### ISSUE TITLE
fail to install 

### ISSUE THREAD

**Issue by trptyrphe** [kvittingseerup/IsoformSwitchAnalyzeR#1]
> biocLite("IsoformSwitchAnalyzeR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).
Installing package(s) ‘IsoformSwitchAnalyzeR’
Warning message:
package ‘IsoformSwitchAnalyzeR’ is not available (for R version 3.4.0)

**Comment by jbergenstrahle** [comment]
How was this solved? having the same issue

**Comment by kvittingseerup** [comment]
You might need to specify that you want to use the development version of Bioconductor by sepcifying:

    useDevel(devel = TRUE)

**Comment by jbergenstrahle** [comment]
There we go, thank you!
