### ISSUE TITLE
the first jaccardSimilarity check is not working

### ISSUE THREAD

**Issue by boaty** [kvittingseerup/IsoformSwitchAnalyzeR#10]
Hi,

I'm using IsoformSwitchAnalyzeR to analyze kallisto output.
when I ran importRdata() and the script stop at step 5, I got this error message from createSwitchAnalyzeRlist() function   :
"The isoform_id in isoformFeatures and isoformCountMatrix does not match"

then I realized that my 2 isoform_id lists in isoformFeatures and isoformCounMatrix have different length.

In script, at importRdata() step 1, there's a check point for isoform_id lists similarity, but somehow it did not work.
In my case, the jaccardsimilarity() returns 0.91. But the stop() function is not triggered so the script went on and error appeared in step 5 when it checks the second time for isoform_id lists similarity.

I used kallisto to map read on transcript and I used ensembl gtf. I also changed manually column name form transcript_id to isoform_id to fit my data.
Is it possible to explain a lit bit more about why use jaccordsimilarity here ? why not just use intersect isoform_id to filter data?

In importRdata() step 1, the script choose to work on intersect of isoform_id lists if jaccardsimilarity > 0.95 but reject to continue if it is <0.95, is this 0.95 threshold for some reason ?

thanks in advance
yz

**Comment by kvittingseerup** [comment]
Hi Yz

Thanks for reporting this. Which version of IsoformSwitchAnalyzeR are you using?

Cheers
Kristoffer

**Comment by boaty** [comment]
Thank you

I checked the version, it is 1.0.0. It's not the latest version...

I installed the package directly by bioconductor, biocLite(), seems I need to update it manually...

Thanks

Yz

**Comment by kvittingseerup** [comment]
Please note bioconductor have switched to use BiocManager (instead of
biocLight).

To get the latest version of IsoformSwitchAnalyzeR start R and enter:

if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("IsoformSwitchAnalyzeR", version = "devel")


If you don't have BiocManager you can install it by typing

install.packages('BiocManager')



Den fre. 27. jul. 2018 kl. 17.22 skrev boaty <notifications@github.com>:
