### ISSUE TITLE
Alpha Threshold difficult to adjust for switchPlot 

### ISSUE THREAD

**Issue by alexg9010** [kvittingseerup/IsoformSwitchAnalyzeR#100]
Hi,

First of all, thank you for this great package and especially the extensive vignette that you are providing, this is really amazing.

I wanted to report a small bug, that occurs when one wants to adjust the significance levels of the switchPlot. 
If I adjust the `alphas`, via the argument nothing changes, but I have to wrap the specification via the `additionalArguments` parameter.

```
data("exampleSwitchListAnalyzed")
# normal
switchPlot(switchAnalyzeRlist = exampleSwitchListAnalyzed,gene='ZAK',condition1 = 'COAD_ctrl',condition2 = 'COAD_cancer')
# no change visible
switchPlot(switchAnalyzeRlist = exampleSwitchListAnalyzed,gene='ZAK',condition1 = 'COAD_ctrl',condition2 = 'COAD_cancer',alphas = c(0.5,0.000001))
# alphas changed
switchPlot(switchAnalyzeRlist = exampleSwitchListAnalyzed,gene='ZAK',condition1 = 'COAD_ctrl',condition2 = 'COAD_cancer',additionalArguments = list(alphas = c(0.5,0.000001)))
```

I guess this happens because you are not using the `alphas` argument of the switchPlot function, but use a redefined version in the internal default value list `eArgList`.  
https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/blob/83ddf636eb61247d31dcc466a2bd3bf970c94efb/R/isoform_plots.R#L2800-L2826

I know that the alpha cutoffs that you chose are widely used, but sometimes it is necessary to adjust them. 

Best,
Alex

**Comment by kvittingseerup** [comment]
Hi Alex

Nice catch. It will be fixed in the next update.

Cheers
Kristoffer
