### ISSUE TITLE
No gene_q_value or iso_q_value reported

### ISSUE THREAD

**Issue by jennshah** [kvittingseerup/IsoformSwitchAnalyzeR#101]
Hi there,

I imported data from Stringtie using importRdata, then successfully ran IsoformSwitchAnalysisPart1, followed by IsoformSwitchTestDEXSeq, on my SwitchList. The problem is that my results report "NA" for all gene_q_value and iso_q_value fields. All other fields look fine, including isoform_switch_q_value and gene_switch_q_value. Any idea why this might be happening? How should I interpret this? In the switch plots for gene and isoform expression, there do seem to be differences between groups, so I'd like to report q values if they can be generated.

Thanks!

**Comment by kvittingseerup** [comment]
Hi.

Thanks for reaching out.

The IsoformSwitchTest* functions only identify isoforms switches. You can follow [this link](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#adding-differential-gene-expression) to the vignette to see how to add differential expression analysis.

Cheers
Kristoffer
