### ISSUE TITLE
 Error in tximport::tximport(files = localFiles, type = tolower(dataAnalyed$orign),  :    all(txId == raw[[txIdCol]]) is not TRUE

### ISSUE THREAD

**Issue by kdinesh777** [kvittingseerup/IsoformSwitchAnalyzeR#102]
Hi, 

I have performed HISAT2 Stringtie and ballgown pipeline and reached till end with my own data. 

while using isoformswitchanalyzer, I am facing problem. 

proble: 
 salmonQuant <- importIsoformExpression(parentDir = "ballgown/", readLength = 150 )
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: StringTie
    Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 Error in tximport::tximport(files = localFiles, type = tolower(dataAnalyed$orign),  : 
  all(txId == raw[[txIdCol]]) is not TRUE

i saw some of you suggestion and used 

if (!requireNamespace("devtools", quietly = TRUE)){
  install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)

but still the sae problem persist. 

may you please help me to rectify this. 

Thanks in Advance

**Comment by kvittingseerup** [comment]
I think I need more info about how you did the last part of the analysis.

Could you [read this](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use) and tell me how closely what you did resembles this?

**Comment by kdinesh777** [comment]
Thanks for your kind reply, 
brief about work flow I used: 
#reference index was created using ensemble gtf file and genome fasta file using hisat2
#I have six sample SRR_33, SRR_34, SRR_35, SRR_42, SRR_43, SRR_45 which were mapped using hisat2 and sorted and converted to bam using samtools.
#stringtie to assemble transcripts for each sample was used.
#stringtie was run to merge all the results which gave 6 files as output for each samples i.e e_data.ctab, e2t.ctab, i_data.ctab, i2t.ctab, SRR_33.gtf, t_data.ctab
# I have got differentially expressed genes and transcripts using balgown package in R.

after that I want to use isoformswitchanalyseR. 

as per the 

library(IsoformSwitchAnalyzeR)
# I used 
card_ips <- importIsoformExpression(parentDir = "ballgown", readLength = 150)

to import data from stringtie but got error:

Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: StringTie
    Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 Error in tximport::tximport(files = localFiles, type = tolower(dataAnalyed$orign),  : 
  all(txId == raw[[txIdCol]]) is not TRUE

I found your suggestion to run below command for other error, 
I ran it
if (!requireNamespace("devtools", quietly = TRUE)){
  install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
but still the problem persists. 
please suggest what I can do to resolve the issue.

**Comment by kdinesh777** [comment]
Thanks for your kind reply,
brief about work flow I used:
#reference index was created using ensemble gtf file and genome fasta file
using hisat2
#I have six sample SRR_33, SRR_34, SRR_35, SRR_42, SRR_43, SRR_45 which
were mapped using hisat2 and sorted and converted to bam using samtools.
#stringtie to assemble transcripts for each sample was used.
#stringtie was run to merge all the results which gave 6 files as output
for each samples i.e e_data.ctab, e2t.ctab, i_data.ctab, i2t.ctab,
SRR_33.gtf, t_data.ctab
I have got differentially expressed genes and transcripts using balgown
package in R.

after that I want to use isoformswitchanalyseR.

as per the

library(IsoformSwitchAnalyzeR)
I used

card_ips <- importIsoformExpression(parentDir = "ballgown", readLength =
150)

to import data from stringtie but got error:

Step 1 of 3: Identifying which algorithm was used...
The quantification algorithm used was: StringTie
Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 Error in tximport::tximport(files = localFiles, type =
tolower(dataAnalyed$orign), :
all(txId == raw[[txIdCol]]) is not TRUE

I found your suggestion to run below command for other error,
I ran it
if (!requireNamespace("devtools", quietly = TRUE)){
  install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR",
build_vignettes = TRUE)
but still the problem persists.
please suggest what I can do to resolve the issue.

[image: image.png]

*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
From your description, I just need you to clarify. Did you rerun StringTie with the '-eB' option on each of the 6 samples using the result of the stringtie --merge run (as [described here](https://ccb.jhu.edu/software/stringtie/index.shtml?t=manual#de))?

Also I cannot recommend doing differential expression analysis with Balgown. It is not maintained anymore, it performs very poorly in all benchmarks and is not even used by the authors themselves.

**Comment by kdinesh777** [comment]
Yes, I did.

here is flow of commands after mapping,

#  Assemble transcripts for each sample:

x="SRR_33 SRR_34 SRR_35 SRR_42 SRR_43 SRR_44"

# than bash runner
for i in $x; do
stringtie/stringtie -p 8 -G hg38_103.gtf -o ${i}.gtf -l ${i} ${i}.bam
done

#Merge transcripts from all samples:

stringtie --merge -p 8 -G guman_genome.gtf -o stringtie_merged.gtf
mergelist.txt


# bash runner to estimate transcript abundances and create table counts for
ballgown

x="SRR_33 SRR_34 SRR_35 SRR_42 SRR_43 SRR_44"
for i in $x; do
stringtie/stringtie -e -B -p 8 -G stringtie_merged.gtf -o
ballgown/${i}/${i}.gtf ${i}.bam
done

the output of the last command provides 6 files.



thanks,




*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kdinesh777** [comment]
Dear,

I want to learn isoformswitchanalyze.

I used hisat pipeline and used stringtie output.
First command worked well.
aSwitchlist making problem.

May you provide link for the data you have used for your tool validation.

May you please guide me how to perform analysis from stringtie out put.
Please take any human RNAseq data.

May you please make any video for analysis or tutorial and share on YouTube
or on your official site.

It will make a great difference.

**Comment by kvittingseerup** [comment]
Sorry, I'm confused. Did you solve the problem with importIsoformExpression()?

If you have a different problem please check if it has been answered before here on Github or the [google group](https://groups.google.com/g/isoformswitchanalyzer). If it has not, please make a new issue to keep the issue tracking neatly organised :)

**Comment by kdinesh777** [comment]
Dear Kristoffer,
No, I am not able to resolve the problem. I used the stringtie command as
it was given in publication as such.
Shall re run stringtie using '-eB'.
may you please draft me the command to run the same.  I am not getting
properly.
thanks,



*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
Hi 

I would say that your StringTie commands you posted in [this response](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/issues/102#issuecomment-795208281) look correct. But the error you get is because the files in each directory are different ([see here](https://support.bioconductor.org/p/96588/#96597)). Are you sure you point to the right parent directory?

Cheers
Kristoffer

**Comment by kdinesh777** [comment]
Dear Kristoffer, I re-ran the string tie from beginning till end.
now the first command works properly as given below:



> test_data <- importIsoformExpression("ballgown_1/", readLength = 150)
Step 1 of 3: Identifying which algorithm was used...
The quantification algorithm used was: StringTie
Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 3 4 5 6
Step 3 of 3: Normalizing abundance values (not counts) via edgeR...
Done


I have tried with both the annotations files: separately
> aSwitchList <- importRdata(
  +   isoformCountMatrix   = test_data$counts,
  +   isoformRepExpression = test_data$abundance,
  +   designMatrix         = myDesign,
  +   isoformExonAnnoation = "hg38_103.gtf",
  +   showProgress = FALSE
  + )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
importing GTF (this may take a while)
Done.
Error in importRdata(isoformCountMatrix = test_data$counts,
isoformRepExpression = test_data$abundance,  :
                       The annotation and quantification (count/abundance
matrix and isoform annotation) seems to be different (Jaccard similarity <
0.925).
                     Either isforoms found in the annotation are not
quantifed or vise versa.
                     Specifically:
                       244213 isoforms were quantified.
                     234393 isoforms are annotated.
                     Only 0 overlap.
                     244213 isoforms quantifed had no corresponding
annoation

                     This combination cannot be analyzed since it will
cause discrepencies between quantification and annotation thereby skewing
all analysis.

                     If there is no overlap (as in zero or close) there are
two options:
                       1) The files do not fit together (e.g. different
databases, versions, etc) (no fix except using propperly paired files).
2) It is somthing to do with how the isoform ids are stored in the
different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
Examples from expression matrix are : MSTRG.31618.1, ENST00000681355,
ENST00000552423
Examples of annoation are : ENST00000586149.1, ENST00000532499.1,
ENST00000577376.5
Examples of isoforms which were only found im the quantification are  :
ENST00000439570, ENST00000548223, ENST00000674042

If there is a large overlap but still far from complete there are 3
possibilites:
  1) The files do not fit together (e.g different databases versions etc.)
(no fix except using propperly paired files).
2) If you are using Ensembl data you have supplied the GTF without
phaplotyps. You need to supply the
<Ensembl_version>.chr_patch_hapl_scaff.gtf file - NOT the
<Ensembl_version>.chr.gtf
3) One file could contain non-chanonical chromosomes while the other do not
(might be solved using the 'removeNonConvensionalChr' argument.)
4) It is somthing to do with how a subset of the isoform ids are stored in
the different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

For more info see the FAQ


with Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.gtf.gz

> aSwitchList <- importRdata(
  +   isoformCountMatrix   = test_data$counts,
  +   isoformRepExpression = test_data$abundance,
  +   designMatrix         = myDesign,
  +   isoformExonAnnoation =
"Homo_sapiens.GRCh38.103.chr_patch_hapl_scaff.gtf.gz",
  +   showProgress = FALSE
  + )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
importing GTF (this may take a while)
Done.
Error in importRdata(isoformCountMatrix = test_data$counts,
isoformRepExpression = test_data$abundance,  :
                       The annotation and quantification (count/abundance
matrix and isoform annotation) seems to be different (Jaccard similarity <
0.925).
                     Either isforoms found in the annotation are not
quantifed or vise versa.
                     Specifically:
                       244213 isoforms were quantified.
                     256183 isoforms are annotated.
                     Only 0 overlap.
                     244213 isoforms quantifed had no corresponding
annoation

                     This combination cannot be analyzed since it will
cause discrepencies between quantification and annotation thereby skewing
all analysis.

                     If there is no overlap (as in zero or close) there are
two options:
                       1) The files do not fit together (e.g. different
databases, versions, etc) (no fix except using propperly paired files).
2) It is somthing to do with how the isoform ids are stored in the
different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
Examples from expression matrix are : MSTRG.11590.1, ENST00000460632,
ENST00000470363
Examples of annoation are : ENST00000331434.7, ENST00000640646.1,
ENST00000641844.2
Examples of isoforms which were only found im the quantification are  :
ENST00000662382, ENST00000498089, ENST00000669554

If there is a large overlap but still far from complete there are 3
possibilites:
  1) The files do not fit together (e.g different databases versions etc.)
(no fix except using propperly paired files).
2) If you are using Ensembl data you have supplied the GTF without
phaplotyps. You need to supply the
<Ensembl_version>.chr_patch_hapl_scaff.gtf file - NOT the
<Ensembl_version>.chr.gtf
3) One file could contain non-chanonical chromosomes while the other do not
(might be solved using the 'removeNonConvensionalChr' argument.)
4) It is somthing to do with how a subset of the isoform ids are stored in
the different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
For more info see the FAQ

Suggest solution

Thanks,

*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
Dear Dr. Kumar

Good that you got `importIsoformExpression()` to work. 

Could you let me know how you interpret the documentation of the _isoformExonAnnoation_ argument for the `importRdata()` function found when typing `?importRdata` in R. I ask because I strive to improve the documentation all the time.

Cheers
Kristoffer

**Comment by kdinesh777** [comment]
Dear Kristoffer,

Thanks for your reply.
I am using an index prepared by HISAT2, a server (256GB RAM).
Geneome fast file was taken
http://ftp.ensembl.org/pub/release-103/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
GTF file was taken
http://ftp.ensembl.org/pub/release-103/gtf/homo_sapiens/Homo_sapiens.GRCh38.103.gtf.gz

Both files were unzipped using gunzip in linux.

extract_splice_sites.py  Homo_sapiens.GRCh38.103.gtf >hg38.ss
extract_exons.py  Homo_sapiens.GRCh38.103.gtf. >hg.exon

Second, build a HISAT2 index:
hisat2-build --ss chrX.ss --exon
Homo_sapiens.GRCh38.dna.primary_assembly.fa genome_tran
It gave me eight files with extension .ht2

I renamed GTF file  Homo_sapiens.GRCh38.103.gtf.gz  to  hg38_103.gtf.gz
The same GTF file I have used for Stringtie.

As far as concern with *isoformExonAnnoation* argument for the importRdata()in
R the file I have given the location of the zipped file of  hg38_103.gtf.gz
the same file I have used for Stringtie.
Please suggest a solution.

Thanks,






*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kdinesh777** [comment]
Dear Kristoffer,

please ignore earlier mail.

Thanks for your reply. You're doing great effort and helping all the people
to learn and do their analysis.

I am using an index prepared by HISAT2, a server (256GB RAM).
Geneome fast file was taken
http://ftp.ensembl.org/pub/release-103/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
GTF file was taken
http://ftp.ensembl.org/pub/release-103/gtf/homo_sapiens/Homo_sapiens.GRCh38.103.gtf.gz

Both files were unzipped using gunzip in linux.

extract_splice_sites.py  Homo_sapiens.GRCh38.103.gtf >hg38.ss
extract_exons.py  Homo_sapiens.GRCh38.103.gtf. >hg.exon

Second, build a HISAT2 index:
hisat2-build --ss  hg38.ss --exon  hg.exon
Homo_sapiens.GRCh38.dna.primary_assembly.fa genome_tran

It gave me eight files with extension .ht2

I renamed the GTF file  Homo_sapiens.GRCh38.103.gtf.gz  to  hg38_103.gtf.gz
The same GTF file I have used for Stringtie.
As far as concern with *isoformExonAnnoation* argument for the importRdata()in
R the file I have given the location of the zipped file of  hg38_103.gtf.gz
the same file I have used for Stringtie.
I am interpreting  *isoformExonAnnoation* is the same file which I have
used for making reference indexes and used for stringtie too.
One request and suggestion: As I followed two pipeline (the tuxedo and new
tuxedo) to learn RNAseq data analysis. both of these gave location of raw
files which needed for running protocol. If you can make similar protocol
like (https://www.nature.com/articles/nprot.2016.095), it would be very
easy with example data and relevant files.

Thanks,



Please suggest a solution.

*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
Thanks for your feedback.

You need to supply the gtf file you create with `stringtie --merge` since this is the one you have quantified in the last round of stringtie quantification.

Please [see here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use) for the difference between a reference-based analysis (not what you have done) and a transcript assembly approach (which you have done) and make sure you have use the approach that best suits your scientific questions.

Cheers
Kristoffer

**Comment by kdinesh777** [comment]
Dear Kristoffer,
Thanks for your reply. I have changed GTF file as you suggested. It shows
overlaps but error still persists. Change in results (red colored text)



Overlaps is showing after changing the GTF files but still the same error.

aSwitchList <- importRdata(

+   isoformCountMatrix   = test_data$counts,

+   isoformRepExpression = test_data$abundance,

+   designMatrix         = myDesign,

+   isoformExonAnnoation = "stringtie_merged.gtf",

+   showProgress = FALSE

+ )

Step 1 of 7: Checking data...

Step 2 of 7: Obtaining annotation...

    importing GTF (this may take a while)

Done.

Error in importRdata(isoformCountMatrix = test_data$counts,
isoformRepExpression = test_data$abundance,  :

  The annotation and quantification (count/abundance matrix and isoform
annotation) seems to be different (Jaccard similarity < 0.925).

Either isforoms found in the annotation are not quantifed or vise versa.

Specifically:

 244213 isoforms were quantified.

 244248 isoforms are annotated.

 Only 234655 overlap.

 9558 isoforms quantifed had no corresponding annoation

 This combination cannot be analyzed since it will cause discrepencies
between quantification and annotation thereby skewing all analysis.

 If there is no overlap (as in zero or close) there are two options:

 1) The files do not fit together (e.g. different databases, versions, etc)
(no fix except using propperly paired files).

 2) It is somthing to do with how the isoform ids are stored in the
different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

     Examples from expression matrix are : ENST00000394318,
ENST00000579373, ENST00000568339

     Examples of annoation are : ENST00000638691, ENST00000383985,
ENST00000651549

     Examples of isoforms which were only found im the quantification are  :
MSTRG.289.1, MSTRG.8731.1, MSTRG.6260.23

If there is a large overlap but still far from complete there are 3
possibilites:

 1) The files do not fit together (e.g different databases versions etc.)
(no fix except using propperly paired files).

 2) If you are using Ensembl data you have supplied the GTF without
phaplotyps. You need to supply the
<Ensembl_version>.chr_patch_hapl_scaff.gtf file - NOT the
<Ensembl_version>.chr.gtf

 3) One file could contain non-chanonical chromosomes while the other do
not (might be solved using the 'removeNonConvensionalChr' argument.)

 4) It is somthing to do with how a subset of the isoform ids are stored in
the different files. This problem might be solvable using some of the
'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

 For more info see the FAQ in the vig

In addition: Warning message:

In importRdata(isoformCountMatrix = test_data$counts, isoformRepExpression
= test_data$abundance,  :

     No CDS annotation was found in the GTF files meaning ORFs could not be
annotated.

     (But ORFs can still be predicted with the analyzeORF() function)




Thanks,

*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
This is not a problem with the software but with the files you provide. I cannot help you with this except by encouraging you to go back and double-check which files you used (you have mentioned several re-runs).

**Comment by kdinesh777** [comment]
Ok I will re-run mapping and complete protocol.

will update you.


*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kdinesh777** [comment]
I re-run the whole protocol.

now got different error:

> test_data <- importIsoformExpression("ballgown", readLength = 150)
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: StringTie
    Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 3 4 5 6
Step 3 of 3: Normalizing abundance values (not counts) via edgeR...
Done

>
> aSwitchList <- importRdata(
+   isoformCountMatrix   = test_data$counts,
+   isoformRepExpression = test_data$abundance,
+   designMatrix         = myDesign,
+   isoformExonAnnoation = "stringtie_merged.gtf",
+   ignoreAfterBar = TRUE,
+   showProgress = FALSE
+ )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
    41266 ( 16.84%) isoforms were removed since they were not expressed in
any samples.
Step 3 of 7: Fixing StringTie gene annoation problems...
    6618 isoforms were assigned the gene_name of their associated gene_id.
        This was only done when the parent gene_id were associated with a
single gene_name.
    3281 isoforms were assigned the gene_name of the most similar
        annotated isoform (defined via overlap in genomic exon
coordinates).
        This was only done if the overlap met the requriements
        indicated by the three fixStringTieViaOverlap* arguments.
Error in eval(quote(list(...)), env) :
  argument is missing, with no default
In addition: Warning message:
In importRdata(isoformCountMatrix = test_data$counts, isoformRepExpression
= test_data$abundance,  :
     No CDS annotation was found in the GTF files meaning ORFs could not be
annotated.
     (But ORFs can still be predicted with the analyzeORF() function)

**Comment by kdinesh777** [comment]
Hi kristoffer,

I run the complete protocol again from raw reads till stringtie re-run
after merge.
Again I got the same error,
please help to solve this.


> GSE_17= importIsoformExpression(parentDir = "ballgown/", readLength = 150)
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: StringTie
    Found 6 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 3 4 5 6
Step 3 of 3: Normalizing abundance values (not counts) via edgeR...
Done

> aSwitchList <- importRdata(
+   isoformCountMatrix   = GSE_17$counts,
+   isoformRepExpression = GSE_17$abundance,
+   designMatrix         = myDsign,
+   isoformExonAnnoation = "stringtie_merged.gtf",
+     showProgress = FALSE
+ )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
    44447 ( 18.14%) isoforms were removed since they were not expressed in
any samples.
Step 3 of 7: Fixing StringTie gene annoation problems...
    6588 isoforms were assigned the gene_name of their associated gene_id.
        This was only done when the parent gene_id were associated with a
single gene_name.
    3250 isoforms were assigned the gene_name of the most similar
        annotated isoform (defined via overlap in genomic exon
coordinates).
        This was only done if the overlap met the requriements
        indicated by the three fixStringTieViaOverlap* arguments.
Error in eval(quote(list(...)), env) :
  argument is missing, with no default
In addition: Warning message:
In importRdata(isoformCountMatrix = GSE_17$counts, isoformRepExpression =
GSE_17$abundance,  :
     No CDS annotation was found in the GTF files meaning ORFs could not be
annotated.
     (But ORFs can still be predicted with the analyzeORF() function)

*...*
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
Glad to hear that you can now get the expression data into R.

I believe this problem is solved by upgrading to IsoformSwitchAnalyzeR 1.13.05. Remember to re-start after installing it as R sometimes cannot update an R package already loaded.

Let me know if it works.

Cheers
Kristoffer

**Comment by kdinesh777** [comment]
Dear Kristoffer,
I am having R 4.0.5. in windows 10.
While installing isoformswitchanalyser  using Biocmanager, it installs
older version only.
As you suggested to upgrade IsoformSwitchAnalyzeR 1.13.05 tried to install
it is still installing version 1.12 only.
> BiocManager::install("IsoformSwitchAnalyzeR")
'getOption("repos")' replaces Bioconductor standard
repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.12 (BiocManager 1.30.12), R 4.0.5
  (2021-03-31)
Installing package(s) 'IsoformSwitchAnalyzeR'
trying URL '
https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/IsoformSwitchAnalyzeR_1.12.0.zip
'
Content type 'application/zip' length 5016755 bytes (4.8 MB)
downloaded 4.8 MB

package ‘IsoformSwitchAnalyzeR’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\Dr Dinesh Kumar\AppData\Local\Temp\Rtmpamk7MC\downloaded_packages
Old packages: 'dbplyr', 'devtools', 'GenomeInfoDb',
  'pkgload', 'rtracklayer'


I installed R 4.1 and tried to install IsoformSwitchAnalyzeR 1.13.05  then
it showed a problem that rtracklayer can not be installed.

is there any way to install latest version of IsoformSwitchAnalyzeR 1.13.05.

thanks for your guidance

*... *
*Dr. Dinesh Kumar (Ph.D)*
Scientist B
ICMR-NICPR,
Noida.
Ph: 7988288306

**Comment by kvittingseerup** [comment]
That is because 1.13.05 is in the developmental branch of Bioconductor. You can find instructions for installing from devel [here](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR#installation).

Cheers
Kristoffer
