### ISSUE TITLE
The annotation and quantification (count/abundance matrix and isoform annotation) seems to be different (Jaccard similarity < 0.925).

### ISSUE THREAD

**Issue by soleilll** [kvittingseerup/IsoformSwitchAnalyzeR#104]
Hello,

I've used salmon for quantification. And it all went well with following code:

`salmon index -t Mus_musculus.GRCm38.cdna.all.fa.gz -i GRCm38_ref_index --type quasi -k 31
for i in Prmt7_{1..10};do samp=`basename ${i}`; echo "Processing sample ${samp}"; salmon quant -i ../../gencodevM25_ref_index -l A -1 ${samp}_1.fq -2 ${samp}_2.fq -p 8 -o quants_new/${samp}_quant;done`

Then for isoformSwitchR when I'm building the SwitchList I used the paired gtf and cdna: 

`switchList <- importRdata(isoformCountMatrix=isoformExpr$counts, isoformRepExpression=isoformExpr$abundance, designMatrix=designM, isoformExonAnnoation="/public/home/lixinjie/public1/GRCm38genome/Mus_musculus.GRCm38.94.chr.gtf", isoformNtFasta="/public/home/lixinjie/public1/GRCm38genome/gencode.vM25.annotation.gtf.gz")`

But it went wrong with this message:
> Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Error in importRdata(isoformCountMatrix = isoformExpr$counts, isoformRepExpression = isoformExpr$abundance,  :
  The annotation and quantification (count/abundance matrix and isoform annotation) seems to be different (Jaccard similarity < 0.925).
Either isforoms found in the annotation are not quantifed or vise versa.
Specifically:
 118782 isoforms were quantified.
 112714 isoforms are annotated.
 Only 112023 overlap.
 6759 isoforms quantifed isoforms had no corresponding annoation

This combination cannot be analyzed since it will cause discrepencies between quantification and annotation thereby skewing all analysis.

If there is no overlap (as in zero or close) there are two options:
 1) The files do not fit together (e.g. different databases, versions, etc) (no fix except using propperly paired files).
 2) It is somthing to do with how the isoform ids are stored in the different files. This problem might be solvable using some of the 'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
     Examples from expression matrix are : ENSMUST00000020827.6, ENSMUST00000068879.10, ENSMUST00000154469.7
     Examples of annoation are : ENSMUST00000027688.14, ENSMUST00000129123.1, ENSMUST00000061799.9
     Examples of isoforms which were only found im the quantification are  : ENSMUST00000234203.1, ENSMUST00000118366.8, ENSMUST00000235857.1

If there is a large overlap but still far from complete there are 3 possibilites:
 1) The files do not fit together (e.g different databases versions etc.) (no fix except using propperly paired files).
 2) If you are using Ensembl data you have supplied the GTF without phaplotyps. You need to supply the <Ensembl_version>.chr_patch_hapl_scaff.gtf file - NOT the <Ensembl_version>.chr.gtf
 3) One file could contain non-chanonical chromosomes while the other do not (might be solved using the 'removeNonConvensionalChr' argument.)

For more info see the FAQ in the vignette.

So how can i solve this problem?

**Comment by kvittingseerup** [comment]
Could you verify if you quantified the gencodevM25 or the GRCm38 index? Both seem to be mentioned in your code?

**Comment by soleilll** [comment]
I am sorry the code above seems to be messed up.  

The right code is:
1、bulid index
`salmon index -t Mus_musculus.GRCm38.cdna.all.fa.gz -i GRCm38_ref_index --type quasi -k 31`
2、quantified
`for i in Prmt7_{1..10}
do 
samp=basename ${i};
echo "Processing sample ${samp}";
salmon quant -i  GRCm38_ref_index -l A -1 ${samp}_1.fq -2 ${samp}_2.fq -p 8 -o quants/${samp}_quant
done`

**Comment by soleilll** [comment]
i used the GRCm38 index at the first time. But i got this error, so i am trying to use gencode files to test if this will help.

**Comment by kvittingseerup** [comment]
Then your problem is most likely that the Ensembl fasta and GTF file does not contain the same transcripts (which they don't unless you download the right files). You can read more [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-transcript-database-should-i-use).

Let me know if using the right files works.

Also make sure to use the corresponding fasta file as input to imporRdata.

**Comment by soleilll** [comment]
Yes, it is exactly the problem that the Ensembl fasta and GTF file does not contain the same transcripts.
With gencode files, it goes well.

> Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Step 3 of 6: Calculating gene expression and isoform fraction...
     32082 ( 23.03%) isoforms were removed since they were not expressed in any samples.
Step 4 of 6: Merging gene and isoform expression...
  |======================================================================| 100%
Step 5 of 6: Making comparisons...
  |======================================================================| 100%
Step 6 of 6: Making switchAnalyzeRlist object...
Done

Thank you very much!
