### ISSUE TITLE
Error with importRdata

### ISSUE THREAD

**Issue by MuradOmarov** [kvittingseerup/IsoformSwitchAnalyzeR#108]
Hello! 
I'm really impressed by your great work! Could you help me?  I'm interested in analysis of novel and known isoforms. My pipeline was:
1) Alignment with hisat2 to genome (hg37) four different samples without replicates.
2) StringTie-provided transcriptome de novo assembly for every sample (with providing -G - reference annotation) 
3) Merging with Stringtie merge
4) Obtaining fasta of transcripts with gffread.
5) Mapping reads with Salmon to obtained transcripts.

So, my code in IsoformSwitchAnalyzeR looks like: 

```salmonQuant <- importIsoformExpression(
  parentDir ='/Users/murad/Desktop/Course/Salmon/'
)

myDesign <- data.frame(
  sampleID = colnames(salmonQuant$abundance)[-1],
  condition = gsub('_.*', '', colnames(salmonQuant$abundance)[-1])
)
aSwitchList <- importRdata(
  isoformCountMatrix   = salmonQuant$counts,
  isoformRepExpression = salmonQuant$abundance,
  designMatrix         = myDesign,
  isoformExonAnnoation = ("merged_transcripts.gtf"),
  fixStringTieAnnotationProblem = TRUE,
  showProgress = FALSE,isoformNtFasta = 'Transcripts.fasta'
)
```
And I got this error: 
Error in if (m == 0) { : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In importRdata(isoformCountMatrix = salmonQuant$counts, isoformRepExpression = salmonQuant$abundance,  :
  The experimental design seems to be of very low complexity - very few samples per replicate. Please check the supplied design matrixt to make sure no mistakes were made.
2: In importRdata(isoformCountMatrix = salmonQuant$counts, isoformRepExpression = salmonQuant$abundance,  :
  
!!! NB !!! NB !!! NB !!!NB !!! NB !!!
IsoformSwitchAnalyzeR is not made to work with conditions without indepdendet biological replicates and results will not be trustworthy!
At best data without replicates should be analyzed as a pilot study before investing in more replicates.
Plase consult the "Analysing experiments without replicates" and "What constitute an independent biological replicate?" sections of the vignette.
!!! NB !!! NB !!! NB !!!NB !!! NB !!!

3: In importRdata(isoformCountMatrix = salmonQuant$counts, isoformRepExpression = salmonQuant$abundance,  :
  We found 723 (0.34%) unstranded transcripts.
  These were removed as unstranded transcripts cannot be analysed
4: In importRdata(isoformCountMatrix = salmonQuant$counts, isoformRepExpression = salmonQuant$abundance,  :
     No CDS annotation was found in the GTF files meaning ORFs could not be annotated.
     (But ORFs can still be predicted with the analyzeORF() function)
5: In importRdata(isoformCountMatrix = salmonQuant$counts, isoformRepExpression = salmonQuant$abundance,  :
  The annotation and quantification (count/abundance matrix and isoform annotation) Seem to be slightly different. 
Specifically:
 385 isoforms were only found in the annotation
 
Please make sure this is on purpouse since differences will cause inaccurate quantification and thereby skew all analysis.
 If you have quantified with Salmon this could be normal since it as default only keep one copy of identical sequnces (can be prevented using the --keepDuplicates option)
 We strongly encurage you to go back and figure out why this is the case.

6: In voom(counts = localDGE, design = localModel, normalize.method = "none",  :
  The experimental design has no replication. Setting weights to 1.

Also I switched aSwitchList$isoformFeatures$gene_switch_q_value to 1 after Example data importing as was guided in your wonderful documentation. 
Could you help me and give me advice? 

Thank you in advance! 

Best regars,
Murad

**Comment by MuradOmarov** [comment]
estimateDifferentialGeneRange=FALSE fixed the error Error in if (m == 0) { : missing value where TRUE/FALSE needed, 
But all the warnings remained. Could I continue my analysis with such errors? 
I want to use analyzeNovelIsoformORF() to extract isoforms with uORFs and detect switching between samples. 
I need your expert opinion.
Thanks in advance

**Comment by kvittingseerup** [comment]
Thanks for reaching out. It is not problematic to run with `estimateDifferentialGeneRange=FALSE`.

Cheers
Kristoffer
