### ISSUE TITLE
large overlap but still far from complete

### ISSUE THREAD

**Issue by jayshin-agc** [kvittingseerup/IsoformSwitchAnalyzeR#109]
Hi,

The overlap is relatively large:

 139450 isoforms were quantified.
 139289 isoforms are annotated.
 Only 139196 overlap.
 254 isoforms quantifed had no corresponding annoation

but I am still getting an error message in step 2 out of 7 with the following script. 
I've tried the recommended fixes but no luck. 

Can you advise?

aSwitchList <- importRdata(
    isoformCountMatrix   = salmonQuant$counts,
    isoformRepExpression = salmonQuant$abundance,
    designMatrix         = myDesign,
    isoformExonAnnoation = "gencode.vM25.chr_patch_hapl_scaff.annotation.gtf",
    isoformNtFasta       = "gencode.vM25.transcripts.fa",
    fixStringTieAnnotationProblem = TRUE,
    showProgress = FALSE, 
    ignoreAfterPeriod = TRUE, 
    removeNonConvensionalChr = TRUE
)

**Comment by jayshin-agc** [comment]
> packageVersion("IsoformSwitchAnalyzeR")
[1] '1.13.7'
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS:   /opt/local/R-4.0.3/lib/R/lib/libRblas.so
LAPACK: /opt/local/R-4.0.3/lib/R/lib/libRlapack.so

**Comment by kvittingseerup** [comment]
Hi.

To help you I would need you to tell me about how you quantified your data, which annotation was used for the quantification and how you obtained the annotation :-)

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Closing issue due to no response.
