### ISSUE TITLE
Issues with isoform analysis from Salmon quantification

### ISSUE THREAD

**Issue by csijcs** [kvittingseerup/IsoformSwitchAnalyzeR#11]
I am trying to figure out how to use IsoformSwitchAnalyzeR to quantify isoform abundance and identify isoform switches with data from Salmon quantification.  I'm really stuck at the very beginning.  I have not been able to import the data, and when I did by accident I couldn't generate a SwitchAnalyzeRlist or run the analysis.  Do you have a guide for Salmon analysis?  I have tried to follow along with the Cufflinks analysis and do the equivalent with Salmon data, but not having much success.  I have done tximport and DEseq/edgeR analysis with the same data no problem.  Trying to do isoform analysis now and not having much luck.  

I am currently running:

`mySwitchList <- importIsoformExpression(files)`

and I get:

```
Step 1 of 3: Identifying which algorithm was used...
Error in dirList[sapply(dirList, FUN = function(aDir) { : 
  invalid subscript type 'list'
```

$files is a directory the contains a subdirectory for each sample with the quant.sf file in each directory.  That's all that is in the directory.

Any help would be much appreciated

**Comment by csijcs** [comment]
Hi Kristoffer,

Thanks for your reply.  In answering your question I realized my error, sorry about that.  I now have the data imported, but am having trouble in the analysis.  Particularly I am stuck at the analyzeCPAT step.  It this something that needs to be run externally and then the results supplied?  I'm having trouble figuring out how to extract the information in R.

Best,
Joe

**Comment by kvittingseerup** [comment]
Hi Joe

Good to hear. From the workflow overview (found [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#quick-start)) you are right that the CPAT (and SignalP and PFAM for that matter) analysis are external. 

You can find descriptions of how to run the external tools (and prepare extract the results) either in the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#advice-for-running-external-sequence-analysis-tools) or in the "Details" section of the function documentation for the import (aka analyzeCPAT, analyzePFAM and analyzeSignalP) .

To run the external prediction tools you just need the biological sequences, which are outputted as two fasta files by IsoformSwitchAnalyzeR either via the isoformSwitchAnalysisPart1() or the extractSequence() function.

Hope this helps.

Cheers
Kristoffer

**Comment by csijcs** [comment]
Hi Kristoffer,

It's working great for me now, thanks so much for your help.  One minor comment, I get a few errors running the PFAM on the hmmscan ebb tool.  They won't accept input sequences longer than 1000 characters, so I just had to trim half a dozen or so. 

Best,
Joe

**Comment by kvittingseerup** [comment]
Thanks for letting me know. I have updated the cutoffs in extractSequence() to match their new cutoffs so it will be available in the next release.

**Comment by csijcs** [comment]
Hi Kristoffer,


Sorry to trouble you again but I’ve come across another issue I could use your advice on.  The fasta files I’ve generated are quite large and contain many sequences, in fact too many for the external tools to analyze.  For the CPAT analysis I
 had to split the fasta into 10 different files, analyze separately, then concatenate the results.  That wasn’t so bad.  For the PFAM analysis, the HMM tool on ebi will only accept 500 sequences per file, and my file has over 50,000.  So this is a bit of a
 problem.  I can do the analysis 100 times, but is there an easier way?
Thanks for your help.


J


On Aug 17, 2018, at 1:59 PM, Kristoffer Vitting-Seerup <notifications@github.com> wrote:


Thanks for letting me know. I have updated the cutoffs in extractSequence() to match their new cutoffs so it will be available in the next release.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.








Important: This email is confidential and may be privileged. If you are not the intended recipient, please delete it and notify us immediately; you should not copy or use it for any purpose, nor disclose its contents to any other person. Thank you.

**Comment by kvittingseerup** [comment]
Hi Joe

Did you use the preFilter() function to remove lowly expressed features?

Did you run the isoformSwitchTestDRIMSeq() function? If so did you use the "reduceToSwitchingGenes = TRUE" argument? This will reduce the switchAnalyzeRlist to only genes with statistical evidence of switching - thereby omitting the need to analyse all isoforms/genes.

If you still find this many genes/isoforms of interest, or want to analyze all of them anyway, you need to download and run the tools on your own computer/server instead - you can find the download instructions on their homepages.

Cheers
Kristoffer

**Comment by csijcs** [comment]
Hi Kristoffer,


I did run preFilter.  I had not tried isoformSwitchTestDRIMSeq(switchAnalyzeRlist, reduceToSwitchingGenes=TRUE).  I tried this now and got the following error:


Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels


I will look into downloading the standalone versions and running locally.


Best,
Joe


On Aug 17, 2018, at 8:51 PM, Kristoffer Vitting-Seerup <notifications@github.com> wrote:


Hi Joe
Did you use the preFilter() function to remove lowly expressed features?
Did you run the isoformSwitchTestDRIMSeq() function? If so did you use the "reduceToSwitchingGenes = TRUE" argument? This will reduce the switchAnalyzeRlist to only genes with statistical evidence of switching - thereby omitting the need to analyse
 all isoforms/genes.
If you still find this many genes/isoforms of interest, or want to analyze all of them anyway, you need to download and run the tools on your own computer/server instead - you can find the download instructions on their homepages.
Cheers
Kristoffer
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.








Important: This email is confidential and may be privileged. If you are not the intended recipient, please delete it and notify us immediately; you should not copy or use it for any purpose, nor disclose its contents to any other person. Thank you.

**Comment by kvittingseerup** [comment]
Could you send me your design matrix? Can be done with:

```
yourSwitchList$designMatrix
```

**Comment by csijcs** [comment]
This prints out a sample file I input:



                                sampleID        run condition filename
1   a6f8ba19-0360-48a9-b5e7-613c5628639f       TCGA       AML quant.sf


There are 193 rows with unique sampleID’s.




On Aug 20, 2018, at 9:01 PM, Kristoffer Vitting-Seerup <notifications@github.com> wrote:


Could you send me your design matrix? Can be done with:
yourSwitchList$designMatrix

—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.








Important: This email is confidential and may be privileged. If you are not the intended recipient, please delete it and notify us immediately; you should not copy or use it for any purpose, nor disclose its contents to any other person. Thank you.

**Comment by kvittingseerup** [comment]
I need to see the design matrix from the switchAnalyzeRlist.

Please send me the output of:

```
head(yourSwitchList$designMatrix)
```

**Comment by csijcs** [comment]
```
head(mySwitchList$designMatrix)
NULL
```
I made mySwitchList with:
```
mySwitchList <- importIsoformExpression(dir,
+                                         calculateCountsFromAbundance=TRUE,
+                                         interLibNormTxPM=TRUE,
+                                         normalizationMethod='TMM',
+                                         pattern='',
+                                         invertPattern=FALSE,
+                                         ignore.case=FALSE,
+                                         showProgress = TRUE,
+                                         quiet = TRUE
+                                         )

```

I had to do a little formatting and preparation:
```
isoformCountMatrix <- mySwitchList$counts
isoformCountMatrix$isoform_id <- sub("\\|.*", "", isoformCountMatrix$isoform_id)
rownames(isoformCountMatrix) <- isoformCountMatrix$isoform_id
isoformAbundanceMatrix <- mySwitchList$abundance
isoformAbundanceMatrix$isoform_id <- sub("\\|.*", "", isoformAbundanceMatrix$isoform_id)
rownames(isoformAbundanceMatrix) <- isoformAbundanceMatrix$isoform_id
gtf <-("/Users/csijcs/Documents/Work/CSI/AML/RNA_seq/gencode.v28.annotation.gtf")
```

I then made with switchAnalyzeRlist:
```
switchAnalyzeRlist <- importRdata(
	isoformCountMatrix,
	isoformAbundanceMatrix,
	samples,
	gtf,
	comparisonsToMake=NULL,
	addAnnotatedORFs=TRUE,
	onlyConsiderFullORF=TRUE,
	removeNonConvensionalChr=TRUE,
	PTCDistance=50,
	foldChangePseudoCount=0.01,
	showProgress=TRUE,
	quiet=FALSE
)

```
samples is the designMatrix for switchAnalyzeRlist, which I sent previously:
head(switchAnalyzeRlist$designMatrix)
```
                              sampleID  run condition filename
1 a6f8ba19-0360-48a9-b5e7-613c5628639f TCGA       AML quant.sf
2 c0a23aca-4b39-4fbc-90c7-3d51a49d81b9 TCGA       AML quant.sf
3 57b89869-6885-4f6b-923f-9af38d919fb5 TCGA       AML quant.sf
4 cdf83522-d571-4b6f-9d3d-3a19941e0f7e TCGA       AML quant.sf
5 a20f007f-3b8b-4732-9da1-ca67c0584dd8 TCGA       AML quant.sf
6 6e605f23-3507-4891-adbd-f010293509a4 TCGA       AML quant.sf
```

**Comment by kvittingseerup** [comment]
Ahh - I think the problem is that columns additional columns in the design matrix (apart from sampleID and condition) are interpreted as cofactors you want to regress out of the test (such as batch effects, effects of gender etc). My guess is then that "run" and "filename" are columns only contain one variable (respectively "TCGA" and "quant.sf") which give rise to the error (DRIMSeq tries to make a contrast with one 1 level).

Try removing them (or replacing them with relevant covariats).

I will implement a test to make sure to give a proper warning for this in the future.

Cheers
Kristoffer

**Comment by csijcs** [comment]
Hi Kristoffer,

You were right, the condition does change for the control, but the filename is the same.  I removed those columns and running isoformSwitchTestDRIMSeq works now.  However, this has now identified even more isoforms than running isoformSwitchTest.  I now have over 80,000 sequences in the fasta.

I installed and ran the standalone version of CPAT and that worked perfectly.  I haven't quite figured out how to run the PFAM analysis on the standalone hmmer though.  Do you have experience with this?

Thanks,
Joe

**Comment by kvittingseerup** [comment]
Hi Joe

Nice to hear that it works! I must admit that sounds like way to much. Could you send me:
1) The output of running extractSwitchSummary() on your switchAnalyzeRlist
2) the entry of the condition part of the switchAnalyzeRlist.

Can be done with:

```
extractSwitchSummary( <insert_your_switch_list> )

<insert_your_switch_list>$conditions
```

Cheers
Kristoffer

**Comment by csijcs** [comment]
Hi Kristoffer,
```
extractSwitchSummary(switchAnalyzeRlist)
   Comparison nrIsoforms nrGenes
1 AML vs Knee      24567   11542
```
```
switchAnalyzeRlist$condition
  condition nrReplicates
1       AML          179
2      Knee           14
```
That makes it seem like there are only 24567 isoforms, which would still be a lot to do in increments of 500, but when I run:
```
grep -e '>' isoformSwitchAnalyzeR_isoform_AA.fasta | wc -l
80702
```

**Comment by csijcs** [comment]
I see.  Unfortunately TCGA doesn't have a proper control for AML samples, so the best I can do it try and use a comparable data set as a control.  Do you have any experience with using the standalone hmmer for PFAM analysis of the data?  I still haven't been able to get that working, but one that's working I should be able to do the analysis.
Thanks,
Joe

**Comment by kvittingseerup** [comment]
Hi Joe

Unfortunately that is not possible! Datasets cannot be combined like that because of there is a very large effect in high throughput data originating from how, where and when the data was produced. This means that you will end up with two completely overlapping effects in your data: 1) The cancer-non cancer. 2) the batch effect. You will never be able to tell these effects apart so any discovery you might as well be due to the batch effect.

Judging from the number of differential transcript usage you find I would suspect the batch effect is the main effect you see.

I would highly recommend you not to proceed with this - and no reviewer knowing about such a batch effect will allow you to publish. On top of this, if you find something important other people will publish about the weakness of your study - see fx: https://f1000research.com/articles/4-121/v1

Cheers
Kristoffer

**Comment by csijcs** [comment]
Yes, I understand all that. Thanks

**Comment by csijcs** [comment]
Hi Kristoffer,

I have another question for you.  If I wanted to look at isoform expression for a specific gene, but one that is not included in the switchAnalyzeRlist, how would I do that?  I have a gene I am interested in looking as the isoform expression, but it's not identified as a "switching gene", so it's not included in the switchAnalyzeRlist object.

Thanks,
Joe

**Comment by kvittingseerup** [comment]
If you ask the question in the [google group](https://groups.google.com/forum/#!forum/isoformswitchanalyzer) I'll answer it there. Github is better for bug-repports

Remember to add enough context so other can make use of the question as well.

Cheers
Kristoffer
