### ISSUE TITLE
2 genomes to compare

### ISSUE THREAD

**Issue by dancortes22** [kvittingseerup/IsoformSwitchAnalyzeR#111]
Hello
I am comparing 2 mouse strains and I wonder if the package would accept 2 genome reference and transcript sequence files instead of one
Thanks
Dan

**Comment by kvittingseerup** [comment]
For the sequence based analysis that should not cause problems but you would have to supply the fasta file with the species specific sequences to `importRdata()` instead of relying on BSgenomes.

For the visualizations it might cause problems since the genomic coordinates will be different (I'm assuming)? Would it be possible to use something like liftOver to fix it?

Cheers
Kristoffer

**Comment by dancortes22** [comment]
Hello Kristoffer
I really appreciate your help, I am not an expert on this type of analysis, do I add one genome annotation or two.

-For the sequence based analysis that should not cause problems but you would have to supply the fasta file with the species specific sequences to importRdata() instead of relying on BSgenomes.
   --how would the pipeline would look like? I don't know how i tell the pipeline what sequence belongs to what file
   

For the visualizations it might cause problems since the genomic coordinates will be different (I'm assuming)? Would it be possible to use something like liftOver to fix it?
   --As a non-expert, I don't know if lift would solve it and if I find the coordinates issue downstream the pipeline. would you say it is better if I stick to BSgenomes?

Thanks
Dan

**Comment by kvittingseerup** [comment]
```do I add one genome annotation or two```
I cannot answer that. It depends on how you want to analyze the data and your scientific question.

```--how would the pipeline would look like? I don't know how i tell the pipeline what sequence belongs to what file```
That would need to be handle by having unique ids from each strain.

```would you say it is better if I stick to BSgenomes?```
You cannot solve the genome coordinates with BSgenomes - those are just for sequences.

I'm sorry I cannot be of more help.
