### ISSUE TITLE
CPAT 3 vs CPAT2

### ISSUE THREAD

**Issue by dancortes22** [kvittingseerup/IsoformSwitchAnalyzeR#113]
I used CPAT3 instead of CPAT 2 to get the nucleotide analysis done, however, I've got many files. which one to use? I tired with a couple of them and got some errors

output.ORF_seqs.fa: The top ORF sequences (at least 75 nucleotides long) in FASTA format.
output.ORF_prob.tsv: ORF information (strand, frame, start, end, size, Fickett TESTCODE score, Hexamer score) and coding probability)
output.ORF_prob.best.tsv: The information of the best ORF. This file is a subset of “output.ORF_prob.tsv”
output.no_ORF.txt: Sequence IDs or BED entries with no ORF found. Should be considered as non-coding.
output.r: Rscript file.
CPAT_run_info.log: log file

Should I stick to the previous version instead?
Thanks
Dan

**Comment by kvittingseerup** [comment]
Unfortunately IsoformSwitchAnalyzeR does not support CPAT3 yet. Until the next update, you will have to use CPAT2 or CPC2.

Cheers 
Kristoffer
