### ISSUE TITLE
Support SignalP v6.0

### ISSUE THREAD

**Issue by lvclark** [kvittingseerup/IsoformSwitchAnalyzeR#124]
I got an error that "No signal peptides were found" when importing results from SignalP v6.0, even though there are some in the output.  I took a quick look at the source code for `analyzeSignalP` and saw that v4.0 is assumed if it does not say v5.0 in the header.

**Comment by kvittingseerup** [comment]
That is correct. I've not yet found time to implement support for SignalP v6 but it is on the to-do list.
In the meantime, you can re-run the with SignalP 5.
