### ISSUE TITLE
error about  isoformSwitchTestDEXSeq

### ISSUE THREAD

**Issue by Indigofera** [kvittingseerup/IsoformSwitchAnalyzeR#13]
Hi, 
When I tried to identify  Isoform Switches, I used  Isoform Switches via DEXSeq. But I got this error: "Error in isoformSwitchTestDEXSeq(switchAnalyzeRlist = exampleSwitchListFiltered,  : 
  could not find function "isoformSwitchTestDEXSeq".

Thank you.

**Comment by kvittingseerup** [comment]
Which version of IsoformSwitchAnalyzeR are you using?

You can check it by running  the following in your R terminal

```
packageVersion("IsoformSwitchAnalyzeR")
```

**Comment by Indigofera** [comment]
version '1.3.7'

**Comment by kvittingseerup** [comment]
That sounds very strange. How did you install it?

Could you try to reinstall it with this command:
```
BiocManager::install("IsoformSwitchAnalyzeR", version = "devel")
```

**Comment by Indigofera** [comment]
I reinstall and update all package but I got the same error.

**Comment by Indigofera** [comment]
I restarted R then it worked.

**Comment by kvittingseerup** [comment]
Good to hear you got it working.

If you have more problems please dont hesitate to contact me again.
