### ISSUE TITLE
IgnoreAfter arguments cause IDs to be non-unique

### ISSUE THREAD

**Issue by MarLee39** [kvittingseerup/IsoformSwitchAnalyzeR#131]
Hi,

Thanks for the nice tools! 
I got an error when importing my salmon quantification data (IsoformSwitchAnalyzeR version 1.8).
my command and error are the followings.

data <- importIsoformExpression(parentDir) 
Step 1 of 3: Identifying which algorithm was used...     
The quantification algorithm used was: Salmon     
Found 114 quantification file(s) of interest 
Step 2 of 3: Reading data... reading in files with read_tsv 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 ..... 114
Step 3 of 3: Normalizing FPKM/TxPM values via edgeR... 
Error in fixNames(nameVec = rownames(localDataList$abundance), ignoreAfterBar = ignoreAfterBar,  :    
The application of the ignoreAfter<Character> arguments would cause IDs to be non-unique (not allowed).

It looks like that isoform IDs are the problem. 
I quantified short-read RNA-seq data using my own annotation detected nanopore RNA-Seq. 
Any insight as to what might be going on here?

The isoform IDs made by nanopore-flair pipline are little bit strange like '45:584|bc8091d4-5929-435f-8922-6ea68d8cbf56'....
If this is the cause of the problem, is there any way to be able to use this uniq ID in this tool?

Thanks

**Comment by kvittingseerup** [comment]
Take a look at the three `ignoreAfter*` arguments of `importIsoformExpression ` and try turning them off :-)
