### ISSUE TITLE
large sample size

### ISSUE THREAD

**Issue by ChiaraCaprioli** [kvittingseerup/IsoformSwitchAnalyzeR#134]
Hi, 

I am interested in performing a characterization similar to that provided by IsoformSwitchAnalyzeR to analyze a large number of isoforms across thousands of samples, with many replicates for each condition of interest. Do you think IsoformSwitchAnalyzeR can reach that scalability? Do you have any suggestion to handle a trial?

Thank you

**Comment by kvittingseerup** [comment]
Unfortunatly IsoformSwitchAnalyzeR does not currently support such sample sizes. Currently, you would have to 

1. Do your DTU analysis with a tool of your choice (check out our recent benchmark [here](https://f1000research.com/articles/10-374))
2. Create a dummy switchAnalyzeRlist with importGTF()
3. Manually overwrite the condition_* and switch_*_q_value columns in the switchAnalyzeRlist with the results of step 1. (you can also add expression etc)

P.s. sorry for the slow response
