### ISSUE TITLE
Error during importRdata process

### ISSUE THREAD

**Issue by jamlover** [kvittingseerup/IsoformSwitchAnalyzeR#135]
Hello. I have been encountering an error when trying to get up and running with isoformSwitchAnalyzeR. I have been trying to debug this myself but have decided to give up and request assistance.

I have constructed a small test data set and reduced metadata file that results in the same error I see when I've tried to run importRdata with my full data set. Below are my commands (with R terminal "+" signs from the "aSwitchList <- importRdata" command removed) and the resulting output, including the error message, from an attempt with the test data set.
____________________________________________________________________________________________________________________
> library(IsoformSwitchAnalyzeR)
> setwd("L:/Lab/HTS/John/janineEsrEtcGenes")
> meta <- read.table("metadata_test.txt", head=T, sep="\t", as.is=T)
> myDesign <- data.frame(sampleID = meta[,1],condition = meta[,7])
> rsemQuant<-importIsoformExpression(parentDir = ("iso_data_test/"))
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: RSEM
    Found 8 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 3 4 5 6 7 8 
Step 3 of 3: Normalizing abundance values (not counts) via edgeR...
Done

> aSwitchList <- importRdata(
    isoformCountMatrix   = rsemQuant$counts,
    isoformRepExpression = rsemQuant$abundance,
    designMatrix         = myDesign,
    isoformExonAnnoation = "L:/Lab/HTS/John/janineEsrEtcGenes/janines.46trans.mod.gtf",
    isoformNtFasta       = "L:/Lab/HTS/John/janineEsrEtcGenes/janinesMiniGenome.46trans.mod.fas",
    fixStringTieAnnotationProblem = TRUE,
    ignoreAfterBar = TRUE,
    ignoreAfterSpace = TRUE,
    ignoreAfterPeriod = TRUE,
    removeTECgenes = FALSE,
    showProgress = FALSE
 )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
Step 3 of 7: Fixing StringTie gene annoation problems...
    There were no need to fix any annotation
Step 4 of 7: Calculating gene expression and isoform fractions...
Step 5 of 7: Merging gene and isoform expression...
Step 6 of 7: Making comparisons...
Step 7 of 7: Making switchAnalyzeRlist object...
Error in `$<-.data.frame`(`*tmp*`, "condition_1", value = "control") : 
  replacement has 1 row, data has 0
______________________________________________________________________________________________________________________________
I believe I have attached all the files that would be necessary to recreate the error. Can I please get some help with this?

Thanks,
John Martinson
[metadata_test.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/8665000/metadata_test.txt)
[testdataGtfFasta.zip](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/8665077/testdataGtfFasta.zip)

**Comment by tf1993614** [comment]
Hi jamlover,

I was also stuck with this step. But the problem in my case is the GTF file. I downloaded my GTF file from Ensembl database. However, when I input it into importRdata function and the error always comes out. So I am wondering where did you download your GTF file? Did you do any modification on the GTF file before you input it into importRdata function?

Thanks,

Feng

**Comment by jamlover** [comment]
Feng,

Most of the gtf file started as an NCBI gff (I think I started with a gff and converted it to a gtf with gffread), and one small part of it (one gene) was made based on our own gene/transcript predictions from EvidenceModeler/PASA. Further, the genomic sequences were reduced to just +/-3500 bases around each gene of interest (there are only about 8 genes I think) and the gtf coordinates were adjusted to reflect that subsampling. So yes, the gtf was definitely modified, but the structure of the gtf is so basic I figured that probably wasn't the problem. To check on that though, I tried using the importGTF function directly and it seemed to work without showing any errors, so I thought that confirmed the gtf was ok . But based on what you are saying it sounds like that may not be the case.

Is there any specific guidance on exactly what the key format/features/tags must be in the gtf file for it to work properly with IsofromSwitchAnalyzeR? I looked at the example gtf.gz that came with isofromSwitchAnalyzeR and thought my gtf looked about the same in terms of basic structure, but I guess I will try looking again to see if I see any structural differences.

I am also wondering, are there any rules about the definition lines or sequences in the transcript fasta file that must be met? As of now I have very simple deflines that just show the basic transcript identifier that matches the transcript ids in the gtf file. (I guess I better double check that file too, but I think I have it right).

Thanks,
John

**Comment by tf1993614** [comment]
Hi John，

Thanks a lot for your detailed explanation about what you did with your GTF file.  However, I am still struggling with it.

My counts were produced from salmon aligner. I mentioned the IsoformSwitchR author's comment in the user manual that the GTF file feed for importR function should be the same one used for establishing salmon index. However, when I established my normal salmon index (not the decoy-aware one), I didn't use any GTF file. So I am wondering what kind of aligner did you use?
salmon, RSEM or kallisto?

I aslo tried to use the Grange object to feed for Import R function. Although in this way importR function ran successfully and didn't show any error, I am not sure if I did right things. As for how I got the Grange object, you can see my code in #136 .

I also exported Grange object file into a excel and attached here. Compared to GTF file, the Grange object is not only contains the information the GTF file must has such as seqname, feature, start, end, strand, transcript_id, gene_id, but also consists of other annotation information. I have to say It makes sense for me to feed it for importR function. How do you think about it?

Thanks,

Feng

**Comment by tf1993614** [comment]
[Granges.zip](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/8674501/Granges.zip)

**Comment by tf1993614** [comment]
The Grange object file is here.
[Granges.zip](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/8674508/Granges.zip)

**Comment by jamlover** [comment]
Thanks for your update Feng.

I may have solved my problem it appears. On a small test set I removed all references to the single  internally generated gene model and it's transcripts (which were named with our own simple internal id scheme). To be thorough I removed their gene and isoform RSEM-generated count data from the RSEM output, removed all lines referring to them from my gtf file, and I removed their sequences from the transcript fasta file. After doing that the importRdata command worked. I am nest going to try to give our internal data/sequences "dummy" names that mimic NCBI style names to see if I can reincorporate that data successfully.

Feng, I am not sure what I have found will help you out, but perhaps it will. I found how to make it work by working with a very small test set that I could manually adjust without much effort, so if you haven't already been trying that, I suggest you too work with a very limited test set to see if you can isolate your problem. Good luck!

I will leave this issue open until I see if I can reintroduce the data I removed successfully. I will report back.

**Comment by jamlover** [comment]
So it turns out if I remove all the lines representing elements of a single specific transcript (one of eight) from my gtf file, and also remove all lines for this transcript from my RSEM "isosforms.results" files for each sample, the error does not occur. I tried removing potential hidden white space characters from all the lines in the results and gtf file associated with that transcript, but that did not do anything. So for now I am remapping my data, after removing all lines for that transcript model from my input files, but that is obviously not an ideal solution. So, any potential ideas on what I might try next to fix this, so I'm able to include the data for that transcript rather than leaving it out, would be greatly appreciated. Thanks.

**Comment by tf1993614** [comment]
Hi John,

Thanks a lot for your detailed response. 

Yes. I also found the error comes out when the number of transcript in the GTF file is not consistent with that in the output file from salmon or RSEM. Therefore, it seems that removing all non-consistent information both in GTF file and salmon's output is an reasonable way to figure out this problem. Obviously, you have already proved it.

I also used this strategy when I fed Grange object to importR function. As I said before, this also enable me to run the importR function successfully. However, I am still waiting for the response from the IsoformSwitchR author to check if what I did is right or not (#136). Once I got any response, I will let you know. 

I am going to try the modified GTF file as you suggested and compare it with my current result. I will also keep this update. 

Thanks,

Feng

**Comment by kvittingseerup** [comment]
Hi @jamlover - sorry for the slow response.

Just to make sure I understand you correctly: The problem seem to be a single transcript that you manually added? But not the other transcripts you added?

**Comment by jamlover** [comment]
Yes, that did seem to be the problem. But now I experienced the same error with a modified data set that didn't include that transcript. So now I am going to try a little more troubleshooting (or perhaps in my case, it's troublemaking) on my own and I will let you know where I stand after doing that.

Thanks,
John

**Comment by jamlover** [comment]
At this point I have overcome the issue. I am not sure if the solution was switching to the development version of IsoformSwitchAnalyzerR, but it seems that when I installed that version is when it started working. I am not certain what version I was using before, but it may have been 1.12. Currently my version shows 1.17.04. So I think it is time to close this issue. If I run into anymore issues though, rest assured you will hear about them!
