### ISSUE TITLE
GTF file error with importR function

### ISSUE THREAD

**Issue by tf1993614** [kvittingseerup/IsoformSwitchAnalyzeR#136]
Hi Kvitting,

I was struggling with importR step and the GTF file error always comes out like XXX isoforms have been quantified but only XXX isoforms have been annotated. I downloaded my GTF file from Ensembl database, so the GTF file should be OK.

I also mentioned your comment in the user manual that the GTF file feed for importR function should be the same one used for establishing salmon index. However, when I established my normal salmon index (not the decoy-aware  one), I didn't use any GTF file.

The code used for establishing normal salmon index is shown below:

`salmon index -t cDNA.fastq.file -i transcript_index -k 31`

So I am confused with your comment in the tutorial.

In the end, I chose to use the Grange object to feed for Import R function. Although importR function ran successfully and didn't show any error,  I am not sure if I did right things.

Firstly, I got the annotation file for each transcript as below:

`ah = AnnotationHub()`
`ah = ah %>% subset(rdataclass == "EnsDb" & species == "Homo sapiens")`
`ensdb = ah [["AH98047"]]`

#extract annotation file for each transcript:
`transcript_anno = transcripts(ensdb)`

#only keep the rows with the transcript_id in the output file from salmon:
`transcript_anno_sub = transcript_anno %>% subset (tx_id_version %in% target_id)`

#change the column name to make sure the Grange object consists of two necessary column names (isoform_id, gene_id):
`names(mcols(transcript_anno_sub ))[7] = "isoform_id"`

Now the **transript_anno_sub** is the Grange object I feed for importR function. Do you think it makes sense?

Thanks,

Feng

**Comment by kvittingseerup** [comment]
If you get that problem when importing the GTF you will get the same if you use another approach to read it into R. The problem is the annotation - not reading it into R.

I think your problem is downloading the right annotation. You can read more [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-transcript-database-should-i-use).
