### ISSUE TITLE
importCufflinksFiles does not recognize gtf file despite is the same I used to run cufflinks, cuffmerge and cuffdiff

### ISSUE THREAD

**Issue by Giuseppe1995** [kvittingseerup/IsoformSwitchAnalyzeR#138]
Hi, I am trying to import some data from a cuffdiff output with the `importCufflinksFiles` function, and the command:
```
importCufflinksFiles(
         ### Core arguments
         pathToGTF="/Users/admin/GRCh37/genes.gtf",
         pathToGeneDEanalysis="gene_exp.diff",
         pathToIsoformDEanalysis="isoform_exp.diff",
         pathToGeneFPKMtracking="genes.fpkm_tracking",
         pathToIsoformFPKMtracking="isoforms.fpkm_tracking",
         pathToIsoformReadGroupTracking="isoforms.read_group_tracking",
         pathToSplicingAnalysis = "splicing.diff",
         pathToReadGroups="read_groups.info",
         pathToRunInfo="run.info",
         isoformNtFasta = NULL,
     
         ### Advanced arguments
         fixCufflinksAnnotationProblem = TRUE,
         addIFmatrix = TRUE,
         estimateDifferentialGeneRange = TRUE,
         quiet = FALSE
     )
```  
and, in the third fase (i.e Obtaining annotation),  I get this error: 

> Error in importCufflinksFiles(pathToGTF = "/Users/admin/GRCh37/genes.gtf",  : 
>   No overlap between isoform annotation and isoform expression data was found

Now, pretty sure that you might think "that's obvious which is the mistake", but in facts I've used this gtf file to run cufflinks, cuffmerge and cuffdiff, and I successfully run all of the above and post-processing with cummeRbunds.
If this may help, I downloaded gtf file from AWS (s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf)

**Comment by kvittingseerup** [comment]
You need to use the GTF file produced by the cuffmerge/cuffdiff :-)
