### ISSUE TITLE
Replicate combined analysis

### ISSUE THREAD

**Issue by medcelerate** [kvittingseerup/IsoformSwitchAnalyzeR#14]
Not particularly an issue but I can't find a reference in the api for handling replicates. Do we simply import multiple, in this case, kallisto quantifications and average the data frames?

**Comment by kvittingseerup** [comment]
Could I get you to ask the question in the associated [google group](https://groups.google.com/forum/#!forum/isoformswitchanalyzer) (github is better for but-repports etc) and also clarify whether you think of biological, technical or bootstrapped replicates?

Cheers
Kristoffer
