### ISSUE TITLE
Using merged assembly but importRdata reported 'There were no need to rescue any annotation'

### ISSUE THREAD

**Issue by Pentayouth** [kvittingseerup/IsoformSwitchAnalyzeR#144]
Dear developer,

Thank you for developing such a easy-to-use tools.

I performed short read RNA-seq assembly and merge with StringTie (use `-G`, or reference guide, in both step), and add gencode v40 annotation with gffcompare. Then I quantified with Salmon and import the data using `importRdata()`.

```
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)...
    38711 ( 10.85%) isoforms were removed since they were not expressed in any samples.
Step 3 of 7: Fixing StringTie gene annoation problems...
    There were no need to rescue any annotation
Step 4 of 7: Calculating gene expression and isoform fractions...
Step 5 of 7: Merging gene and isoform expression...
  |======================================================================| 100%
Step 6 of 7: Making comparisons...
  |======================================================================| 100%
Step 7 of 7: Making switchAnalyzeRlist object...
```

Everything works fine actually, no bugs, warnings or errors. 

I just didn't feel safe because `importRdata()` reported 'There were no need to rescue any annotation' in STEP3, despite that fixStringTieAnnotationProblem and fixStringTieViaOverlapInMultiGenes is TRUE by default.

Could it possibly happen to "home made" assembly? I didn't feel safe because I have a gut feeling that there must be something need to be fixed ...

Could you please give some clues on how to quick check if the.assembly need any "fix"? Thank you very much.

Best regards,
Wang.

**Comment by kvittingseerup** [comment]
That does indeed sound strange. Do you have any transcripts where the name that does not start with "ENS" in your merged GTF file?

**Comment by Pentayouth** [comment]
Yes There are.
![图片](https://user-images.githubusercontent.com/58732746/188469720-10100ce8-52e5-48c6-887a-311f749886fa.png)

**Comment by Pentayouth** [comment]
Here is the code,

```
aSwitchList <- importRdata(
  isoformCountMatrix   = salmonQuant$counts,
  isoformRepExpression = salmonQuant$abundance,
  designMatrix         = designMatrix,
  isoformExonAnnoation = "gffcompare.annotated.gtf",
  isoformNtFasta       = "gffcompare.annotated.fa",
  comparisonsToMake    = comparisons,
  showProgress         = TRUE
)
```

**gffcompare.annotated.gtf** is the merged assembly,
**gffcompare.annotated.fa** is generated from **gffcompare.annotated.gtf** using `gffread`, the same fasta file that used to build Salmon index.

I wonder if it is the right command.

Best regards,
Wang.

**Comment by Pentayouth** [comment]
Here is the code,

```
aSwitchList <- importRdata(
  isoformCountMatrix   = salmonQuant$counts,
  isoformRepExpression = salmonQuant$abundance,
  designMatrix         = designMatrix,
  isoformExonAnnoation = "gffcompare.annotated.gtf",
  isoformNtFasta       = "gffcompare.annotated.fa",
  comparisonsToMake    = comparisons,
  showProgress         = TRUE
)
```

**gffcompare.annotated.gtf** is the merged assembly,
**gffcompare.annotated.fa** is generated from **gffcompare.annotated.gtf** using `gffread`, the same fasta file that used to build Salmon index.

I wonder if it is the right command.

Best regards,
Wang.

**Comment by Pentayouth** [comment]
Dear developer,

I suppose that it may be a good idea to provided an example GTF file which need to be fixed in the tutorial.

Best regards,
Wang.

**Comment by Pentayouth** [comment]
Dear developer,

Now I know what, but still not know why.

I test 2 GTF file:
1. **merge.guide.gtf**: This GTF file is generated by `StringTie --merge`
2. **gffcompare.annotated.gtf**: This GTF file is generated by `gffcompare -r gencode.v40.gtf -o gffcompare merge.guide.gtf` (merge.guide.gtf is the first GTF file)

I used **gffcompare.annotated.gtf** in `importRdata()`,  so this time I try **merge.guide.gtf.** 

To do so, I substitute `isoformExonAnnoation = "gffcompare.annotated.gtf"` with `isoformExonAnnoation = "merge.guide.gtf"`

And the fix step (STEP3) works just fine!
```
Step 3 of 7: Fixing StringTie gene annoation problems...
   59340 isoforms were assigned the ref_gene_id and gene_name of their associated gene_id.
        This was only done when the parent gene_id were associated with a single ref_gene_id/gene_name.
   29301 isoforms were assigned the ref_gene_id and gene_name of the most similar
        annotated isoform (defined via overlap in genomic exon coordinates).
        This was only done if the overlap met the requriements
        indicated by the three fixStringTieViaOverlap* arguments.
   We were unable to assign 2125 isoforms (located within annotated genes) to a known ref_gene_id/gene_name. 
        These were removed to enable analysis of the rest of the isoform from within the merged genes.
   3666 gene_ids which were associated with multiple ref_gene_id/gene_names
        were split into mutliple genes via their ref_gene_id/gene_names.
    53563 genes_id were assigned their original gene_id instead of the StringTie gene_id.
        This was only done when it could be done unambiguous.
```

I guess `gffcomapre` fix the GTF file in advance.

I will try to figure out which pipeline is better:
1. `stringtie --merge` → `gffcompare` fix → `importRdata()` without fix
or
2. `stringtie --merge`  → `importRdata()` fix

**Comment by kvittingseerup** [comment]
Thanks for letting me know about the gffcompare approach :-)

Are the results then identical?

**Comment by Pentayouth** [comment]
Not identical.
