### ISSUE TITLE
Custom GTF from TALON lacks CDS annotation, use of addORFfromGTF()

### ISSUE THREAD

**Issue by callumparr** [kvittingseerup/IsoformSwitchAnalyzeR#145]
I wanted to confirm that what I am doing is correct:

Previously in long-read dataset assembly using TALON. I extracted a GTF file and from that a transcriptome file from the database and then used this map and estimate the isoform counts from the original FASTQ data (because some reads are filtered out during TALON database generation). 

I used the talon_create_GTF module from TALON to extract both gencode annotated isoforms/genes, and the novel genes and transcripts. However, this GTF file only has the gene, isoform, and exon levels of annotation and not the CDS or 5' and 3' UTR levels.

Is possible to place back in these for the original gencode ENSG/ENST by using the `addORFfromGTF() `function and the original gencode.v39.annotation.gtf I originally used for initializing the TALON database? Of course, the TALONT will still lack ORF information but then these novel transcripts can use the other tools in annotating this. 

I am also wondering if is it necessary to` preFitler()` because I noticed the console output when reading in the salmon data files, that single-isoform genes and lowly expressed ones were removed.

**Comment by kvittingseerup** [comment]
You have just perfectly described the use-case for `addORFfromGTF()`. Also, IsoformSwitchAnalyzeR has the `analyzeNovelIsoformORF()` function which then uses Gencode annotation to annotate the novel transcripts (when applicable).

`importRdata()` only does the bare minimum filtering. preFilter allows you to be a bit more strict which is usually nice since lowly expressed features are harder to test statistically or might not be of interest.

**Comment by callumparr** [comment]
Thank you. for the reply and confirmation.

**Comment by callumparr** [comment]
Sorry ,I should have read the documentation more fully. I followed the workflow to add the ORFs from gencode and then use analyzeORF for the rest of the novel transcripts but I noticed before and after that it seems analyzeORF is overwriting some of the known gencode annotation ORFs 

after addORFfrom GTF() the original aSwitchList there were around 71,000 annotated transcripts with ORF from gencode brought in. 

```
> aSwitchList$orfAnalysis$orf_origin == "Annotation" -> x
> aSwitchList$orfAnalysis$orf_origin == "not_annotated_yet" -> y
> sum(x) + sum(y)
[1] 261747
> sum(x)
[1] 71394
> sum(y)
[1] 190353
```

I then ran the DEXseq test

```
aSwitchListDEX <- isoformSwitchTestDEXSeq(
  switchAnalyzeRlist = aSwitchList,
  reduceToSwitchingGenes = TRUE
)
```

And then analyzed the transcripts without any ORF. Selecting `analysisAllIsoformsWithoutORF = TRUE`

```
aSwitchListDEX <- analyzeNovelIsoformORF(switchAnalyzeRlist = aSwitchList,
                                         analysisAllIsoformsWithoutORF = TRUE, 
                                         showProgress = TRUE) 

```

Now it seems some must be overwritten as there are more predicted values than original Annotation values. I thought the predicted value should only replace the previous slots that had Not_yet_annotated.

```
> aSwitchListDEX$orfAnalysis$orf_origin == "Annotation" -> z
> aSwitchListDEX$orfAnalysis$orf_origin == "Predicted" -> a
> sum(z) + sum(a)
[1] 261747
> sum(z)
[1] 44672
> sum(a)
[1] 217075
```

**Comment by kvittingseerup** [comment]
That does indeed sound strange. Do you get the same results if you do not run `isoformSwitchTestDEXSeq()` first?

Also could you try using `table(aSwitchList$orfAnalysis$orf_origin, exclude = NULL)` instead of `sum()`?

**Comment by callumparr** [comment]
sorry, I think I was being stupid the way I was running it means I wasn't comparing like for like as I saved the results of DTU to a new Rlist object and when I added the CDS from the gencode annotation I was saving that to hew Rlist but the old one without the DTU results, so in the end, I wasn't even comparing like for like.

**Comment by kvittingseerup** [comment]
So is there a problem when you re-run it? 🤔

**Comment by callumparr** [comment]
> So is there a problem when you re-run it? 🤔

No, it is all good now.
