### ISSUE TITLE
Adding custom RNA characteristics to the Rlist such as poly-A tail length

### ISSUE THREAD

**Issue by callumparr** [kvittingseerup/IsoformSwitchAnalyzeR#147]
I was wondering if it's possible to add in custom characteristics of polyA length estimated from the representative reads of that transcript.

Previously I have analyzed the lengths using [nanopolish polya](https://nanopolish.readthedocs.io/en/latest/quickstart_polya.html) which works from the direct RNA raw signal to provide an estimation.

And then used [pipeline-polya-diff](https://github.com/nanoporetech/pipeline-polya-diff) to test if there is an overall difference for each isoform between several conditions including young vs old mice, SPF vs germ-free housing and male vs female. 

The intention would be to bring in the already tested differences at the level of the isoform for each transcript so it could be combined with the other consequences already in the Rlist. Like if the isoformSwitch results in polyA length difference shorter or longer. Or if there is some connection with last exon and poly-A length.

Related to this is possible to add other consequences without rewriting over the existing list. Like if I just add intron retention but later after running pfam I add domain disorder. I tried this and it seems to overwrite the existing intron retention information.

**Comment by kvittingseerup** [comment]
I like the idea thanks for suggesting it! 

Unfortunately I currently don't have the bandwidth to improve IsoformSwitchAnalyzeR 😞 .

But it seems fairly easy to do:
1) Create a function that reads in and adds the polyA data
2) Add a test (the [pipeline-polya-diff](https://github.com/nanoporetech/pipeline-polya-diff) uses a simple Wilcox test) to the `analyzeSwitchConsequences()` function (via the hidden `compareAnnotationOfTwoIsoforms()` that does the actual comparison).

**Comment by callumparr** [comment]
Sure, I understand I didn't mean to imply piling more work on your plate 

For now, I can try merging the information from both sets of analyzes in more of a manual way for interesting isoforms. 

I may have little play around. Might be something in this.

https://github.com/smaegol/nanotail

**Comment by kvittingseerup** [comment]
Not to worrie, I really appreciate you reached out 🙂
