### ISSUE TITLE
importRData error

### ISSUE THREAD

**Issue by Merlino-git** [kvittingseerup/IsoformSwitchAnalyzeR#148]
Hi!

I'm trying to analyze some quantification data generated using bowtie2 for the alignment and RSEM for the quantification of the transcripts, but I get an error that I cannot figure out how to solve it. When using the importRData function, during (or after?) step 2 I encounter this:

Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Error in subsetSwitchAnalyzeRlist(gtfSwichList, !gtfSwichList$isoformFeatures$isoform_id %in%  : 
  Nothing is left after subsetting.

I checked fasta, gtf and quantification files and the transcript ids are there and match. I share also the directory from which I downloaded the fasta and annotation files in case it's of any help (https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/)

I did not encountered this problem before using STAR as aligner and Ensembl ids, is it possible that RefSeq ids are the issue?
Thank you in advance!

**Comment by kvittingseerup** [comment]
Thanks for reaching out!

Which version of IsoformSwitchAnalyzeR are you using?

Could you post the code for how you use `importRdata()`?

**Comment by kvittingseerup** [comment]
Could you try using IsoformSwitchAnalyzeR 1.16.3 or higher?

If that does not work could you post the first couple of lines of `RSEMQuant$counts` and your `GCF_000001405.40_GRCh38.p14_genomic.gtf` file?

**Comment by Merlino-git** [comment]
Hi, I tried updating using the standard Biocmanager::install command but it doesn't update further than 1.10.0. Do I have to change repositories? I'm not familiar with that.

**Comment by Merlino-git** [comment]
Ok so I managed to update to the 1.17.04 version, but I still get the same error. I attach two text files with the first few lines of the gtf file and the counts

[head_gtf.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/9625894/head_gtf.txt)
[head_counts.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/9625899/head_counts.txt)

**Comment by kvittingseerup** [comment]
That seem strange

Do the chromosome names in the GTF file look strange?

Does it work running IsoformSwitchAnalyzeR::importGTF() on the GTF file?


Den tor. 22. sep. 2022 kl. 13.57 skrev Merlino-git ***@***.***

**Comment by Merlino-git** [comment]
I wasn't familiar with the RefSeq annotation but the chromosomes seem fine to me (as NC_000001.11 is chromosome 1 and so on). Also in the GRCh38.p14 transcripts fasta file the reference seems to be the same. I also tried using the fasta generated by RSEM when preparing the reference but it resulted in the same error.

Using importGTF() it does work, can I assign the counts, abundances and conditions to the switchList created with the importGTF()?

**Comment by kvittingseerup** [comment]
Would you be willing to share the data with me so I can debug this? I would naturally keep it confidential and delete it once I was done debugging. If so can you email me the `RSEMQuant` object (e.g. via `save()` and GTF file?

**Comment by Merlino-git** [comment]
No problem at all, I'll send you the files today. Do you need also the fasta file of the transcripts?

**Comment by Merlino-git** [comment]
Hey! Just wanted to update you. I re-aligned an quantified using Ensembl annotation (107) and it is now working. 

Please let me know if you find out what's causing the issue with the RefSeq annotated data.
