### ISSUE TITLE
Is transcript expression normalised for length?

### ISSUE THREAD

**Issue by royfrancis** [kvittingseerup/IsoformSwitchAnalyzeR#149]
![0070_switch_plot_ENSG00000153283_aka_CD96](https://user-images.githubusercontent.com/5083500/201097494-95db7298-2932-4c7c-8f41-512410418e68.png)

In this figure, subplot "Isoform expression", it makes sense to compare expression of a transcript across conditions (light grey vs dark grey). But, is it ok to compare the expression of various transcripts within the same group? ie; Does transcript ENST00000438817 have the same expression as ENST00000465428 in the light grey group? These two isoforms have very different lengths.

**Comment by kvittingseerup** [comment]
All expression (and isoform fractions) are corrected for lengths either through the abundance estimates you supply for the switchAnalyzeRlist or through RPKM calculation

**Comment by royfrancis** [comment]
Ok thanks. Just wanted to confirm.
