### ISSUE TITLE
Sashimi plots

### ISSUE THREAD

**Issue by royfrancis** [kvittingseerup/IsoformSwitchAnalyzeR#150]
Just wondering if there is a good way to generate sashimi plots from the IsoformSwitchAnalyzer results for a set of selected genes? The sashimi plots from miso are so pretty 🤩!

![](https://miso.readthedocs.io/en/fastmiso/_images/sashimi-plot-example.png)
https://miso.readthedocs.io/en/fastmiso/sashimi.html

**Comment by kvittingseerup** [comment]
Unfortunately not. Those plots require exon and junction coverage which is a completely different quantification than what IsoformSwitchAnalyzeR is build for :)
