### ISSUE TITLE
extractSplicingGenomeWide puzzling result

### ISSUE THREAD

**Issue by istolarek** [kvittingseerup/IsoformSwitchAnalyzeR#152]
I'm using a function extractSplicingGenomeWide and got a result that is hard for me to interpret.

For one of the splicing types (ATTS), the function returns statistical significance (***) both for testing between isoforms with ATTS and for comparison of isoforms without ATTS (bottom row in the picture).
Normally with one comparison being significant and the other not, I would interpret this, i.e. isoforms with some splicing type being used more often.

However, when I got a double positive result, what does it mean?

All of the steps are done as required by the vignette

![splicing_perspective](https://user-images.githubusercontent.com/5182707/206223589-dba0a51f-d62b-42be-acf1-6c40a3a83fd4.png)

**Comment by kvittingseerup** [comment]
Are the results not in opposite directions (would be easier to see if you left the quantile dots in the plot)?

What does the data.frame you get back with the test results state?

**Comment by kvittingseerup** [comment]
And sorry for the long response time - January has been crazy :-S

**Comment by istolarek** [comment]
here is that last row with ATTS before I butchered the quantile information out of it:

![Beznazwy-3](https://user-images.githubusercontent.com/5182707/215522446-aad7270c-f28e-433a-98c7-fc164f27c8f7.png)


and this is the summary from extractSplicingGenomeWide about this particular comparison:

  comparison category isoform_feature    n medianIF1 medianIF2   medianDIF   wilcoxPval   wilcoxQval significance

47  n30 vs n4     ATTS       With ATTS 4210 0.1917187 0.2181375  0.02641875 1.217630e-09 7.305781e-09          ***
48  n30 vs n4     ATTS    Without ATTS 1679 0.3401125 0.2997750 -0.04033750 6.248337e-05 1.874501e-04          ***

**Comment by kvittingseerup** [comment]
My hunch was right. If you format the table you pasted, you can see the medianDIF has opposite signs 😃
