### ISSUE TITLE
Older versions?

### ISSUE THREAD

**Issue by OlgaVT** [kvittingseerup/IsoformSwitchAnalyzeR#153]
Hi,

where could I find the older version of IsoformSwitchAnalyzeR to install? In particular, I am interested in 1.18. Thank you!

**Comment by OlgaVT** [comment]
I understand but I need to keep the analysis uniform. I analyzed the previous datasets with 1.18 and the current one I would also like to analyze using the same version.

**Comment by kvittingseerup** [comment]
Sorry for the long response time - January has been crazy :-S

You will have to go back through the older Bioconductor release to find it
