### ISSUE TITLE
Error when reading CPC2 archive

### ISSUE THREAD

**Issue by lukais-iohan** [kvittingseerup/IsoformSwitchAnalyzeR#154]
Hi

I'm having trouble in run the second part of Isoform Swtich pipeline. Everytime I run the code I get the error bellow:

`
Step 1 of 5 : Importing external sequence analysis...
Error in analyzeCPC2(switchAnalyzeRlist = switchAnalyzeRlist, pathToCPATresultFile = pathToCPC2resultFile,  : 
  There seems to be a problem with the CPC2 result file. Please check it is the rigth file and try again`

I ran the CPC2 stand alone version, not the website version. I think the table produced is correct, as you can see bellow:

[astrocyte_cpc2.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/10261577/astrocyte_cpc2.txt)

**Comment by kvittingseerup** [comment]
Sorry for the long response time - January has been crazy :-S

Does it work if you use the webserver (on a subset of the data)?

**Comment by lukais-iohan** [comment]
Hi, @kvittingseerup 

I've executed Isoform Switch's second phase. The problem was that I tried the new CPC2 algorithm, and it appears that Isoform cannot manage the outcomes of the new CPC2 algorithm.
However, everything functioned properly with CPC2's older version (version 2).
I believe that Isoform will benefit from the ability to detect data from the new CPC2 and Netsurfp2 versions.

**Comment by kvittingseerup** [comment]
What do you mean by "the new CPC2 algorithm" (the 2 in CPC2 referees to v2 - is there a v3)?

**Comment by lukais-iohan** [comment]
Sorry, there is only a new version of NetsurfP (v3 - https://services.healthtech.dtu.dk/service.php?NetSurfP-3.0).

**Comment by kvittingseerup** [comment]
Thanks :)
