### ISSUE TITLE
custom gtf

### ISSUE THREAD

**Issue by zwardnz** [kvittingseerup/IsoformSwitchAnalyzeR#16]
Hi,
I used stringtie v1.3.3 https://ccb.jhu.edu/software/stringtie/ which is similar to cufflinks in that it assembles de novo transcripts. I use the gtf file from stringtie to index salmon and quantify.

This gtf file only contains information on the transcripts and exons (no CDS entries)
When I try to use this gtf for importRdata I get the error:

> Error in getSeqlevelsReplacementMode(value, seqlevels(x)) : 
>   the supplied 'seqlevels' must be a character vector with no NAs and no duplicates

Am I able to use this custom gtf file??

**Comment by zwardnz** [comment]
Hi @kvittingseerup  thank you for your reply. I have now managed to follow through the vignette: https://bioconductor.org/packages/release/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#predicting-switch-consequences

Can I just check something with you?
My design_matrix is:

sampleID | condition | pair
-- | -- | --
100V_post | post | 1
100V_pre | pre | 1
102V_post | post | 2
102V_pre | pre | 2
103V_post | post | 3
103V_pre | pre | 3
...

After importing the data using this design matrix, is it enough to use the isoformSwitchTestDRIMSeq function to run a paired analysis???

Many thanks.

**Comment by kvittingseerup** [comment]
If you ask the question in the [IsoformSwitchAnalyzeR google group](https://groups.google.com/forum/#!forum/isoformswitchanalyzer) with an emphasis on the paired aspect I will answer it there so other people can find it :-)

Cheers
Kristoffer
