### ISSUE TITLE
importGTF error

### ISSUE THREAD

**Issue by sysbiocoder** [kvittingseerup/IsoformSwitchAnalyzeR#161]
I have installed IsoformSwitchAnalyzeR 1.20.0 using BiocManager::install("IsoformSwitchAnalyzeR")

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2
The package is installed without any error
But when I run
aSwitchList <- importGTF(pathToGTF=system.file("extdata/example.gtf.gz", package="IsoformSwitchAnalyzeR"))
aSwitchList
It generates the following error. 
Importing GTF (this may take a while)...
Massaging annoation...
Massaging annotated CDSs...
 Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
Backtrace:
 1. IsoformSwitchAnalyzeR::importGTF(...)
 3. dplyr:::full_join.data.frame(...)
Run `rlang::last_trace()` to see the full context.

 Is there any way to solve this  error.

**Comment by sysbiocoder** [comment]
I updated to  IsoformSwitchAnalyzeR 1.21.0 and it works

**Comment by biga94** [comment]
How do you install the 1.21.0 version using R 4.2.2?

**Comment by sysbiocoder** [comment]
I downloaded the package and used 
install.packages(path_to_file, repos = NULL, type="source")

**Comment by biga94** [comment]
I've tried as you suggested, but it still stops on the same error as above :(
Now I'm going to produce a GRanges object and trying to bypass this error

**Comment by kvittingseerup** [comment]
An update to dplyr causes the problem. I'll upload a fix soon
