### ISSUE TITLE
Error in `dplyr::full_join()`

### ISSUE THREAD

**Issue by biga94** [kvittingseerup/IsoformSwitchAnalyzeR#162]
From one day to the next, the function `importRdata()` stops at step 2 with the following error:

`Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)...
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
Run `rlang::last_error()` to see where the error occurred.`

What I've understood is that every GTF file I provide to this function (and also `importGTF()`) this error comes out. 
I've tried to update the package to 1.21.0 version, to generate a GRanges file, without success.

Any suggestion?

Best,
Davide

**Comment by kvittingseerup** [comment]
Thanks for reporting it. A change in dplyr causes this.

I'll have a fix ready soon

**Comment by biga94** [comment]
> Thanks for reporting it. A change in dplyr causes this.
> 
> I'll have a fix ready soon

Thank you for your immediate response :-)

Best wishes,

Davide

**Comment by kvittingseerup** [comment]
The problems should now be fixed. Try installing from GitHub as instructed in [the readme](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR).

Again thanks for reporting it

**Comment by biga94** [comment]
The error has been fixed, however there's another problem that emerged at step 6 in importRdata() function. But I'll open another issue for that.

Thank you for the constant support!
Davide

**Comment by tjoy20** [comment]
Thanks for this amazing package. I tried to follow the recommendations on installing the latest version. I have an M1 Mac and the latest version requires  Bioconductor 3.17 and R 4.3. However, these releases are not available yet.  Is there an alternative fix around this.  Please find the error below - 

<error/rlib_error_dots_nonempty>
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
---
Backtrace:
    ▆
 1. └─IsoformSwitchAnalyzeR::importRdata(...)
 2.   ├─base::suppressWarnings(...)
 3.   │ └─base::withCallingHandlers(...)
 4.   └─IsoformSwitchAnalyzeR::importGTF(...)
 5.     ├─dplyr::full_join(...)
 6.     └─dplyr:::full_join.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 5 hidden frames.
> rlang::last_trace(drop = FALSE)
<error/rlib_error_dots_nonempty>
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE

**Comment by tjoy20** [comment]
Thank you! this worked,  had failed initially due to version incompatibility for satuRn- so downloaded the development version for satuRn separately and that did it.
