### ISSUE TITLE
Error with devtools installation

### ISSUE THREAD

**Issue by lab83bio** [kvittingseerup/IsoformSwitchAnalyzeR#163]
I received the following error when trying to install the github version with devtools:

```
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = FALSE)
Downloading GitHub repo kvittingseerup/IsoformSwitchAnalyzeR@HEAD
Error: Failed to install 'IsoformSwitchAnalyzeR' from GitHub:
  Line starting 'person(given="Jeroen ...' is malformed!
```
The issue was solved by forking the rep and by adding a 'TAB' in the second line of the "Authors@R:" field. (However, with some warnings and with build_vignette=FALSE)

devtools version: 2.4.5

**Comment by kvittingseerup** [comment]
Thanks for reporting this. I will upload a fix soon.

**Comment by kvittingseerup** [comment]
The problems should now be fixed. Try installing from GitHub as instructed in [the readme](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR).
