### ISSUE TITLE
Error in h(simpleError(msg, call)) at step 6 of 10 from importRdata()

### ISSUE THREAD

**Issue by biga94** [kvittingseerup/IsoformSwitchAnalyzeR#164]
Hey there, 
after correctly producing my list of isoform expression data and its corresponding design matrix, I've tried to produce my switchAnalyzeRlist, however importRdata() function stops at step 6 of 10 with the following error:

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': error in evaluating the argument 'x' in selecting a method for function 'which': error in evaluating the argument 'table' in selecting a method for function '%in%': object 'switchAnalyzeRlist' not found`

Any suggestions?

Best,

Davide

**Comment by kvittingseerup** [comment]
Thanks for reporting it. Just pushed a fix to IsoformSwitchAnalyzeR 2.01.02.

Let me know if it works.

**Comment by biga94** [comment]
It works like charm! Thank you so much for the continuous support.

Greetings from Italy :-)

Davide
