### ISSUE TITLE
Factor error when running isoformSwitchTestDEXseq

### ISSUE THREAD

**Issue by unawaz1996** [kvittingseerup/IsoformSwitchAnalyzeR#167]
Hi, 

I'm rerunning a script that worked fine a couple of months ago. I keep getting an error at the testing each pairwise comparisons with DEXSeq stage after running the function isoformSwitchTestDEXseq()

```
Step 1 of 4: Correcting for batch effect...
Step 2 of 4: Calculating Isoform Fraction matrix...
Step 3 of 4: Testing each pairwise comparisons with DEXSeq (this might be a bit slow)...
    Estimated run time is: 93.3 min
  |                                                                                                                      |   0%Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [2] is duplicated
```

I did recently install the dev version of the package because of the dplyr issue, so not sure if it could be related to that? I also tried running isoformSwitchTestDRIMSeq(), yet it is not able to find that function for some reason?

There were no changes made the the original script and it is pretty much following the code of the vignette. 

Any help would be amazing! Thanks

**Comment by kvittingseerup** [comment]
Could you try updating to 2.1.4 here from GitHub? Remember to restart R before you run the code again (else the updates might not take effect)

**Comment by unawaz1996** [comment]
All good, was definitely an R issue - version did not update properly the first time
