### ISSUE TITLE
Switchplot function require analyzeDeepTMHMM()?

### ISSUE THREAD

**Issue by gregvall** [kvittingseerup/IsoformSwitchAnalyzeR#169]
Hello,

Apologies if this is a silly question. I have been attempting to use the switchPlotTopSwitches function but ran into the error below:

switchPlotTranscript(switchAnalyzeRlist = tArgList$switchAnalyzeRlist,  : 
  Cannot plot toplogy as it has not been added. Either you first use analyzeDeepTMHMM() or you set "topologyAnalysis=FALSE".
Error: with piece 1: 
  gene_id gene_name condition_1 condition_2 gene_switch_q_value switchConsequencesGene           comparison
1   CASP1     CASP1     Control   Responder        0.0004798947                   TRUE Control_vs_Responder
  switchConsequencesGeneDescription                                                                      outputName

I was unable to find anything it the manual about analyzeDeepTMHMM()  function. Is this an error or something that is new in order to run the function? Thought I'd make sure this is not some sort of error.

I look forward the hearing back from you

Greg

**Comment by kvittingseerup** [comment]
It is not an error. IsoformSwitchAnalyzeR now supports the visualization of topology predictions from DeepTmHMM. 

You can find more info by typing `?analyzeDeepTMHMM ` in your R terminal or check the NEWS file.

I now realize this is not a nice behavior to throw an error and will change it to a message. 

I also now realize more info about these needed to the vignette - thanks for letting me know.

Both updates are in IsoformSwitchAnalyzeR 2.01.05
