### ISSUE TITLE
multiple instances of the same gene_id on different chromosomes?

### ISSUE THREAD

**Issue by zwardnz** [kvittingseerup/IsoformSwitchAnalyzeR#17]
Hi Kristoffer,

I am getting the following error when I run imnportRdata:

> In createSwitchAnalyzeRlist(isoformFeatures = isoAnnot, exons = isoformExonStructure,  :
>   The gene_ids were not unique - we identified multiple instances of the same gene_id on different chromosomes. To solve this we removed 22205 genes. Please note there might still be duplicated gene_id located on the same chromosome.

I imported my data after Salmon quantification with:
```
parent_dir<-("analysis/results/05b_salmon_counts/")
ie<-importIsoformExpression(
  parent_dir,
  calculateCountsFromAbundance=TRUE,
  interLibNormTxPM=TRUE,
  normalizationMethod='TMM'
)
```
I then use the following for importRdata:

```

aSwitchList <- importRdata(
  isoformCountMatrix=ie$counts,
  designMatrix=design_matrix,
  isoformExonAnnoation=myGTF,
  removeNonConvensionalChr=TRUE
)
```

I have attached a copy of my GTF file (it's not standard as I am using the annotation created after running stringtie (which also looks ar de novo transcripts)
Is there an issue with my GTF file can you tell me??
[myGTF.zip](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/2448062/myGTF.zip)

I am using isoformSwitchAnalyzeR v.1.2.0

**Comment by kvittingseerup** [comment]
Could you update to IsoformSwitchAnalyzeR 1.3.9 from [here](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html).

I could not open your GTF file. Could you send me just 50 lines of it as a txt file instead?

How did you merge the individual stringtie GTF files into one?

Cheers
Kristoffer

**Comment by zwardnz** [comment]
Hi Kristoffer,

I have updated to IsoformSwitchAnalyzeR 1.3.9. Now when I run:
salmonQuant <- importIsoformExpression(
  parentDir = system.file("analysis/results/05b_salmon_counts/"),
  addIsofomIdAsColumn = TRUE
)
I get:

Step 1 of 3: Identifying which algorithm was used...
Error in dirList[sapply(dirList, FUN = function(aDir) { : 
  invalid subscript type 'list'

The oath is correct and inside '05b_salmon_counts are multiple sub-directories - one per sample. 

Please help??

**Comment by zwardnz** [comment]
Hi Kristoffer,

I have updated to 1.3.9.
I have run:
```
parent_dir<-("analysis/results/05b_salmon_counts/")
ie<-importIsoformExpression(
  parent_dir,
  calculateCountsFromAbundance=TRUE,
  interLibNormTxPM=TRUE,
  normalizationMethod='TMM'
)
myGTF <- rtracklayer::import('analysis/results/02_stringtie/stringtie_merged.gtf')

aSwitchList <- importRdata(
  isoformCountMatrix=ie$counts,
  isoformRepExpression = ie$abundance,
  designMatrix=design_matrix,
  isoformExonAnnoation=myGTF,
  removeNonConvensionalChr=TRUE,
  showProgress = TRUE
)
```
I now get the error:

> Step 1 of 5: Obtaining annotation...
> Error in importRdata(isoformCountMatrix = ie$counts, isoformRepExpression = ie$abundance,  : 
>   The 'type' column of the data supplied to 'isoformExonAnnoation' indicate there are multiple levels of data. Please fix this or provide a string with the path to the GTF file (then IsoformSwitchAnalyzeR will import the file as well).

I have attached 50 lines of my gtf file as requested.
Please help!
[for.kristoffer.gtf.gz](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/2477355/for.kristoffer.gtf.gz)
