### ISSUE TITLE
Error in analyzeSwitchConsequences

### ISSUE THREAD

**Issue by LetiziaMe** [kvittingseerup/IsoformSwitchAnalyzeR#170]
Hi, 
I used IsoformSwitchAnalyzeR to perform isoform differential analysis and alternative splicing. 
I was able to predict alternative splicing, but when I tried to perform consequence analysis I encountered this error:

aSwitchListAnalyzed <- analyzeSwitchConsequences(aSwitchListAnalyzed, consequencesToAnalyze = consequenceOfInterest, dIFcutoff = 0.1, showProgress=F)
**Step 1 of 4: Extracting genes with isoform switches...
Step 2 of 4: Analyzing 1586 pairwise isoforms comparisons...
  |                                                                                                             |   0%Error in dplyr::left_join(transcriptData, orfData, by = "isoform_id",  : 
  `...` must be empty.
✖ Problematic argument:
• all.x = TRUE
Errore: with piece 1: 
  isoformUpregulated isoformDownregulated comparison
1  ENST00000499762.2    ENST00000648157.1          1**

Could you please help me in solving?
Thanks a lot
Letizia

**Comment by kvittingseerup** [comment]
Could you check if the [previous issue](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/issues/165) solution works? :-)

**Comment by LetiziaMe** [comment]
Yes, sorry I missed the previous issue. 
Now it works!

Thank you!

**Comment by kvittingseerup** [comment]
Perfect :-)
