### ISSUE TITLE
Error in Step 5 of 10 from importRdata()

### ISSUE THREAD

**Issue by EntoErin** [kvittingseerup/IsoformSwitchAnalyzeR#171]
Good Afternoon, 

Than you again for helping me with my previous issue. I have now had success in step 2 of importing my GTF file but am now receiving the following error:

Step 1 of 10: Checking data...
Step 2 of 10: Obtaining annotation...
    importing GTF (this may take a while)...
    1951 ( 5.71%) isoforms were removed since they were not expressed in any samples.
Step 3 of 10: Fixing StringTie gene annoation problems...
    There were no need to rescue any annotation
    13498 genes_id were assigned their original gene_id instead of the StringTie gene_id.
        This was only done when it could be done unambiguous.
Step 4 of 10: Calculating expression estimates from count data...
    Skipped as user supplied expression via the "isoformRepExpression" argument...
Step 5 of 10: Testing for unwanted effects...
Error in 1:ncol(localSv) : argument of length 0

Please could you advise? I cannot see an empty column in my gtf file so I am unsure where this is coming from.

Thanks in advance, really appreciate how prompt and helpful your responses are!

Kind Regards,
Erin

**Comment by kvittingseerup** [comment]
Thanks for reaching out again - really appreciate it. 

I think I found and solved the problem. Try again with IsoformSwitchAnalyzeR >= 2.01.07. Remember to restart R after updating the R package.

Let me know if it works

**Comment by EntoErin** [comment]
@kvittingseerup 

That worked! Thank you so much. I really appreciate your prompt responses and help. 

Kind Regards,
Erin

**Comment by kvittingseerup** [comment]
Perfect - thanks again for repporting the problem :-)
