### ISSUE TITLE
isoformSwitchAnalysisPart1 (addORFfromGTF) Error in `dplyr::full_join()`:

### ISSUE THREAD

**Issue by valext34** [kvittingseerup/IsoformSwitchAnalyzeR#174]
Hello,
I have run into a problem in part 1 of the analysis, specifically addORFfromGTF. When i try to break down part1 into the component steps I run in to same problem. I had been actively running the complete pipeline on a series of experiments just fine and then this problem suddenly cropped up and I have no idea why or how to fix. I have R version 4.2.2 (2022-10-31) and RStudio Version 2022.12.0+353 (2022.12.0+353).

#isoformSwitchAnalysisPart1
```{r}
dirGTF <- "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz"
part1 <- isoformSwitchAnalysisPart1(switchAnalyzeRlist = aSwitchFilt, pathToGTF = dirGTF, pathToOutput =  dir, outputSequences = TRUE, prepareForWebServers = TRUE)
```
Step 1 of 3 : Detecting isoform switches...
Warning: some variables in design formula are characters, converting to factorsStep 2 of 3 : Adding and predicting open reading frames
trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz'
Content type 'unknown' length 28359457 bytes (27.0 MB)
==================================================
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
Backtrace:
 1. IsoformSwitchAnalyzeR::isoformSwitchAnalysisPart1(...)
 2. IsoformSwitchAnalyzeR::addORFfromGTF(...)
 5. IsoformSwitchAnalyzeR::importGTF(...)
 7. dplyr:::full_join.data.frame(...)
Backtrace:
Error in dplyr::full_join(orfInfo, unique(myIsoAnot[, "isoform_id", drop = FALSE]), :

✖ Problematic argument:
• all = TRUE 14.
stop(fallback)
13.
signal_abort(cnd, .file)
12.
action(c(message, x = bullet_header, set_names(bullets, "*"),
note), class = c(class, "rlib_error_dots"), ...)
11.
try_dots(action(c(message, x = bullet_header, set_names(bullets,
"*"), note), class = c(class, "rlib_error_dots"), ...))
10.
action_dots(error = error, action = action, message = "`...` must be empty.",
note = note, dots_i = TRUE, class = "rlib_error_dots_nonempty",
call = call, env = env)
9.
check_dots_empty(call = call)
8.
check_dots_empty0(...)
7.
full_join.data.frame(orfInfo, unique(myIsoAnot[, "isoform_id",
drop = FALSE]), by = "isoform_id", all = TRUE)
6.
dplyr::full_join(orfInfo, unique(myIsoAnot[, "isoform_id", drop = FALSE]),
by = "isoform_id", all = TRUE)
5.
importGTF(pathToGTF = pathToGTF, addAnnotatedORFs = TRUE, onlyConsiderFullORF = onlyConsiderFullORF,
removeNonConvensionalChr = FALSE, ignoreAfterBar = ignoreAfterBar,
ignoreAfterSpace = ignoreAfterSpace, ignoreAfterPeriod = ignoreAfterPeriod,
removeTECgenes = FALSE, PTCDistance = PTCDistance, removeFusionTranscripts = FALSE, ...
4.
withCallingHandlers(expr, warning = function(w) if (inherits(w,
classes)) tryInvokeRestart("muffleWarning"))
3.
suppressWarnings(gtfSwichList <- importGTF(pathToGTF = pathToGTF,
addAnnotatedORFs = TRUE, onlyConsiderFullORF = onlyConsiderFullORF,
removeNonConvensionalChr = FALSE, ignoreAfterBar = ignoreAfterBar,
ignoreAfterSpace = ignoreAfterSpace, ignoreAfterPeriod = ignoreAfterPeriod, ...
2.
addORFfromGTF(switchAnalyzeRlist = switchAnalyzeRlist, pathToGTF = pathToGTF,
quiet = TRUE)
1.
isoformSwitchAnalysisPart1(switchAnalyzeRlist = aSwitchFilt,
pathToGTF = dirGTF, pathToOutput = dir, outputSequences = TRUE,
prepareForWebServers = TRUE)

#addORFfromGTF
```{r}
dirGTF <- "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz"
mySwitchList <- addORFfromGTF(mySwitchList, pathToGTF = dirGTF)
```
Step 1 of 2: importing GTF (this may take a while)...
trying URL 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M27/gencode.vM27.annotation.gtf.gz'
Content type 'unknown' length 28359457 bytes (27.0 MB)
==================================================
Error in `dplyr::full_join()`:
! `...` must be empty.
✖ Problematic argument:
• all = TRUE
Backtrace:
 1. IsoformSwitchAnalyzeR::addORFfromGTF(mySwitchList, pathToGTF = dirGTF)
 4. IsoformSwitchAnalyzeR::importGTF(...)
 6. dplyr:::full_join.data.frame(...)
Backtrace:
Error in dplyr::full_join(orfInfo, unique(myIsoAnot[, "isoform_id", drop = FALSE]), :

✖ Problematic argument:
• all = TRUE
13.
stop(fallback)
12.
signal_abort(cnd, .file)
11.
action(c(message, x = bullet_header, set_names(bullets, "*"),
note), class = c(class, "rlib_error_dots"), ...)
10.
try_dots(action(c(message, x = bullet_header, set_names(bullets,
"*"), note), class = c(class, "rlib_error_dots"), ...))
9.
action_dots(error = error, action = action, message = "`...` must be empty.",
note = note, dots_i = TRUE, class = "rlib_error_dots_nonempty",
call = call, env = env)
8.
check_dots_empty(call = call)
7.
check_dots_empty0(...)
6.
full_join.data.frame(orfInfo, unique(myIsoAnot[, "isoform_id",
drop = FALSE]), by = "isoform_id", all = TRUE)
5.
dplyr::full_join(orfInfo, unique(myIsoAnot[, "isoform_id", drop = FALSE]),
by = "isoform_id", all = TRUE)
4.
importGTF(pathToGTF = pathToGTF, addAnnotatedORFs = TRUE, onlyConsiderFullORF = onlyConsiderFullORF,
removeNonConvensionalChr = FALSE, ignoreAfterBar = ignoreAfterBar,
ignoreAfterSpace = ignoreAfterSpace, ignoreAfterPeriod = ignoreAfterPeriod,
removeTECgenes = FALSE, PTCDistance = PTCDistance, removeFusionTranscripts = FALSE, ...
3.
withCallingHandlers(expr, warning = function(w) if (inherits(w,
classes)) tryInvokeRestart("muffleWarning"))
2.
suppressWarnings(gtfSwichList <- importGTF(pathToGTF = pathToGTF,
addAnnotatedORFs = TRUE, onlyConsiderFullORF = onlyConsiderFullORF,
removeNonConvensionalChr = FALSE, ignoreAfterBar = ignoreAfterBar,
ignoreAfterSpace = ignoreAfterSpace, ignoreAfterPeriod = ignoreAfterPeriod, ...
1.
addORFfromGTF(mySwitchList, pathToGTF = dirGTF)

Error in dplyr::full_join(orfInfo, unique(myIsoAnot[, "isoform_id", drop = FALSE]), :

✖ Problematic argument:
• all = TRUE

**Comment by emmafjones** [comment]
Hi Valext34,

I had a similar issue, but it looks like it has been resolved (https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/issues/168)

I was able to fix this by installing the most recent IsoformSwitchAnalyzeR version from GitHub:

`if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)`

Hope this helps,
Emma

**Comment by valext34** [comment]
Emma,
Thank you! I will check this out.

Victor

**Comment by valext34** [comment]
Hi Emma,
Yes this resolved my issue, thank you so much again.
Victor

**Comment by jesswhitts** [comment]
Is there any way around needing R 4.3 for this? For some reason the new version won't download without wanting R 4.3, but all my R libs are 4.2
