### ISSUE TITLE
Error in isoformSwitchTestSatuRn()

### ISSUE THREAD

**Issue by betulsb** [kvittingseerup/IsoformSwitchAnalyzeR#177]
Hello,
I am currently using IsoformSwitchAnalyzeR 2.1.9 from github. Since I am working with a large dataset, I tried to use isoformSwitchTestSatuRn() and got the following error message:

Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'which': 'list' object cannot be coerced to type 'double'
In addition: Warning messages:
1: glm.fit: algorithm did not converge
2: glm.fit: algorithm did not converge
3: glm.fit: algorithm did not converge
4: glm.fit: algorithm did not converge
5: Zero sample variances detected, have been offset away from zero 

My dataset contains 569 samples (404 Alzheimer's disease patients & 165 controls). My design matrix has the following columns: Sample ID, condition (AD/control), gender, age of death, and pmi. The last three are the confounding variables.

Could you please help me fixing this problem?

Many thanks in advance,
Betul

**Comment by kvittingseerup** [comment]
@jgilis do you have any idea about this problem? Also seem to be a problem for [another dataset ](https://groups.google.com/g/isoformswitchanalyzer/c/G27cY2izz_w) with much fewer samples

**Comment by jgilis** [comment]
Hi Kristoffer,

I won't have much time to look at it before March 22nd. The warning issues are not unexpected, this just indicates non-convergence for 5 out of all features, which are probably  very sparse features.

I have not yet encountered this specific error message myself. However, I did make some changes recently to resolve another, possibly similar error: https://github.com/statOmics/satuRn/issues/25.

@betulsb, could you try updating `satuRn` to version 1.7.3 and see if the issues persists?

**Comment by betulsb** [comment]
Hi Jeroen, 

I updated satuRn to version 1.7.3 and tried the isoformSwitchSatuRn() again. Unfortunately, it did not fix the problem. I am still getting the same error.

**Comment by kvittingseerup** [comment]
Did you restart R before trying isoformSwitchSatuRn() again? Sometimes R cannot update functions already loaded.

**Comment by betulsb** [comment]
Yes, I did restart R before trying again. However, I got the error anyway.

**Comment by kvittingseerup** [comment]
Another user was kind and sent their data, allowing me to debut this problem. 

I've just pushed a solution to GitHub, so if you install the newest version, it should work after restarting R. Please let me know if it does not :-)

@jgilis let me know if you disagree with the [implemented solution](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/commit/e398a234bc698df715587290a5ca0ebc51b12550#diff-db3b213697faf897fedbf94d2b9174727b52f44acb181d8cd392e077c107e468).
