### ISSUE TITLE
Issues with 'ifMultipleIdenticalAnnotation' and CPAT Question

### ISSUE THREAD

**Issue by drneavin** [kvittingseerup/IsoformSwitchAnalyzeR#18]
Hi Kristoffer,

I have two questions:

1. I am having issues with the function "switchPlotTopSwitches". I would like the output to plot each of the domains that have the same name with the same color. However, it is currently numbering the domains that have the same name and therefore assigning them a different color. I noticed that this can be controlled with the 'ifMultipleIdenticalAnnotation' option but even when I set that to "summarize" it continues to number the domain names and assign them different colors. Any ideas on how I can alter this to ensure that it is assigning the same color to the same domain name instead of numbering the domains?
Here is the chunk of code that I am using:
switchPlotTopSwitches(
  switchAnalyzeRlist = SwitchListAnalyzed,
  n = NA,
  IFcutoff = 0.05, 
  filterForConsequences = FALSE, 
  splitFunctionalConsequences = TRUE,
  pathToOutput = "DIR/IsoformSwitchFigures0.05IFcutoff/",
  additionalArguments = c(ifMultipleIdenticalAnnotation = "summarize")
  )

2. My second question has to do with CPAT which only has hg19 as genome option although my original annotation is on hg38. I am wondering if this will impact the annotation in IsoformSwitchAnalyzeR?

Thanks for your assistance!

Best,
Drew

**Comment by kvittingseerup** [comment]
Hi Dew

Thanks of reaching out.

With regards to question 1 I must admit I'm not sure what you mean - could you provide an example?

With regards to question 2 I have tested CPAT in Hg38 and the cutoff suggested in the documents is also based on Hg38 performance. You can see the test result in the supplementary results of [this article](http://mcr.aacrjournals.org/content/15/9/1206).

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Hi Dew

Ahh. They get a separate color to highlight that the number of domains in the isoforms are very different. In your case one isoform have 3 copies while another have 12.

There is unfortunately no way of modifying it the way you want currently - but I have added it to my to do list (it will however not happen in a time worth waiting for). If you really want to change this you will have to modify the colors in post-production (Illustrator, GIMP or any of the other vector graphics tools).

Cheers
Kristoffer
