### ISSUE TITLE
The more samples the less isoforms

### ISSUE THREAD

**Issue by seongguheo** [kvittingseerup/IsoformSwitchAnalyzeR#190]
Hi Authors,

The importSalmonData() function returns less number of isoforms as the number of samples increases.
At the end it return zero number of isoforms.
It saids that they were not expressed in any samples.

Input Data: Smart-seq2 scRNA-seq

aSwitchList <- importSalmonData(
    salmonFileDataFrame = salmonDf
)

22 samples, 156895 ( 66.73%) isoforms were removed since they were not expressed in any samples
286 samples, 235119 ( 100%) isoforms were removed since they were not expressed in any samples.

Best,
Luke

**Comment by kvittingseerup** [comment]
Was there a problem with IsoformSwitchAnalyzeR here? Would love to help you solve it if there were
