### ISSUE TITLE
Error installing latest github version

### ISSUE THREAD

**Issue by jesswhitts** [kvittingseerup/IsoformSwitchAnalyzeR#191]
Hello, 

I am trying to install the latest version via github, using R 4.3 which I have just downloaded. 

I get the following error:

   Error: package or namespace load failed for ‘DEXSeq’:
    objects ‘rowSums’, ‘colSums’, ‘rowMeans’, ‘colMeans’ are not exported by 'namespace:BiocGenerics'
   In addition: Warning message:
   replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘AnnotationDbi’ 
   Execution halted
   ERROR: lazy loading failed for package ‘IsoformSwitchAnalyzeR’
─  removing ‘/private/var/folders/32/8mghz1t14416wmmns0p1mgx80000gr/T/RtmpVMWHTi/Rinst601ac99d20/IsoformSwitchAnalyzeR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'IsoformSwitchAnalyzeR' from GitHub:
  ! System command 'R' failed

possible this is more of an issue with DEXSeq than this, but any suggestions?

Thanks,
jess

**Comment by kvittingseerup** [comment]
I think the problem is that you lack the BiocGenerics package?
