### ISSUE TITLE
InterProScan Pfam output has different file structure to original pfam_scan.pl

### ISSUE THREAD

**Issue by skudashev** [kvittingseerup/IsoformSwitchAnalyzeR#193]
Hello, 

Thank you for the great tool. 
As you might know, Pfam is now part of the InterProScan software, it would be great if the output would be compatible with your tool. The output TSV has the following structure https://interproscan-docs.readthedocs.io/en/latest/OutputFormats.html#example-output, so it no longer contains <clan>, <predicted_active_site_residues> and some other columns. The score and envelope start and end columns can probably be extracted from the JSON. 

This could be a great feature to consider. 

Thanks, 
Sofia

**Comment by kvittingseerup** [comment]
Thanks for reaching out. Do you mean to use EBI's interproscan instead of EBI's dedicated analysis pfam domains?

**Comment by Moinulhq** [comment]
> Thanks for reaching out. Do you mean to use EBI's interproscan instead of EBI's dedicated analysis pfam domains?
No matter which one I use, it shows error (The file(s) 'pathToPFAMresultFile' points to does not exist).

Is it possible to update the instruction? Interpro has TSV, JSON, XML, GFF and Sequence. On the other hand, the .txt file from the EBI site (https://www.ebi.ac.uk/Tools/hmmer/download/70511F0E-9DAB-11EE-9A26-59343CB63F3F.1/score?) also looks different from the example file. I am so confused.

**Comment by skudashev** [comment]
@vasikara17 Hi, you should be using the txt output from PFAM, not json. Also the structure of the file only works if you run pfam_scan.pl or pfam_scan.py, rather than interproscan. Hope this helps
