### ISSUE TITLE
issue with venn diagram scaling

### ISSUE THREAD

**Issue by Harshangda** [kvittingseerup/IsoformSwitchAnalyzeR#199]
I am using extractSwitchOverlap to create venn diagrams and using scaleVennIfPossible as TRUE. But my venn diagram is not scaled. Any idea why this is happening. I have 3 populations to compare.

**Comment by kvittingseerup** [comment]
Unfortunatly venn diagrams cannot always be scaled (mathematical impossible) so I don't believe it is a bug 🙂
