### ISSUE TITLE
use "extent", not "extend"

### ISSUE THREAD

**Issue by malcook** [kvittingseerup/IsoformSwitchAnalyzeR#2]
c.f.  [Common Errors in English Usage](https://brians.wsu.edu/2016/05/25/extend-extent//)

in section [Genome Wide Analysis](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#genome-wide-analysis)

I must study this paper and R package ... looks quite amazing and clearly described!

**Comment by kvittingseerup** [comment]
Thanks for pointing this out - it will be corrected in the next update.
