### ISSUE TITLE
Issue with the data?

### ISSUE THREAD

**Issue by HAFSAKHAN9** [kvittingseerup/IsoformSwitchAnalyzeR#201]
Step 1 of 7: Checking data...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function '%in%': dim(X) must have a positive length. 
I have small set of data, 4 samples. I have repeatedly checked the data, it is correct. what am I doing wrong?
switchAnalyzeRlist <- importRdata(
    isoformCountMatrix = "fpkm_matrix.txt",
    designMatrix = "design_matrix.txt",
    isoformExonAnnoation = "annotation.gtf"
)
[design_Matrix.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/11784788/design_Matrix.txt)
[fpkm_matrix.txt](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/files/11784792/fpkm_matrix.txt)

**Comment by emmafjones** [comment]
your column names for isoformCountMatrix need to exactly match the sample IDs, so I would try removing FPKM from the column names or adding the FPKM prefix to your sampleIDs in the design matrix.

**Comment by kvittingseerup** [comment]
You are giving strings as input instead of the actual data 🙂
