### ISSUE TITLE
UTR length

### ISSUE THREAD

**Issue by lananh-ngn** [kvittingseerup/IsoformSwitchAnalyzeR#204]
Hello,
Is there any way to extract UTR length when there is a shortening or a lengthening of the UTRs?
Thanks in advance.

**Comment by kvittingseerup** [comment]
Yep - `analyzeSwitchConsequences` can do that for you. Check the details in the description of the function 🙂

**Comment by lananh-ngn** [comment]
Hello, thank you for your fast reply. Sorry if I should have opened a new issue, but I kept looking for it, and I can only see that you can test for whether there are significant changes in UTR length, but not extraction of the UTR length.
Thanks in advance.

**Comment by kvittingseerup** [comment]
Ahh sorry - I was to quick and only say you were interested in them - not you wanted to extract them.

There is not a build-in function for extracting that, so you will have to do some work yourself.

You can find the switches in `exampleSwitchListAnalyzed$switchConsequence`.
You can find the ORF info in `exampleSwitchListAnalyzed$orfAnalysis`
And you can extract the transcript length from the `exon entry` by summing the width of all exons belonging to an isoform.

Hope this helps 🙂
