### ISSUE TITLE
Gene position for eqtl analysis

### ISSUE THREAD

**Issue by sumageb** [kvittingseerup/IsoformSwitchAnalyzeR#207]
Hi,
I am working on RNA-seq data from wheat. I used stringtie for assembly and followed the IsoformSwitchanalyzeR manual to fix the stringtie issue. My ultimate goal is to do eqtl analysis; for that, I need gene position. I could not find an option from where I can get the gene position along with the id.

I appreciate your help.

**Comment by chunxubioinfor** [comment]
Hi! I guess you have already dealt with this problem. But I just want to say that you could get gene position from the gtf file used when you import the stringtie file. I will close this issue and if you have further problems, please feel free to open a new one.
