### ISSUE TITLE
Gene expression values using IsoformSwitchAnalyzeR

### ISSUE THREAD

**Issue by Harshangda** [kvittingseerup/IsoformSwitchAnalyzeR#208]
The gene expression values I am getting from using IsformSwitchAnalyzeR (summing up isoform expression) are different from the values we get by doing normal differential gene expression (aligning reads to the gene using DESeq). Why is it so and which one is more accurate?

**Comment by chunxubioinfor** [comment]
Hi @Harshangda ! Compared with traditional gene quantification, transcript-level gene quantification, which IsoformSwitchAnalyzeR uses, has many advantages. One of them is the more accurate quantification algorithm (which includes correcting various sequence biases). For further information, please check the [official documentation.](https://bioconductor.org/packages/release/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use). Let me know if you need more help :)
