### ISSUE TITLE
StringTie readLength when using long reads

### ISSUE THREAD

**Issue by majdabdul** [kvittingseerup/IsoformSwitchAnalyzeR#209]
Hello,

Thank you for such a valuable tool with fantastic documentation.

I have matched short- and long-read cDNA-seq data. I used StringTie to assemble the transcriptome and quantify my samples. I used stringtie --mix, which allows me to leverage both datasets to get accurate sequence and structure of transcripts. When I tried to import the data into IsoformSwitchAnalyzeR, I got the following message:
```
> quant <- importIsoformExpression(
    parentDir = "merged_gtf"
)
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: StringTie
Error in importIsoformExpression(parentDir = "merged_gtf") : 
  When importing StringTie results the 'readLength' argument must be specified.
 This argument must be set to the number of base pairs sequenced (e.g. if the 
 quantified data is 75 bp paired ends 'readLength' should be set to 75.
```

I'm not sure what read length I'm supposed to use here, given I have a mixture of short and long reads. Should I just use the read length of my short-read dataset (150 bp)?

Thanks,
Majd

**Comment by chunxubioinfor** [comment]
Hi Majd, I noticed that Kristoffer has already replied to this issue through Google Groups. Please let me know If you have further questions. Otherwise, we would like to close this issue. Thank you :)

**Comment by majdabdul** [comment]
Hi @chunxubioinfor,
Yes, @kvittingseerup kindly responded. I just want to flag that, because of this, IsoformSwitchAnalyzeR is actually not compatible with cases where both short and long reads are used in assembling the transcriptome with StringTie (--mix option). The documentation makes it seem otherwise.

Best wishes,
Majd
