### ISSUE TITLE
Cannot import CPAT

### ISSUE THREAD

**Issue by ElvaWong** [kvittingseerup/IsoformSwitchAnalyzeR#210]
Hi, I have a problem importing external file from CPAT analysis. 
I want to import them to the SwitchList that underwent the isoformSwitchAnalysisPart1.

Here are some contents of my external files (all in TSV file format):
1. CPAT
ID	mRNA	ORF_strand	ORF_frame	ORF_start	ORF_end	ORF	Fickett	Hexamer	Coding_prob
ENSMUST00000162751.8_ORF_1	3030	+	3	219	1931	1713	1.0091	0.105940749047772	0.999913680566869
ENSMUST00000162751.8_ORF_2	3030	-	1	369	1	369	0.7696	0.0566954545960345	0.271282579045262
ENSMUST00000162751.8_ORF_3	3030	+	1	1813	2016	204	0.9462	0.00327711877859152	0.112167274498432
ENSMUST00000162751.8_ORF_4	3030	+	1	1309	1509	201	0.992	0.106113544331737	0.170114280417295

```
# Here are errors that I got:
# Importing CPAT file
SwitchList_analyzed.p1_externel <- analyzeCPAT(
+     switchAnalyzeRlist = SwitchList_analyzed.p1,
+     pathToCPATresultFile = "C:/Users/elvag/Desktop/Research_Practice/Linux/CPAT_output/CPAT_output.ORF_prob.tsv",
+     codingCutoff = 0.44,
+     removeNoncodinORFs = TRUE   # because ORF was predicted de novo
+ )
Error in analyzeCPAT(switchAnalyzeRlist = SwitchList_analyzed.p1, pathToCPATresultFile = "C:/Users/elvag/Desktop/Research_Practice/Linux/CPAT_output/CPAT_output.ORF_prob.tsv",  : 
  There seems to be a problem with the CPAT result file. Please check it is the rigth file and try again

```

**Comment by MustafaElshani** [comment]
Use CPAT2 instead of CPAT3
