### ISSUE TITLE
addORFfromGTF: cannot reconcile novel isoform IDs and ref gene annotations

### ISSUE THREAD

**Issue by srisarya** [kvittingseerup/IsoformSwitchAnalyzeR#214]
Hi, 

Firstly, thanks for this great tool! It's going to be very helpful for my project. 

I generated a novel transcriptome with Stringtie, and annotated it (i.e., 'named' each isoform) with GFFcompare, so there is a gene name (symbol) associated with each transcript. I then used this as a transcriptome for Salmon, so I could get expression information for novel isoforms, (similarly to option B1 [here](https://bioconductor.org/packages/release/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use). The quant files have "MSTRG.xyz' style rownames. **_No information after any bars_**

Except, now I'm having issues with `addORFfromGTF` because this takes in a reference transcriptome (I chose RefSeq) and the gene IDs in this are in symbol format, not in MSTRG format. It throws this error: 

`Error in addORFfromGTF(exampleSwitchListAnalyzed, paste0(basedir, "genomes_files/mm39.ncbiRefSeq.gtf")) : 
  No ORFs could be added to the switchAnalyzeRlist. Please ensure GTF file have CDS info (and that isoform ids match).
This could be a problem with ID matching you can fix by some combination of the three ignoreAfter*() arguments (look at your files)
Also note that ORF/CDS information cannot be found in the output from asemblers such as StringTie and Cufflinks.Instead use the official GTF that you downloaded from an official source such as Ensembl, Gencode, etc.`

I would assume that the tool would read the MSTRG ID in the salmonQuant$abundance, see that it is associated with a gene in the analysed switch list, and see what the reference ORF is from the ref GTF. BUT I feel like I've missed something basic and crucial about the package and can't figure it out from this [section](https://bioconductor.org/packages/release/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#analyzing-open-reading-frames) of the docs.

MANY thanks!

**Comment by chunxubioinfor** [comment]
@srisarya Hi Srishti! I'm glad that ISAR is helpful to your project :). As for your issue about ID mismatches, you can try to use `importRdata()` to fix the naming problem (instead of `GFFcompare` ), and then it should work. Please let me know if you have further issues.

**Comment by srisarya** [comment]
Hi @chunxubioinfor 
Thanks for your reply.
The issue was that I had no ORF data for novel transcriptomes as assembled with Stringtie (which are present in reference GTFs i.e., ncbi or ensembl, but not in custom/novel GTFs made with stringtie)
The solution I used was to extract ORFs manually using [TransDecoder](https://github.com/TransDecoder/TransDecoder/wiki#starting-from-a-genome-based-transcript-structure-gtf-file-eg-cufflinks-or-stringtie) and then to merge the gff3 with the CDS info with the novel transcriptome GTF in R itself using `GRanges`, and save that as a new GTF which I loaded in with `importRData`, like you say. I'm not sure if there's a more efficient way to go about this, but since stringtie-assembled custom GTFs lack CDS data, I wasn't sure what else to do. 
I'm not sure if this can be added to the vignette? It seems like I likely won't be the only one with this puzzle. 
As you said, GFFcompare was not hugely useful here though!
Thanks :)

**Comment by kvittingseerup** [comment]
Impressive workaround. For future refrences the workflow we have impelemnted is IsoformSwitchAnalyzeR is as follows:

1. Use `importRdata()` to fix the StringTie naming problem 
2. Use`addORFfromGTF()` to add ORF/CDS to the transcripts originating from the official source (Ensemble/Gencode etc)
3. Use `analyzeNovelIsoformORF()` to annotate the novel isoforms predicted by StringTie
