### ISSUE TITLE
How do I get exon inclusion level of alternative splicing events in each group

### ISSUE THREAD

**Issue by orange-3711** [kvittingseerup/IsoformSwitchAnalyzeR#215]
Hi , I'm sorry that I don't have a good enough understanding of alternative splicing events， how do I get the information in each group? Looking forward to your reply!

**Comment by kvittingseerup** [comment]
I don't think you can. IsoformSwitchAnalyzeR uses an isoform-based approach for the analysis since it allows for detailed biological insights (protein domains etc.). 

This means that there is no group-based information about alternative splicing.
