### ISSUE TITLE
File import order impacts IsoformSwitchAfterDEXSeq

### ISSUE THREAD

**Issue by LetiziaMe** [kvittingseerup/IsoformSwitchAnalyzeR#217]
Hi, 

following RSEM, we import our data according to the following code: 

_rsemQuant <- importIsoformExpression(parentDir = “pathtofile”)
myDesign <- data.frame(sampleID = colnames(rsemQuant$abundance)[-1], condition = gsub('_.*', '', colnames(rsemQuant$abundance)[-1]))
aSwitchList <- importRdata(isoformCountMatrix = rsemQuant$counts, isoformRepExpression = rsemQuant$abundance, 
  designMatrix = myDesign, comparisonsToMake = comparison,
  isoformExonAnnoation = "gencode.v44.primary_assembly.annotation.gtf",
  isoformNtFasta= "hsa.transcripts.fa",
  fixStringTieAnnotationProblem = FALSE,
  showProgress = FALSE, addAnnotatedORFs = FALSE)
aSwitchList_filtered<- preFilter(switchAnalyzeRlist = aSwitchList, geneExpressionCutoff = 1, isoformExpressionCutoff = 0, removeSingleIsoformGenes = TRUE)_

Our files are named A_1, A_2, A_3, B_1, B_2, B_3 obtaining the comparison A vs B and a number of differential isoforms when performing isoformSwitchTestDEXSeq(switchAnalyzeRlist = aSwitchList_filtered, reduceToSwitchingGenes=TRUE)

However, if we change the files alphabetical order (renaming A_1, A_2, A_3 in C_1, C_2, C_3), we DON'T get any differential isoforms. 

Is it possible that the alphabetical order affects the import in some way? If yes, how could we fix it? 

Thanks

**Comment by chunxubioinfor** [comment]
Hi @LetiziaMe, I don't think the alphabetical order would affect the results of differential isoforms. Do you change the comparison dataframe after renaming the files? If you rename` A_1, A_2, A_3` in `C_1, C_2, C_3`, now you should specify the comparison like: `comparisonsToMake = data.frame(condition_1 = 'C',condition_2 = 'B')`. I hope this will help you solve your issues :)

**Comment by chunxubioinfor** [comment]
I'm going to close this issue now, but you're welcome to open a new one at any time.😊
