### ISSUE TITLE
addORFfromGTF(): Error in in h(simpleError(msg, call)) 

### ISSUE THREAD

**Issue by Catv97** [kvittingseerup/IsoformSwitchAnalyzeR#219]
I have done guided transcript assembly using stringtie and quantified my transcripts using salmon and now I wanted to annotate ORFs. I will do this using addORFfromGTF and then using analyzeNovelIsoformORF, but I´m having troubles in the first step. When running addORFfromGTF I get this error: 
Step 1 of 2: importing GTF (this may take a while)...
Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': error in evaluating the argument 'x' in selecting a method for function 'sort': subscript contains invalid names

I´m using v2.1.3 of IsoformSwitchAnalyzeR

This is my code: 
### Add ORF back in from GTF
SwitchListIntermediary <- addORFfromGTF(
  switchAnalyzeRlist = switchAnalyzeRlist,
  pathToGTF = "/Users/catv/OneDrive - Danmarks Tekniske Universitet/PhD/data_analysis/RefSeq_SusScrofa11.1/genomic.gtf", #reference gtf file used for the guided assembly
  onlyConsiderFullORF =TRUE #set to TRUE only adds ORF stored in GTF file if it is annotated with both start and stop codon
)

I have also tried to import the same gtf file into R by using importGTF function:
aSwitchList <- importGTF(pathToGTF="/Users/catv/OneDrive - Danmarks Tekniske Universitet/PhD/data_analysis/RefSeq_SusScrofa11.1/genomic.gtf") and it seems to work fine.

So I´m not sure what the problem is with addORFfromGTF function.

Any ideas of what is the problem?

Cheers,
Catarina

**Comment by chunxubioinfor** [comment]
Hi Catarina, this issue is fixed in the latest github version. So I just closed this issue. Feel free to reach out if you have further issues.😊
