### ISSUE TITLE
Error of isoformSwitchTestDEXSeq() 

### ISSUE THREAD

**Issue by greencream** [kvittingseerup/IsoformSwitchAnalyzeR#22]
Hi Kristoffer, 
I use the SALMON got the quants files, it seems isoform_id has redundant name, 
such as: ENST00000456328.2|ENSG00000223972.5|OTTHUMG00000000961.2|OTTHUMT00000362751.1|DDX11L1-202|DDX11L1|1657|processed_transcript|

I kept the ENST name using : 
salmonQuant_GENCODE_total$abundance$isoform_id <- str_remove_all(salmonQuant_GENCODE_total$abundance$isoform_id, "[|].*")
salmonQuant_GENCODE_total$counts$isoform_id <- str_remove_all(salmonQuant_GENCODE_total$counts$isoform_id, "[|].*")
salmonQuant_GENCODE_total$length$isoform_id <- str_remove_all(salmonQuant_GENCODE_total$length$isoform_id, "[|].*")

importRdata() works fine, but isoformSwitchTestDEXSeq() showed error:
Error in DEXSeqDataSet(countData = round(localCount[, which(!colnames(localCount) %in% : class(sampleData) %in% c("data.frame") are not all TRUE

Hoping you could help to fix it.

Thanks

**Comment by kvittingseerup** [comment]
If you use IsoformSwitchAnalyzeR::importIsoformExpression() or tximport::tximport() they have a "ignoreAfterBar" argument which should fix the naming problem.

With regards to the isoformSwitchTestDEXSeq() could you send me:
1) The command you use to run it
2) The version of IsoformSwitchAnalyzeR you are using. Can easily be obtained by typing the following in your R terminal.

    packageVersion('IsoformSwitchAnalyzeR')

Cheers
Kristoffer

**Comment by greencream** [comment]
Thank you, Kristoffer.

My workmates help take a look the code, is because myDesign was dataMatrix, not the dataframe, and lead to this error.

Best

Kevin
