### ISSUE TITLE
Import after STAR Alignment

### ISSUE THREAD

**Issue by bassanio** [kvittingseerup/IsoformSwitchAnalyzeR#224]
Dear Team,

I have two groups of samples which have went through the following pipeline

```
RAW FASTQ > Trimmed Fastq >STAR (Genome) >Htseq-Count & Cufflinks
```

I was going through the Viggenetts and I am unable to Follow how to move forward

1)  **Under Isoform/transcript quantification Option A**:

 It's says to use quantification from Salmon/kalisto. In STAR aligner I use the genome sequence to align against but according to salmon and Kalisto it requires transcriptome fasta(cDNA) as reference. So how move forward? Is it as discussed in the [salmon](https://salmon.readthedocs.io/en/latest/salmon.html#quantifying-in-alignment-based-mode) where we redo the alignment to cDNA?

2) **Under Isoform/transcript quantification Option B**:

I felt this is the most suitable method from the pipeline similar to the existing method I used. The confusion for me is on the step 4 . After running the Cuffmerge for creating the  merged gtf for including novel transcript should I need to run **Cuffdiff** ? or Is it that we use the gtf file from cuffmerge and use salmon downstream? If so the above issue of different reference exist here also (genome fasta and cDNA fasta) secondly for using the salmon with the new gtf file which fasta I need to use

**Comment by chunxubioinfor** [comment]
Hi @bassanio, I agree that option B is more suitable and reliable. After running the cuffmerge you can just use salmon to re-quantify. You can use tools such as [gffread](http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread_ex), along with the GTF file from step 3, to create the transcript fasta file needed for quantifying with Salmon/Kallisto. I hope this can be of help to you. 😊🤞
