### ISSUE TITLE
Question on importIsoformExpression()

### ISSUE THREAD

**Issue by sparthib** [kvittingseerup/IsoformSwitchAnalyzeR#225]
Hi there, I am using `importIsoformExpression()` to import expression from salmon. I am unclear on the `calculateCountsFromAbundance` argument. When it's set to true, does that mean that counts are recalculated based on `scaledTPM` value from Salmon. However, the abundance column in the final product object uses edgeR to normalize it to TMM. Any clarity in the order of operations is would be appreciated! Thanks!

**Comment by chunxubioinfor** [comment]
Hi Sowmya, [here](https://rdrr.io/github/kvittingseerup/IsoformSwitchAnalyzeR/man/importIsoformExpression.html) are more details about `importIsoformExpression()`. I think this can solve your problems. 😊 Let me know if you need further help.
