### ISSUE TITLE
comparisonsToMake wiith 4four conditions

### ISSUE THREAD

**Issue by rvermamsm** [kvittingseerup/IsoformSwitchAnalyzeR#234]
Hello

I have 4 conditions in my data. Can I compare them like this:

comparisons_to_make <- as.data.frame(
     rbind(
         c("Disc_NO", "Base_NO"),
         c("4-6h_NO", "Base_NO"),
         c("Disc_YES", "Base_YES"),
         c("4-6h_YES", "Base_YES")
     ),
     stringsAsFactors = FALSE  # Ensure that strings are not converted to factors
 )

> # Rename columns to match the expected format
colnames(comparisons_to_make) <- c("condition_1", "condition_2")
> # Import data with additional comparisons
aSwitchList_str <- importRdata(
   isoformCountMatrix = stringQuant$counts,
   isoformRepExpression = stringQuant$abundance,
   designMatrix = myDesign,
   isoformExonAnnoation = gtf,
   isoformNtFasta = NULL,
   showProgress = FALSE,
   ignoreAfterBar = TRUE,
   ignoreAfterSpace = TRUE,
   addAnnotatedORFs = TRUE,
   ignoreAfterPeriod = FALSE,
   comparisonsToMake = comparisons_to_make
 )

Is this the correct way to compare all this condition at a time?

**Comment by chunxubioinfor** [comment]
Hi, I think it's the right way to achieve the four comparisons. But I recommend you put baseline as _condition 1_ and case as _condition 2_ (if this Base means baseline), which will enable the following visualisation to be more intuitive.

**Comment by rvermamsm** [comment]
Thank you for your quick response.
