### ISSUE TITLE
Continous condition in design matrix?

### ISSUE THREAD

**Issue by amkilpatrick** [kvittingseerup/IsoformSwitchAnalyzeR#236]
Hello, we are interested in how isoform usage might change based on clinical measurements in a cohort of human patients. We have gene-level analysis from another R package providing a continuous variable in the design matrix, but from the documentation it seems that this is not an option in this package? Must the 'condition' column in the design matrix always be a string? Or is there a better way to answer this question?
Thanks!

**Comment by chunxubioinfor** [comment]
Hi! It's not possible to use the continuous condition as all The statistical analysis are based on pairwise comparisons so all the conditions should be discrete (with replicates). But I think maybe you could convert the continuous variables to categorical ones.

**Comment by amkilpatrick** [comment]
Thanks for the confirmation, we can try that for sure.
Out of interest, do you know any similar packages that would allow to specify based on a continuous variable?

**Comment by chunxubioinfor** [comment]
Sorry, I'm afraid I don't know any similar packages. I'm going to close this issue now. If you have further issues, plz feel free to open a new one.
