### ISSUE TITLE
importing Kallisto counts to IsoformSwitchAnalyzer

### ISSUE THREAD

**Issue by panconchoclo** [kvittingseerup/IsoformSwitchAnalyzeR#24]
Hi Kristoffer,

I am trying to import kallisto counts to IsoformSwitchAnalyzer but is not working. I am doing that in this way:

### Import Kallisto quantifications
```
kallistoQuant <- importIsoformExpression(
parentDir = system.file("/my_path/kallisto/", package="IsoformSwitchAnalyzeR")
)
```
inside /my_path/kallisto/ I have directories with samples names (sequenced libraries) and inside of each one there is an abundance.tsv file with the expected data. However the importIsoformExpression function claim with the follow warning.

```
Step 1 of 3: Identifying which algorithm was used...
Error in dirList[sapply(dirList, FUN = function(aDir) { : 
  invalid subscript type 'list'
```
So already on Step 1 there is a problem.

How abundance files looks?

head(abundance.tsv)

target_id       length  eff_length      est_counts      tpm
AT1G51370.2     1118    927.449 0       0
AT1G50920.1     2394    2203.45 1587    66.372
AT1G36960.1     546     355.48  0       0
AT1G44020.1     2314    2123.45 0       0 ....etc

As an alternative solution I am thinking load the counts directly to imporRdata. However; What should I load as a replacement of kallisto$abundance?  can I use TPM scaled by length values?

The object "myDesign" looks Ok. 

Thank you very much for any clue or suggestion.

**Comment by kvittingseerup** [comment]
I think the problem is that you should not use system.file() command:

```
### Please note
# The way of importing files in the following example with
# "system.file('pathToFile', package="IsoformSwitchAnalyzeR") is
# specialised way of accessing the example data in the IsoformSwitchAnalyzeR package
# and not something you need to do - just supply the string e.g.
# "/mySalmonQuantifications/" pointing to the parent directory (where 
# each sample is a separate sub-directory) to the function.
```

**Comment by panconchoclo** [comment]
Thank you very much for your answer. I understand what you mean. 
My apologies. I think that the google group is a better place to ask than here. I do not give up yet on how to enter the data by importRdata. I think is a data struture issue. I have an object with the counts and another one with the TPM values.
Running the example data I realized that the class of the inputs objects for  isoformCountMatrix and isoformRepExpression must be "list".  Am I right?

```
### Create switchAnalyzeRlist
aSwitchList <- importRdata(
  isoformCountMatrix   = data_counts_as_list,
  isoformRepExpression = data_tpm_as_list,
  designMatrix         = myDesign,
  isoformExonAnnoation = system.file("file.gtf.gz", package="IsoformSwitchAnalyzeR")
)
```

However 

```
Step 1 of 6: Checking data...
Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables
```

**Comment by umasstr** [comment]
@kvittingseerup thanks for clearing this up so quickly! I was also confused by the note. You may consider adding a line to your comments showing the standard input, parentDir = 'pathToFile'

Thanks again for your support.
