### ISSUE TITLE
Version Discrepancy (GitHub vs. Bioconductor)

### ISSUE THREAD

**Issue by NanoCoreUSA** [kvittingseerup/IsoformSwitchAnalyzeR#241]
Hi,

I ran into issue #219 and reinstalled the package from GitHub as suggested, which seems to have fixed the problem. However, I just wanted to confirm I have the most up to date version as it's currently listed as '2.1.3' whereas the most recent one from Bioconductor is '2.5.0'. Is this just because the version numbers on GitHub haven't been updated in the description file? I assume installing from GitHub directly would be the most up to date but just wanted to check.

Thanks for the great tool!

**Comment by chunxubioinfor** [comment]
Hi! Yes, the github version is the up-to-date one so I think we just forgot to update the description file. Thank you for pointing out the problem! Hope your analysis goes well with IsoformSwitchAnalyzeR :)
