### ISSUE TITLE
the output of importRdata is different?

### ISSUE THREAD

**Issue by huawen-poppy** [kvittingseerup/IsoformSwitchAnalyzeR#248]
Hi! Thank you for your very nice tool!!

I am using below code to create switchAnalyzeRlist,
```
aSwitchList <- importRdata(
  isoformCountMatrix   = count,
  isoformRepExpression = tpm_data,
  designMatrix         = myDesign,
  isoformExonAnnoation = "./input_data/OUT.transcript_models.gtf",
  isoformNtFasta       = "./input_data/OUT.transcript_models.fa",
  )
```
at the first time the output looks like below:

`
Step 1 of 10: Checking data...
Please note that some condition names were changed due to names not suited for modeling in R.
Step 2 of 10: Obtaining annotation...
    importing GTF (this may take a while)...
Step 3 of 10: Fixing StringTie gene annoation problems...
    There were no need to rescue any annotation
Step 4 of 10: Calculating expression estimates from count data...
    Skipped as user supplied expression via the "isoformRepExpression" argument...
Step 5 of 10: Testing for unwanted effects...
    No unwanted effects added
Step 6 of 10: Batch correcting expression estimates...
Step 7 of 10: Extracting data from each condition...
  |=============================================================================================================================================| 100%
Step 8 of 10: Making comparisons...
  |=============================================================================================================================================| 100%
Step 9 of 10: Making switchAnalyzeRlist object...
Step 10 of 10: Guestimating differential usage...
    The GUESSTIMATED number of genes with differential isoform usage are:
   comparison estimated_genes_with_dtu
1 apo vs holo                108 - 181
Done
`

but when I run the same exact code, the output is different. is this normal?
`Step 1 of 10: Checking data...
Please note that some condition names were changed due to names not suited for modeling in R.
Step 2 of 10: Obtaining annotation...
    importing GTF (this may take a while)...
Step 3 of 10: Fixing StringTie gene annoation problems...
    There were no need to rescue any annotation
Step 4 of 10: Calculating expression estimates from count data...
    Skipped as user supplied expression via the "isoformRepExpression" argument...
Step 5 of 10: Testing for unwanted effects...
    No unwanted effects added
Step 6 of 10: Batch correcting expression estimates...
Step 7 of 10: Extracting data from each condition...
  |=============================================================================================================================================| 100%
Step 8 of 10: Making comparisons...
  |=============================================================================================================================================| 100%
Step 9 of 10: Making switchAnalyzeRlist object...
Step 10 of 10: Guestimating differential usage...
    The GUESSTIMATED number of genes with differential isoform usage are:
   comparison estimated_genes_with_dtu
1 apo vs holo                 76 - 128
Done`

**Comment by chunxubioinfor** [comment]
Hi @huawen-poppy, the guesstimated provided is just a guess informed by an estimate. This is provided for getting a quick idea of what to expect. The final number could be obtained after running isoformSwitchTestDEXSeq(), isoformSwitchTestSatuRn (), or other tools you like. I hope this is helpful to you. 
Please feel free to open a new issue if you need further help. ☺️
