### ISSUE TITLE
example of dataset to use IsoformSwitchAnalyzeR 

### ISSUE THREAD

**Issue by jchelbling** [kvittingseerup/IsoformSwitchAnalyzeR#249]
I m trying o set up a pipeline analysis for my own data but I met some errors with my dataset.
Do you have an example of dataset which I can use to decorticate the process of analysis using ISAR.
Thanks a lot for your reply
Best
-Jc

**Comment by chunxubioinfor** [comment]
Hi @jchelbling, We've included the example data in our project. You could load them via like data("exampleSwitchList"). For more information, please check the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html).

**Comment by jchelbling** [comment]
Thanks,
-Jc
