### ISSUE TITLE
stacked bar for Isoform usage

### ISSUE THREAD

**Issue by Indigofera** [kvittingseerup/IsoformSwitchAnalyzeR#25]
I want to use a stacked bar plot for isoform usage instead of bar plot. Is there a chance to change bar plot with stacked bar plot in switchPlotTranscript?

**Comment by Indigofera** [comment]
No need

**Comment by kvittingseerup** [comment]
Unfortunately that is not supported so you will have to make it yourself.

**Comment by Indigofera** [comment]
Thanks.
