### ISSUE TITLE
What is the criteria for plotting a particular isoform? The results don't meet the threshold you set

### ISSUE THREAD

**Issue by dudududu12138** [kvittingseerup/IsoformSwitchAnalyzeR#256]
Hi, I just used your pipeline and I got the final switch consequence result. Then I want to plot the result of one gene using `switchPlot`. My codes are like this: `switchPlot(exampleSwitchListAnalyzedSubset, gene = 'XLOC_055866')`. And I got the result figure like below:
![1728394336176](https://github.com/user-attachments/assets/1d580b57-c106-464a-b2ab-307514b3832c)

- But I don't know why your function choose this 8 isoforms to plot. There are 17 isoforms in this gene while only 8 of them are plotted. And not all the 8 isoforms meet the cutoffs you set **_(alpha<0.05 & abs(dIF)>0.1 & IF>0.05_**). 

- **So I am confused what is the criteria for plotting a particular isoform?**

- This is the `isoformFeature` table from my final result : [gene.features.txt](https://github.com/user-attachments/files/17294130/gene.features.txt)

**Comment by chunxubioinfor** [comment]
Hi, I just checked the source code of the switchPlot() function, and by default, the isoforms whose IF > 0.05 (at least one condition) will be plotted. I also downloaded your gene feature file and confirmed that these eight isoforms are the only ones to meet the criteria. Alpha and dIF are applied to decide significance. Hope this can solve your issue. :)
