### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by Ollipolli1909** [kvittingseerup/IsoformSwitchAnalyzeR#26]
example_isoform_nt.fasta.gz is not included in the latest release

**Comment by kvittingseerup** [comment]
Thanks for reaching out.  Are you sure - it is supposed to be in: ```inst/extdata```

What IsoformSwitchAnalyzeR version are you running?

Cheers
Kristoffer

**Comment by Ollipolli1909** [comment]
Hi Kristoffer,
I just installed yesterday, so assume I use the latest version. Your walkthrough indicates it should be in extdata together with the example.gtf.gz. The latter is. Also, if I run it with isoformNtFasta i get an unused argument error when supplying another fasta
Cheers,
Oliver

**Comment by Ollipolli1909** [comment]
sorry, my bad. I somehow followed the dev workflow, not the release one. Seems you have removed isoformNtFasta from the release ?

**Comment by kvittingseerup** [comment]
Nope - the isoformNtFasta currently only exists in the devel version as it is an extention made after the last stable release. I do however highly recommend you use the devel version as many important updates have been made since last stable release.

**Comment by Ollipolli1909** [comment]
The devel version is only for R version 3.6 though ? I am not keen on installing it before release.

Cheers,
Oliver

**Comment by kvittingseerup** [comment]
I made sure there is a workaround - simply install it from the github where I only require R 3.5. Can be done with:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```
