### ISSUE TITLE
PfamScan 

### ISSUE THREAD

**Issue by wong15w** [kvittingseerup/IsoformSwitchAnalyzeR#27]
After running pfamScan.pl, I obtained a result file, which appears similar to the output found in the sample pfam_results.txt file. The only place where I could discern a difference was that some of the hmm_acc fields in my file were left blank, which may be causing the file to fail the second test for determining if the file is a pfam result file.  I have pasted an instance of that below. 

ENST00000219797.4     55    110     55    111 PF11717.7   Tudor-knot        Family     1    54    55     76.2   1.3e-21   1 CL0049   
ENST00000219797.4    176    230    176    230             zf-MYST                      1    55     0     81.0   3.4e-23   1 No_clan  
ENST00000219797.4    235    412    235    412 PF01853.17  MOZ_SAS           Family     1   179   179    291.3   2.3e-87   1 CL0257   predicted_active_site

**Comment by kvittingseerup** [comment]
Thanks for reaching out! Have not seen that before.

Which annotation database and version are you using?

**Comment by wong15w** [comment]
I am using the annotations for Gencode release 19.

**Comment by kvittingseerup** [comment]
Could  you try sending me the subset of the Pfam result text-file with the ENST00000219797.4 results?

**Comment by kvittingseerup** [comment]
Closed due to no response from OP
