### ISSUE TITLE
SwitchAnalzyer fails

### ISSUE THREAD

**Issue by ebioman** [kvittingseerup/IsoformSwitchAnalyzeR#28]
Hello
I am following your recommended steps analyzing data from Kallisto and Ensembl annotation for mouse.
I can go trough the preparation steps but the final isoformSwitch analysis step fails for both the DEX and DRIM with the same error

Warning messages:
1: no function found corresponding to methods exports from 'GenomicAlignments' for: 'concatenateObjects'
2: replacing previous import 'DEXSeq::plotMA' by 'limma::plotMA' when loading 'IsoformSwitchAnalyzeR'
Please consider using isoformSwitchTestDEXSeq() instead.
The DEXSeq implementation have been shown to superiour to DRIMSeq
on all paramters (except runtime for large number of samples)
by Love et al 2018 (F1000) - results we can replicate.

<pre><code>
Step 1 of 6: Creating DM data object...
Step 2 of 6: Filtering DM data object...
Step 3 of 6: Estimating precision paramter (this may take a while)...
Step 4 of 6: Fitting linear models (this may take a while)...
Step 5 of 6: Testing pairwise comparison(s)...
Step 6 of 6: Preparing output...
Result added switchAnalyzeRlist
An isoform switch analysis was performed for 5478 gene comparisons (99.8%).
Error in switchAnalyzeRlist[[localAnalysis]][which(switchAnalyzeRlist[[localAnalysis]]$isoform_id %in%  :
  incorrect number of dimensions
Calls: isoformSwitchTestDRIMSeq -> subsetSwitchAnalyzeRlist
</code></pre>

**Comment by kvittingseerup** [comment]
Thanks for reaching out!

Which version of IsoformSwitchAnalyzeR are you using?

**Comment by ebioman** [comment]
Hello thanks for the swift reply,
I had first the one on Bioconductur but installed last week the github based on directly instead.
I do the the options for stop after point, space and so on.

I conducted a kallisto based analysis on Ensembl mouse 95 cDNA and tried first to run your tool using the Ensembl corresponding .chr.gff annotation file. This resulted though in a correlation value ~0.95 and 2000 missing transcripts preventing the analysis to start in the first place.

I then took from Ensembl the annotation containing as well patches which contains all transcripts which I analyzed and I can prepare till the above mentioned error. I had though to introduce the "stop after point" option in order to capture all transcripts as a very small sub-set from Ensembl did not have a versioning.

**Comment by kvittingseerup** [comment]
Thanks for getting back to me so quick and verifying your version. I must admit I have not seen this error before and I cannot reproduce it with my usual datasets. Would you be willing to send/email me the switchAnalyzeRlist you give as input to isoformSwitchTestDEXSeq() so I can debug it? I would naturally treat your data confidentially and delete it as soon as the problem was solved :-)

**Comment by ebioman** [comment]
Hi
I am afraid I cant reproduce the error anymore - on the other hand I am happy since the problem disappeared. I believe I might have had an Rdata project saved with objects created in an older version of SwitchAnalyzer which I then continued to analyze with the updated version.
