### ISSUE TITLE
Getting all p values for all isoforms and genes

### ISSUE THREAD

**Issue by crj32** [kvittingseerup/IsoformSwitchAnalyzeR#29]
Hi

My supervisor wants to test a specific hypothesis with the tool that means just looking at the nominal p value for one specific gene he is interested in. The gene does not make FDR cut off, but he wants to look at it anyway. I couldn't find a way to do this with iso. Is there a way? For example, running this command, gave me only a few hundred isoforms and a bunch of rows with NA in, we need everything... Thanks.

tophits <- extractTopSwitches(exampleSwitchListAnalyzedSubset,alpha=1)

Best,

Chris

**Comment by kvittingseerup** [comment]
Hi Chris

The "problem" is that the default workflow is to reduce the switchAnalyzeRlist to only containing significant genes in the testing stage (in the ```isoformSwitchTestDEXSeq()``` or ```isoformSwitchAnalysisPart1()``` functions) whereby you cannot extract them. You should re-run with ```isoformSwitchTestDEXSeq()``` and set ```reduceToSwitchingGenes = FALSE```. Then your gene should still be in there.

And if you want the p-value you should look at the isoformSwitchAnalysis entry of the switchList:

```exampleSwitchListIntermediary$isoformSwitchAnalysis```
