### ISSUE TITLE
Covariates in isoformSwitchTest

### ISSUE THREAD

**Issue by dylanmr** [kvittingseerup/IsoformSwitchAnalyzeR#3]
Is there any way to incorporate covariates to account for changing cell populations and/or paired samples in the isoformSwitchTest command?

**Comment by kvittingseerup** [comment]
Unfortunatly co-variates are not possible when using the isoformSwitchTest() but it is when using the isoformSwitchTestDRIMSeq() function which we also recommend for most usecases (as discussed in the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#testing-isoform-switches-via-drimseq))
