### ISSUE TITLE
file reading issue on isoformswitchanalyzer

### ISSUE THREAD

**Issue by Saddamhus** [kvittingseerup/IsoformSwitchAnalyzeR#31]
I am trying to figure out how to use IsoformSwitchAnalyzeR on Salmon quantification. I'm really stuck at the very beginning. I have not been able to import the data. Below is the code I am using-

getwd()
[1] "/Users/saddamhusain/Desktop/salmon_isoswitch"

salmonQuant <- importIsoformExpression(
parentDir = system.file("salmonQuant", package="IsoformSwitchAnalyzeR")

)

Step 1 of 3: Identifying which algorithm was used...

Error in dirList[sapply(dirList, FUN = function(aDir) { :

invalid subscript type 'list'

salmon_isoswitch is a directory that contains salmonQuant subdirectory that in tern contains four independent subdirectories for each sample.

With this code-

salmonQuant <- importIsoformExpression("salmonQuant")
Step 1 of 3: Identifying which algorithm was used...

Error in importIsoformExpression("salmonQuant") : No directories of interest were found

Even though .txt files of count data are there.

Any help will be appreciated.

**Comment by kvittingseerup** [comment]
The problem is that the way of importing files in the vignette/example with "system.file('pathToFile', package="IsoformSwitchAnalyzeR") is specialised way of accessing the example data in the IsoformSwitchAnalyzeR package and not something you need to do - just supply the string e.g. "/mySalmonQuantifications/" pointing to the parent directory (where  each sample is a separate sub-directory) to the function. 

Cheers
Kristoffer

**Comment by Saddamhus** [comment]
Thank you Kristoffer for the response. I am still seeing the error.

> getwd()

[1] "/Users/saddamhusain/Desktop/salmon_isoswitch"

> salquant <- importIsoformExpression("/squant/")

Step 1 of 3: Identifying which algorithm was used...

Error in dirList[sapply(dirList, FUN = function(aDir) { : 

  invalid subscript type 'list'

squant folder contains four different folder with one file in each.

**Comment by kvittingseerup** [comment]
That looks strange. Could you try restarting R and see if the error persists?

Cheers
Kristoffer

**Comment by Saddamhus** [comment]
I have restarted and run but it still showed error.

> library(IsoformSwitchAnalyzeR)

> getwd()

[1] "/Users/saddamhusain/Desktop/salmon_isoswitch"

> salquant <- importIsoformExpression("/squant/")

Step 1 of 3: Identifying which algorithm was used...

Error in dirList[sapply(dirList, FUN = function(aDir) { : 

  invalid subscript type 'list'




my workdir is salmon_isoswitch and squant is a folder within it which contains four different folders of quant.txt file.

**Comment by kvittingseerup** [comment]
Ahh. Sorry I was to fast. The problem is the first "/". This causes your computer to look in the root of all your directores - not the current one. Try removing it is you use:
```salquant <- importIsoformExpression("squant/")```

**Comment by Saddamhus** [comment]
Now it shows other error

> salquant <- importIsoformExpression("squant/")

Step 1 of 3: Identifying which algorithm was used...

Error in importIsoformExpression("squant/") :
 
  No directories of interest were found


My salmon quant files end with .txt, could it be a problem?

**Comment by kvittingseerup** [comment]
Yes. The salmon files should not be rename (that is the main way importIsoformExpression() can distinguish input from different quantification tools.

**Comment by Saddamhus** [comment]
Ok. Since I have run salmon on galaxy platform (salmon v- 0.13.1) it generated quantification and gene quantification file in tabular format (instead of .sf) therefore I have to change them too .txt files so that I could do differential gene expression analysis (I have done it successfully with quantification
files).  I am using same files for the isoform analysis and not gene quantification files.

**Comment by kvittingseerup** [comment]
To use importIsoformExpression() the quantification files in the sub-directories must be have the post-fix "quant.sf". So either you need to re-name them (e.g. to quant.sf) or alternative you can import the count and abundance matrix yourself using[ tximport] (http://bioconductor.org/packages/release/bioc/html/tximport.html) and then just continue to the imporRdata() step.

**Comment by bellenger-l** [comment]
Hello, 

I think it would be useful for the users to specify this in the manual... I encounter a problem to import my data.
I had to look into your [code](https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/blob/master/R/import_data.R#L1805) to see that if you have Salmon dataset, filenames should be "quant.sf" (your example) but if you have RSEM abundances (my case) files should be named "isoforms.results". 
In my opinion, it is very important to include this table in your doc to make your package even more user-friendly.

Best regards, 
Lea

**Comment by kvittingseerup** [comment]
Hi Lea

Thanks for reaching out. I fully agree - which is why I have extended the documentation to highlight this as well as implemented the functionality of supplying a vector directly pointing to the files of interest. I expect the update will be online shortly.

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
The update containing this improvement was just released via Bioconductor as v 1.5.7. :-)

**Comment by kvittingseerup** [comment]
If you downloaded IsoformSwitchAnalyzeR 1.5.7 you need to upgrade to 1.5.8 (available both on the github and Bioconductor) as there was a but that caused downstream problems in 1.5.7. Analysis done with 1.5.7 would need to be redone from the consequence prediction step (since that is where the problem was). Sorry for the inconvenience.

Cheers
Kristoffer

**Comment by Saddamhus** [comment]
Thank you for the updates.

**Comment by sk1350** [comment]
Hello I am getting an error while importing quant.sf files: 
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: Salmon
    Found 9 quantification file(s) of interest
Error in file.exists(localFiles) : invalid 'file' argument
Would appreciate any help

**Comment by kvittingseerup** [comment]
Hi SK1350.

If you post the code you are using along with the version of IsoformSwitchAnalyzeR I'll be able to help you out. You can check you package version with this R command:
```
packageVersion("IsoformSwitchAnalyzeR")
```
If your version is less than 1.8.0 you will need to update first and try again. You can read about how to update [here](https://bioconductor.org/packages/release/bioc/html/IsoformSwitchAnalyzeR.html).

**Comment by sk1350** [comment]
> salmonQuant <- importIsoformExpression(parentDir = ".", pattern="_transcripts_quant")
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: Salmon
    Found 6 quantification file(s) of interest
Error in file.exists(localFiles) : invalid 'file' argument
> packageVersion("IsoformSwitchAnalyzeR")
[1] ‘1.8.0’

**Comment by kvittingseerup** [comment]
That looks strange. Could you write the path from "." to one of the quantification files?
