### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by crj32** [kvittingseerup/IsoformSwitchAnalyzeR#35]
Apologies for another post, but I just want to check if this code is correct.

This code to get the differential expression results for this contrast

exampleSwitchListAnalyzedSubset <- subsetSwitchAnalyzeRlist(
  exampleSwitchListAnalyzed, 
  subset = exampleSwitchListAnalyzed$isoformFeatures$condition_1 == 'Fibroid' & exampleSwitchListAnalyzed$isoformFeatures$condition_2 == 'Lymphoid'
)

This code to get all p values for all genes FOR this contrast above only, note I am adding additional information here manually because we lose it not using extractTopSwitches, which is non-ideal. Not sure about the extractTopSwitches function, it removes too much stuff because it is not meeting the threshold, when that stuff could be useful still.

t <- exampleSwitchListAnalyzedSubset$isoformSwitchAnalysis
mappings <- exampleSwitchListAnalyzed$isoformFeatures[,c('gene_ref','gene_name')]
t <- merge(t, mappings, by = 'gene_ref')

Thanks.

**Comment by kvittingseerup** [comment]
If your aim was to add the "gene_name" to the DE result then your code looks good.
