### ISSUE TITLE
Cannot import Stringtie data?

### ISSUE THREAD

**Issue by wolfgangrumpf** [kvittingseerup/IsoformSwitchAnalyzeR#36]
I have a t_data.ctab file that I want to import into IsoformSwitchAnalyzeR.  When I use this command:

test <- importIsoformExpression(system.file("t_data.ctab", package="IsoformSwitchAnalyzeR"))

The results is:

Step 1 of 3: Identifying which algorithm was used...
Error in dirList[sapply(dirList, FUN = function(aDir) { : 
  invalid subscript type 'list'

I also tried:  test <- importIsoformExpression("t_data.ctab")

and got;

Step 1 of 3: Identifying which algorithm was used...
Error in dirList[sapply(dirList, FUN = function(aDir) { : 
  invalid subscript type 'list'

**Comment by wolfgangrumpf** [comment]
I also tried using the entire assembly directory, e.g.:

test <- importIsoformExpression("assembly/t_data.ctab")

Just to make sure it wasn't missing the other files in that directory.

And still no change.  Same error.

**Comment by kvittingseerup** [comment]
Hi Wolfgang

Could I get you to update to IsoformSwitchAnalyzeR v1.5.10 and try again?

You can update via the following R command - remember to restart R before rerunning the code :-)

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

**Comment by wolfgangrumpf** [comment]
A different error now, so progress of a sort:

> test <- importIsoformExpression("assembly/t_data.ctab")
Error in importIsoformExpression("assembly/t_data.ctab") : 
  The file pointed to with the 'parentDir' argument seems not to be a directory. Did you mean to use the 'sampleVector' argument?
>

**Comment by kvittingseerup** [comment]
That is because importIsoformExpression() can either import all files in sub-directores (via the parentDir argument) or pre-specified files (via the sampleVector).

Since you want to import a specific file you need to use the sampleVector argument. Simply change your code to:

```
test <- importIsoformExpression( sampleVector = "assembly/t_data.ctab")
```

**Comment by wolfgangrumpf** [comment]
Got it.  I hate to be a pain, but now I'm getting:

Error in importIsoformExpression(sampleVector = "assembly/t_data.ctab") : 
  When importing StringTie results the 'readLength' argument must be specified.
 This argument must be set to the number of base pairs sequenced (e.g. if the 
 quantified data is 75 bp paired ends 'readLength' should be set to 75.


I'm using PacBio data, not paired end data.....will it work anyway?

**Comment by kvittingseerup** [comment]
Hi Wolfang

You should probably read the documentation to importIsoformExpression() before continuing (try type ```?importIsoformExpression``` in R) :-)

With regards to whether it will work: the "t_data.ctab" name indicate you have StringTie data (right?) IsoformSwitchAnalyzeR does support StringTie quantification but I though PacBio data was not quantitative? You need to be sure of this - If it is not quantitative you are probably better of using the importGTF() functionality for the transcripts assembled with StringTie.

Cheers
Kristoffer

**Comment by wolfgangrumpf** [comment]
Correct, I have stringtie data.....I'm not as interested in quantitation as I am in detection jumbled exons.  I'll take a look at the docs!  :)
