### ISSUE TITLE
isoformSwitchTestDEXSeq: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by tjakobi** [kvittingseerup/IsoformSwitchAnalyzeR#38]
Hi,

I started to use the IsoformSwitchAnalyzeR to analyze an experiment and use salmon input with an Ensembl reference genome. 

`importIsoformExpression`, `importRdata`, and `isoformSwitchAnalysisPart1` are working well and run without issues. 

For the importRdata step I was not entirely sure which FASTA files to use best, so I tried the following setup:

```
aSwitchList <- importRdata(
    isoformCountMatrix   = salmonQuant$counts,
    isoformRepExpression = salmonQuant$abundance,
    designMatrix         = myDesign,
    ignoreAfterPeriod = TRUE,
    isoformExonAnnoation = "Rnor_6.0.90.gtf",
    isoformNtFasta       = "Rattus_norvegicus.Rnor_6.0.cdna.all.fa",
    showProgress = TRUE
)
```

Is the cDNA NT file in this case the right choice? Anyway, I wanted to perform the `isoformSwitchTestDEXSeq` work flow but that had to stop with the following error:

```
Step 1 of 2: Testing each pairwise comparisons with DEXSeq (this might be a bit slow)...
    Estimated time (for dataset with ~30.000 isoforms): 7.8 min
  |                                                                      |   0%Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
Calls: isoformSwitchTestDEXSeq ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
In addition: Warning message:
non-unique values when setting 'row.names':  
```
Looking at the contents of supplied object, it seems that several isoforms are coming up multiple times and seem to only differ in the columns `iso_overall_mean` and following. Would you have any hints on how to process the data?

I am using IsoformSwitchAnalyzeR 1.6.0 and R 3.6.

Thank you so much,
Tobias

**Comment by kvittingseerup** [comment]
Hi Tobias

Thanks for reaching out! This seems quite strange but lets try to get to the bottom of it.

Can you post the code for how you use importIsoformExpression() as well? Witch tool did you use for quantifying RNAseq data?

with regards to the fasta file I cannot comment on it as I dont know where they are from. I would suggest downloading it from the same resource, fx Ensembl.

Cheers
Kristoffer

**Comment by tjakobi** [comment]
Hi Kristoffer,

thanks for getting in touch. 

Here is the code fragment for the import process:

```
salmonQuant <- importIsoformExpression(
    parentDir = salmon_dir,
    addIsofomIdAsColumn = FALSE
)
```
I tried both, `addIsofomIdAsColumn = FALSE` and `addIsofomIdAsColumn = TRUE` with the same end result. I used salmon 0.12.0 based on an Index from the Ensembl build 90 of the rat genome.

The FASTA files are directly from the Ensembl FTP server:

* ftp://ftp.ensembl.org/pub/release-90/fasta/rattus_norvegicus/cdna/Rattus_norvegicus.Rnor_6.0.cdna.all.fa.gz
* ftp://ftp.ensembl.org/pub/release-90/gtf/rattus_norvegicus/Rattus_norvegicus.Rnor_6.0.90.gtf.gz

Please let me know if you require additional information. 

Thanks!
Tobias

**Comment by kvittingseerup** [comment]
Hmm this looks really strange. Could you post or email me the design matrix?

The fasta file looks good.

Cheers
Kristoffer

**Comment by tjakobi** [comment]
Sure:

```
> print(myDesign)
          sampleID condition
1  Control_1   Control
2  Control_2   Control
3  Control_3   Control
4  TP3_1   TP3
5  TP3_2   TP3
6  TP3_3   TP3
7   TP1_1    TP1
8   TP1_2    TP1
9   TP1_3    TP1
10  TP2_1    TP2
11  TP2_2    TP2
12  TP2_3    TP2
```

**Comment by tjakobi** [comment]
Dear Kristoffer,

is it possible that I am actually running DexSeq twice? From the detailed documentation it is not completely clear to me if the high level function `isoformSwitchAnalysisPart1` already includes the DEXSeq run. The ` switchTestMethod = "DEXSeq"` argument makes that a possiblity. 

In that case it probably makes sense that DEXSeq fails, since I ran `isoformSwitchTestDEXSeq` with the object returned by `isoformSwitchAnalysisPart1`.

Cheers,
Tobias

**Comment by kvittingseerup** [comment]
You can run isoformSwitchAnalysisPart1() successfully?

**Comment by kvittingseerup** [comment]
Problem will be fixed with next update.

**Comment by tjakobi** [comment]
Dear Kristoffer,

for the sake of completeness, yes I was able to run `isoformSwitchAnalysisPart1() ` successfully.

Thank you for your help,
Tobias
