### ISSUE TITLE
NaNs produced with odd number of conditions

### ISSUE THREAD

**Issue by dlukacso** [kvittingseerup/IsoformSwitchAnalyzeR#39]
I tried to run IsoformSwitchAnalyzeR with multiple conditions. Here is the code that I used:

`
perform_switching_analysis <- function(sampleTable, save_name, get_switch=TRUE){
    # get target files
    file_names <- paste('Lab_Pvalb_95', sampleTable$sampleID, 'abundance.tsv', sep='/')
    names(file_names) <- sampleTable$sampleID
    
    # Read Cells
    kallistoQuant <- importIsoformExpression(
        sampleVector = file_names,
        addIsofomIdAsColumn = TRUE
    )
    
    # Add Annotations
    gtf_name = 'Mus_musculus.GRCm38.95.chr_patch_hapl_scaff.gtf.gz'
    fasta_name = 'Mus_musculus.GRCm38.cdna.95.fa.gz'
    
    aSwitchList <- importRdata(
        isoformCountMatrix   = kallistoQuant$counts,
        isoformRepExpression = kallistoQuant$abundance,
        designMatrix         = sampleTable,
        isoformExonAnnoation = gtf_name,
        isoformNtFasta = fasta_name,
        showProgress = FALSE,
    )
    
    # Prefilter
    aSwitchList <- preFilter(
        switchAnalyzeRlist = aSwitchList,
        geneExpressionCutoff = 10,
        isoformExpressionCutoff = 3,
        IFcutoff = .1,
        dIFcutoff = .1,
        alpha = .1,
        removeSingleIsoformGenes = TRUE
    )
    
    # Test for Switching
    aSwitchList <- isoformSwitchTestDRIMSeq(
        switchAnalyzeRlist = aSwitchList,
        reduceToSwitchingGenes=get_switch,
        quiet=TRUE,
        alpha=0.10,
        dIFcutoff = 0.1,
        showProgress = FALSE,
    )
    
    # Save Isoforms to File
    write.table(aSwitchList$isoformFeatures,
                file=sprintf('%s.tsv', save_name),
                sep='\t',
                quote=FALSE,
                row.names=FALSE
    )

    # Save Switching Results
    saveRDS(aSwitchList, sprintf('%s.RData', save_name))
}
`

`
sampleTable <- read.table(fname, sep='\t', header=TRUE, stringsAsFactors=FALSE)
perform_switching_analysis(sampleTableHarris, 'Comparison_Harris', get_switch = TRUE)
`

where fname is a tab separated file of the form:

sampleID	condition
O100	BC
O102	HBC
O103	BC
O109	BC
O111	BC
O113	BC
O114	BC
O117	BC
O125	BiC
O127	AAC
O128	BC
O129	BC
O130	BC
O131	BC
O132	AAC
O135	BC
O137	BC
O141	BiC
O145	BC
O147	BC
O149	AAC
O159	BiC

(the actual sample file is longer)

What I have found, is that this works if I have 4 conditions in sampleTable. Similarly, it works if I trim it to just 2 conditions for pairwise comparisons. However, if I try it with 3 conditions, or 5 conditions (using a different method to label our cell types), then isoformSwitchTestDRIMSeq starts printing NaNs produced, over and over again. In large enough numbers that printing them is causing RStudio to lag. Whenever this happens I abort the run so I don't know if letting it run would still produce good results

**Comment by kvittingseerup** [comment]
Hi 

Thanks for reaching out. I do not think it is something to do with the odd number of condition since one of the example dataset have 3 conditions and work fine for me.

Can you try running the following code:

    library(IsoformSwitchAnalyzeR)
    
    ### import data
    salmonQuant <- importIsoformExpression(system.file("extdata/", package="IsoformSwitchAnalyzeR"))

    ### Make design matrix
    myDesign <- data.frame(
        sampleID = colnames(salmonQuant$abundance)[-1],
        condition = gsub('_.*', '', colnames(salmonQuant$abundance)[-1])
    )

    ### Create switchAnalyzeRlist
    aSwitchList <- importRdata(
        isoformCountMatrix   = salmonQuant$counts,
        isoformRepExpression = salmonQuant$abundance,
        designMatrix         = myDesign,
        isoformExonAnnoation = system.file("extdata/example.gtf.gz", package="IsoformSwitchAnalyzeR"),
        isoformNtFasta       = system.file("extdata/example_isoform_nt.fasta.gz", package="IsoformSwitchAnalyzeR")
    )

    ### Subset and test
    aSwitchList <- preFilter(aSwitchList)
    aSwitchList <- isoformSwitchTestDEXSeq(aSwitchList)
    aSwitchList
    

So I have 4 questions for you:

- Does the above code chunk work for you?
- What version of IsoformSwitchAnalyzeR are you using?
- Also I'm not sure what you mean by "printing NaNs produced" - could you post examples that warning?
- Does the NaN only occure when you include a specific condition?

Cheers
Kristoffer

**Comment by dlukacso** [comment]
Thank you for the quick response.

Slightly out of order on the bullet points:
	•	The above code chunk works for me
	•	IsoformSwitchAnalyzeR is version 1.6.0, R is version 3.6.0
	•	With one classification method, I have 4 conditions: BC, HBC, BiC and AAC, and I get the error on the following triplets
	⁃	AAC, HBC, BiC
	⁃	BC, HBC, BiC
	⁃	BC, AAC, BiC
	⁃	BC, AAC, HBC
	•	In turn, the following sets work:
	⁃	All 4 together
	⁃	AAC, BC
	⁃	AAC, HBC
	⁃	AAC, BiC
	⁃	BC, HBC
	⁃	BC, BiC
	⁃	HBC, BiC
	•	With another classification method, I have 5 conditions: clust_00, clust_01, clust_02, clust_03 and clust_04, and I get the error on the following sets:
	⁃	All 5 together
	⁃	clust_00, clust_01, clust_02
	⁃	clust_00, clust_01, clust_03
	⁃	clust_00, clust_01, clust_04
	⁃	clust_00, clust_02, clust_03
	⁃	clust_00, clust_02, clust_04
	⁃	clust_00, clust_03, clust_04
	⁃	clust_01, clust_02, clust_03
	⁃	clust_01, clust_02, clust_04
	⁃	clust_01, clust_03, clust_04
	⁃	clust_02, clust_03, clust_04
	•	In turn, the following sets work (I didn’t check all due to time constraints):
	⁃	clust_00, clust_01, clust_02, clust_03
	⁃	clust_01, clust_02, clust_03, clust_04
	•	The following is that the output generally looks like (the number of files read varies depending on which 3 conditions are chosen):


```
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: Kallisto
Step 2 of 3: Reading data...
Note: importing abundance.h5 is typically faster than abundance.tsv
reading in files with read_tsv
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 
Step 3 of 3: Normalizing FPKM/TxPM values via edgeR...
Done

Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Step 3 of 6: Calculating gene expression and isoform fraction...
     44843 ( 38.64%) isoforms were removed since they were not expressed in any samples.
Step 4 of 6: Merging gene and isoform expression...
Step 5 of 6: Making comparisons...
Step 6 of 6: Making switchAnalyzeRlist object...
Done
The filtering removed 59676 ( 83.79% of ) transcripts. There is now 11548 isoforms left
Youc might want to consider using isoformSwitchTestDEXSeq() instead. 
The DEXSeq implementation have been shown to superiour to DRIMSeq 
on all paramters (except runtime for large number of samples) 
by Love et al 2018 (F1000) - results we can replicate.
Most journals and scientists consider an alpha larger than 0.05 untrustworthy. We therefore recommend using alpha values smaller than or queal to 0.05NaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs produced
```

Sincerely,
David

**Comment by kvittingseerup** [comment]
Hi David

Thanks for the detailed response!

And naturally I made a mistake. Should have asked you to run the DRIMseq verion of the code (not the DEXSeq).

```
library(IsoformSwitchAnalyzeR)

### import data
salmonQuant <- importIsoformExpression(system.file("extdata/", package="IsoformSwitchAnalyzeR"))

### Make design matrix
myDesign <- data.frame(
    sampleID = colnames(salmonQuant$abundance)[-1],
    condition = gsub('_.*', '', colnames(salmonQuant$abundance)[-1])
)

### Create switchAnalyzeRlist
aSwitchList <- importRdata(
    isoformCountMatrix   = salmonQuant$counts,
    isoformRepExpression = salmonQuant$abundance,
    designMatrix         = myDesign,
    isoformExonAnnoation = system.file("extdata/example.gtf.gz", package="IsoformSwitchAnalyzeR"),
    isoformNtFasta       = system.file("extdata/example_isoform_nt.fasta.gz", package="IsoformSwitchAnalyzeR")
)

### Subset and test
aSwitchList <- preFilter(aSwitchList)
aSwitchList <- isoformSwitchTestDRIMSeq(aSwitchList)
aSwitchList
```

Do you also get the warnings there?

Cheers
Kristoffer

**Comment by dlukacso** [comment]
Hi Kristoffer

Produces the following output:

```
This switchAnalyzeRlist list contains:
 348 isoforms from 78 genes
 3 comparison from 3 conditions (in total 6 samples)

Switching features:
           Comparison switchingIsoforms switchingGenes
1 Fibroblasts vs hESC                67             35
2  Fibroblasts vs iPS               128             59
3         hESC vs iPS                93             51
4            combined               175             78

Feature analyzed:
[1] "Isoform Switch Identification, ntSequence"
```

So it seems to run, but it still shows the warnings. If I run the `aSwitchList <- isoformSwitchTestDRIMSeq(aSwitchList)` command in the console instead of in an RStudio notebook, I get `There were 50 or more warnings (use warnings() to see the first 50)` and the warnings are:
```
Warning messages:
1: In isoformSwitchTestDRIMSeq(aSwitchList) :
  Youc might want to consider using isoformSwitchTestDEXSeq() instead. 
The DEXSeq implementation have been shown to superiour to DRIMSeq 
on all paramters (except runtime for large number of samples) 
by Love et al 2018 (F1000) - results we can replicate.

2: In log(det(n * (-H))) : NaNs produced
3: In log(det(n * (-H))) : NaNs produced
4: In log(det(n * (-H))) : NaNs produced
5: In log(det(n * (-H))) : NaNs produced
6: In log(det(n * (-H))) : NaNs produced
7: In log(det(n * (-H))) : NaNs produced
8: In log(det(n * (-H))) : NaNs produced
9: In log(det(n * (-H))) : NaNs produced
10: In log(det(n * (-H))) : NaNs produced
11: In log(det(n * (-H))) : NaNs produced
12: In log(det(n * (-H))) : NaNs produced
13: In log(det(n * (-H))) : NaNs produced
14: In log(det(n * (-H))) : NaNs produced
15: In log(det(n * (-H))) : NaNs produced
16: In log(det(n * (-H))) : NaNs produced
17: In log(det(n * (-H))) : NaNs produced
18: In log(det(n * (-H))) : NaNs produced
19: In log(det(n * (-H))) : NaNs produced
20: In log(det(n * (-H))) : NaNs produced
21: In log(det(n * (-H))) : NaNs produced
22: In log(det(n * (-H))) : NaNs produced
23: In log(det(n * (-H))) : NaNs produced
24: In log(det(n * (-H))) : NaNs produced
25: In log(det(n * (-H))) : NaNs produced
26: In log(det(n * (-H))) : NaNs produced
27: In log(det(n * (-H))) : NaNs produced
28: In log(det(n * (-H))) : NaNs produced
29: In log(det(n * (-H))) : NaNs produced
30: In log(det(n * (-H))) : NaNs produced
31: In log(det(n * (-H))) : NaNs produced
32: In log(det(n * (-H))) : NaNs produced
33: In log(det(n * (-H))) : NaNs produced
34: In log(det(n * (-H))) : NaNs produced
35: In log(det(n * (-H))) : NaNs produced
36: In log(det(n * (-H))) : NaNs produced
37: In log(det(n * (-H))) : NaNs produced
38: In log(det(n * (-H))) : NaNs produced
39: In log(det(n * (-H))) : NaNs produced
40: In log(det(n * (-H))) : NaNs produced
41: In log(det(n * (-H))) : NaNs produced
42: In log(det(n * (-H))) : NaNs produced
43: In log(det(n * (-H))) : NaNs produced
44: In log(det(n * (-H))) : NaNs produced
45: In log(det(n * (-H))) : NaNs produced
46: In log(det(n * (-H))) : NaNs produced
47: In log(det(n * (-H))) : NaNs produced
48: In log(det(n * (-H))) : NaNs produced
49: In log(det(n * (-H))) : NaNs produced
50: In log(det(n * (-H))) : NaNs produced
```

My question, I suppose, is that is the output correct? If so, I suppose I can just run it with warnings suppressed.

Sincerely
David

**Comment by kvittingseerup** [comment]
It is a known problem with DRIMSeq - which unfortunately is not well maintained.

You can suppress the warnings with suppressWarnings().

Why not use isoformSwitchTestDEXSeq instead?

Cheers
Kristoffer

**Comment by dlukacso** [comment]
Ah, thank you for that.

I'm running the analysis on a lab computer, and the DEXSeq based run would take on the order of weeks. I could have the DRIMSeq run is an hour or two. The plan is to run it finally using DEXSeq when we have a better idea of the results

Sincerely,
David

**Comment by kvittingseerup** [comment]
Fair enougth - the DEXSeq runtime is unfortunately also a known problem
