### ISSUE TITLE
typo in tittle (don't hate me)

### ISSUE THREAD

**Issue by lpantano** [kvittingseerup/IsoformSwitchAnalyzeR#4]
Hi,

I just saw this super nice package that I will try for sure. 

Don't hate me, but maybe it would be good to fix the typos in the tittle:

```
Title: An R package to Identify, Annotate and Visualize Isoform Switches with Functional Consequences (from RNA-seq data)
```

**Comment by khoegenauer** [comment]
Your issue regarding title typos has a typo.

**Comment by kvittingseerup** [comment]
Thanks for letting me know - will be fixed in the next update.

**Comment by lpantano** [comment]
@khoegenauer, totally deserved that! :)
