### ISSUE TITLE
P values as well as q values in exampleSwitchListAnalyzed$isoformFeatures

### ISSUE THREAD

**Issue by crj32** [kvittingseerup/IsoformSwitchAnalyzeR#40]
Hi

Is it possible to get p values as well as the corrected values of these in the output table? Some isoforms just have NA for a iso switch q value, can I get a p value for those, were they tested?

Thanks,

Chris

**Comment by kvittingseerup** [comment]
Hi Chris

Thanks for reaching out. The full test analysis can be found in the "isoformSwitchAnalysis" entry of the switchAnalyzeRlist as illustrated by this code.

```
data("exampleSwitchListIntermediary")
head(exampleSwitchListIntermediary$isoformSwitchAnalysis)
```

With regards to NA's which test did you use?

**Comment by crj32** [comment]
Thanks for responding. I used this code.

  exampleSwitchListAnalyzed <- isoformSwitchTestDRIMSeq(
    switchAnalyzeRlist = exampleSwitchListFilteredStrict,
    testIntegration='isoform_only',
    reduceToSwitchingGenes=FALSE

A second issue is it would be really helpful to get the transcript names such as CCL5-201 into your output data frames:

outputdata <- exampleSwitchListAnalyzed$isoformFeatures # I'm using this for the volcano, some isoforms have q value as NA
morestuff<-exampleSwitchListAnalyzed$isoformSwitchAnalysis # This you have recommended for the p values

This is because for a volcano plot I want to annotate specific isoforms with their names not complex IDs. I can get the info from the gtf or fa file, but I just thought I would suggest an addition.

**Comment by crj32** [comment]
Also used these settings, any idea why NA q values happen? Can't find those isoforms in this object exampleSwitchListAnalyzed$isoformSwitchAnalysis.

## create switchAnalyzeRlist
aSwitchList <- importRdata(
  isoformCountMatrix   = salmonQuant$counts,
  isoformRepExpression = salmonQuant$abundance,
  designMatrix         = myDesign,
  isoformExonAnnoation = "~/Desktop/assemblies/v29_r4ra/gencode.v29.annotation.gtf.gz",
  showProgress = FALSE
)

## filter the data
exampleSwitchListFilteredStrict <- preFilter(
  switchAnalyzeRlist = aSwitchList,
  geneExpressionCutoff = 1, # 10 hard/ 1 soft
  isoformExpressionCutoff = 0, # 3 hard/ 0 soft
  removeSingleIsoformGenes = TRUE
)

**Comment by kvittingseerup** [comment]
Hi Chris

It is a well known problem tha DRIMSeq (which is the tool used in ```isoformSwitchTestDRIMSeq()```) produces NAs for some test. The problem is that for specific combinations of isoform-level counts is simply does not work. You can read (a bit) more about it in [this article](https://f1000research.com/articles/7-952/v3). Alternatively you can use ```isoformSwitchTestDEXSeq()``` which I BTW recommend since it produces more trustworthy results.

Thanks for the idea with the transcript names.

Cheers
Kristoffer
