### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dktanwar** [kvittingseerup/IsoformSwitchAnalyzeR#42]
CPPred: https://academic.oup.com/nar/article/47/8/e43/5314020

**Comment by kvittingseerup** [comment]
Thanks for the suggestion. Is it just me or does CPPred compared to CPC2 and CPAT (already supported) only look like a very small improvement for standard transcripts?

**Comment by dktanwar** [comment]
Yes, upon checking plots it seems like the difference in improvement is little.

Not sure though if all tools use the same RNA sequences: https://academic.oup.com/view-large/figure/134278841/gkz087fig3.jpg

**Comment by kvittingseerup** [comment]
If there are no substantial improvements in either performance or usability I'll wait with updating IsoformSwitchAnalyzeR. But thanks for the suggestion :-)
