### ISSUE TITLE
Question about importIsoformExpression with salmon

### ISSUE THREAD

**Issue by josruirod** [kvittingseerup/IsoformSwitchAnalyzeR#43]
Hi, thank you for the package. It's very convenient and I'm using it a lot.
So I have been using the function importIsoformExpression() to directly get the count from salmon quant.
I have now a situation where I have 2 different sf files for the same sample (sequenced differently), and I would like IsoformSwitchAnalyzeR to get them at the same time.

So my questions are, can importIsoformExpression take a file from salmon quantmerge? And particularly, which counts do the package work with? The "TPM" column on the sf file or the "NumReads" column? If I knew this I could manually sum the columns and proceed with the package.

Thanks for your support!

**Comment by kvittingseerup** [comment]
As long as they are seperate .sf files there is no problem with importing them. Do you experience problems?

Why do you have different quantifications if you want to merge them? Btw you should not just sum the data - that will not work for TPM values (and since counts depent on TPMs you will run into problems there as well).

**Comment by josruirod** [comment]
Thanks for your useful response. I explained myself poorly.
So I have in a directory 4 folders with the corresponding output from salmon: a_1, a_2, b_1, b_2
I was wondering if there was any way of merging a_1 and a_2, so IsoformSwitchAnalyzeR received the info as if they were a single folder.

But just realized it probably does not make sense, because in the design matrix I could specifiy they are the sample/condition.

Thanks for your comments!

**Comment by kvittingseerup** [comment]
Just remember that it is not a [biological independent](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-constitute-an-independent-biological-replicate) replicate so be carefull not to treat it as such.
