### ISSUE TITLE
Bugs in switchPlotTopSwitches() function

### ISSUE THREAD

**Issue by apuhegde** [kvittingseerup/IsoformSwitchAnalyzeR#44]
Thank you for making this useful tool!

I'm running into some issues when I run the `switchPlotTopSwitches()` plotting function, which I traced down to the following bugs in the plot_all_iso_switch.R script as it is currently implemented (I'm using IsoformSwitchAnalyzeR v1.2.0, and I used the code from gitHub to debug):

1) Line 267: `if (!file.exists(myComparison[i, j]))`
myComparison is a tibble, so `myComparison[i, j]` acts as a tibble. When it's passed to the function `file.exists()`, it results in the following error:
`Error in file.exists(myComparison[i, j]) : invalid 'file' argument`

I debugged this by converting it to a character string using `as.character()`.

2) When I rerun it, I get the following error next:
`Error in pdf(file = paste(fileName, ".pdf", sep = ""), height = 5, width = 8,  : 
cannot open file 'D:/Control_vs_Tumor//without_consequences/07_switch_plot_ENSG00000069667_aka_RORA.pdf'`
Turns out it's due to the double "/". So I removed the last"/" wherever it occurs when used with the `paste()` function (for eg., lines 247,250,255,281,290).

These steps seem to have debugged the script successfully and I'm now able to successfully write the plots to pdf using the `switchPlotTopSwitches()` function.

Can you please test this/try to recreate it and let me know if I need to put in a pull request to I can push these changes to your script?

Thanks.

**Comment by kvittingseerup** [comment]
Hi

Sorry for the late response ( paternity leave ).

Thanks for putting in all the hard work of debugging this. 

I have not seen double "/" being a problem before - which operating system are you using? (Windows?).

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Were you using windows?

**Comment by kvittingseerup** [comment]
Closing issue as I'm assuming the no-response means it was solved
