### ISSUE TITLE
Error on isoformSwitchTestDEXSeq

### ISSUE THREAD

**Issue by keenhl** [kvittingseerup/IsoformSwitchAnalyzeR#45]
I get an error when trying to run the DEXSeq test

Here is the design, top 6 rows only, there are 22 rows, M and F gender

      sampleID gender condition
H7568    H7568      F        wt
H7571    H7571      F        wt
H7572    H7572      F        ko
H7579    H7579      F        wt
H7588    H7588      F        ko
H7791    H7791      F        ko

filtering step

  filteredSwitchList <-  preFilter(
    switchAnalyzeRlist = aSwitchList,
    geneExpressionCutoff = 1,
    isoformExpressionCutoff = 0,
    removeSingleIsoformGenes = TRUE
)

DEXSeq test

filteredSwitchList <- isoformSwitchTestDEXSeq(
    switchAnalyzeRlist = filteredSwitchList,
    reduceToSwitchingGenes=TRUE
)

The error:

Error in nbinomLRT(x, reduced = reducedModelMatrix, full = fullModelMatrix) : less than one degree of freedom, perhaps full and reduced models are not in the correct order

Any thoughts about the error or steps I should take the debug/solve the problem.  Thank you for your help.

**Comment by kvittingseerup** [comment]
Hi

Thanks for reaching out and sorry for the late response ( paternity leave ).

That looks strange. The only idea i have would be to try and use something different from "F" for female (since F in R language can be interpreted as the logic FALSE). Does that help?

Cheers
Kristoffer

**Comment by keenhl** [comment]
No problem.  Thanks for the suggestion.  I will test it out and provide an update later.

**Comment by keenhl** [comment]
So, I ran the code again and got the same error.  Changing M to Male and F to Female didn't prevent the error.  What did work, for me, was changing the order of the columns to sampleID, condition, then gender.   Thanks again.

**Comment by kvittingseerup** [comment]
Thanks for letting me know - will fix this problem in a future update
