### ISSUE TITLE
Error with switchPlot 

### ISSUE THREAD

**Issue by crj32** [kvittingseerup/IsoformSwitchAnalyzeR#47]
Any idea how to solve this, I am getting it for some genes, but most are OK. It does not plot for IL6ST.

Sorry for a lack of reproducible example, but I thought I would ask anyway.

Thanks, Chris.

> switchPlot(exampleSwitchListAnalyzedSubset, gene = 'IL6ST')
Error: Breaks and labels are different lengths

**Comment by kvittingseerup** [comment]
Thanks for reaching out and sorry for the late response ( paternity leave ).

Which version of IsoformSwitchAnalyzeR are you using? Can I get you to try with 1.7.1 - should be installable with the following command

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Closing this issue as I interpret the "no response" as a "issue solved"
