### ISSUE TITLE
multiple comparisons issue

### ISSUE THREAD

**Issue by aprezvykh** [kvittingseerup/IsoformSwitchAnalyzeR#48]
Hello! Thank you for creating a such multifunctional and useful package for isoform switch analysis!

I've got a question about multiple comparisons. I've got 10 samples, with 5 different conditions (analysed with hisat2/stringtie). That's a part of my code. I've created design matrix and condition data frame as described in manual
```
myQantifications <- importIsoformExpression(parentDir = '/my/target/dir',
                                            pattern = 'SRR',readLength = 75,showProgress = T)

design <- data.frame(sampleID = colnames(myQantifications$abundance[,2:11]), 
                     condition = c('Wt1', 'Wt1', 'Wt3', 'Wt3', 'Tg1', 'Tg1', 'Tg2', 'Tg2', 'Tg3', 'Tg3'))

cond <- data.frame(condition_1 = c('Wt3','Tg1','Tg2','Tg3'),
                   condition_2 = c('Wt1','Wt1','Tg1','Tg1'))

mySwitchList <- importRdata(isoformCountMatrix = myQantifications$abundance,
                            showProgress = T,
                            designMatrix = design,
                            isoformExonAnnoation = '/my/target/dirmerged.annotated.gtf',
                            comparisonsToMake = cond)
```
Here is the output of mySwitchList command, and that's still OK
```
This switchAnalyzeRlist list contains:
 121347 isoforms from 36052 genes
 4 comparison from 5 conditions
```

But when i run a statistical test to calculate pairwise comparison statistics (preFilter arguments are quiet strickt to reduce calculation time), i've got only one pairwise comparison, that was first in comparisonsToMake data frame:
```
mySwitchList <- preFilter(mySwitchList,geneExpressionCutoff = 1,IFcutoff = 0.2,quiet = F,isoformExpressionCutoff = 7)
mySwitchList <- isoformSwitchTestDEXSeq(mySwitchList,showProgress = T,correctForConfoundingFactors = T)
``` 
 Here is output of mySwitchList after running DEXseq statistical test. As you can see, there is only one statistical comparison, instead of all comparisonsToMake data frame.
```
This switchAnalyzeRlist list contains:
 19 isoforms from 9 genes
 1 comparison from 2 conditions
Switching features:
  Comparison switchingIsoforms switchingGenes
1 Tg1 vs Wt1                17              9
Feature analyzed:
[1] "Isoform Swich Identification"
```
Here is my question: how should i modify my code to get multiple pairwise comparisons in DEXseq test?

Thank you!

**Comment by kvittingseerup** [comment]
Could I get you to try and update to IsoformSwitchAnalyzeR 1.7.1 and try again?

This should be doable with the following R command:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

**Comment by kvittingseerup** [comment]
Closing this issue as I interpret the "no response" as a "issue solved"
