### ISSUE TITLE
IsoformSwitchAnalyzeR on short reads PE RNAseq dataset?

### ISSUE THREAD

**Issue by JamalEH** [kvittingseerup/IsoformSwitchAnalyzeR#49]
Dear Team,
Thank you for having developed the great tool SwitchaAnalyzeR!

I have a paired-end RNASeq dataset (2 conditions/3 replicates each) and I want differential switching between my two conditions, upon the silencing of a transcription factor. The dataset is paired-end (2x75bp) read lengths and 89M read depth.

In the manual it is stated that the tool can be run on full-length RNA-seq datasets. Can I run the SwitchAnalyzeR tool on my dataset even if it is a short read RNAseq?

Thank you so much in advance!
Best regards,
Jamal.

**Comment by kvittingseerup** [comment]
Hi Jamal

Thanks for reaching out. IsoformSwitchAnalyzeR work on any full length transcript _quantification_ - which is typically obtained from short RNASeq (but can also be obtained from long reads).

Your data can easily be analyzed by IsoformSwitchAnalyzeR when you can quantified it. If you are interested you can read more about how to quantify the data [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use).

Remember to use the newest version of IsoformSwitchAnalyzeR 1.7.1 which can be downloaded by copy/pasting the following command into R:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

Cheers
Kristoffer
