### ISSUE TITLE
Can't import RSEM outputs

### ISSUE THREAD

**Issue by qoiopipq** [kvittingseerup/IsoformSwitchAnalyzeR#52]
Hi,

I tried to input two libraries quantified separately by RSEM, but I got this error:
> files<-importIsoformExpression(parentDir = "./Documents/PacBio/IsoformSwitch/")
Step 1 of 3: Identifying which algorithm was used...
    The quantification algorithm used was: RSEM
    Found 2 quantification file(s) of interest
Step 2 of 3: Reading data...
reading in files with read_tsv
1 2 Error in tximport::tximport(files = localFiles, type = tolower(dataAnalyed$orign),  : 
  all(txId == raw[[txIdCol]]) is not TRUE
In addition: Warning message:
In txId == raw[[txIdCol]] :
  longer object length is not a multiple of shorter object length

Is it because of different number of transcripts in two conditions (or two libraries)? If this is the case, do I need to assign transcripts from two libraries to a new set of transcript IDs then do the analysis or any suggestions?

Cheers!

**Comment by kvittingseerup** [comment]
Most likely the two separate quantifications uses different annotations. 

When you look at the RSEM "isoforms.results" do they have the same number of lines? The same transcript_ids? If so you would need to re-quantify one (or both) of the libraries so the same set of transcripts have been quantified in both samples.

**Comment by qoiopipq** [comment]
Thanks for your help! Yes, these were on different annotations. As I got 2 PacBio libraries (for 2 conditions), and wanted to find condition-specific transcripts and also to quantify PacBio long reads using RNA-seq short reads. So I prepared RSEM annotation and quantified them separately.  If I merge 2 processed PacBio libraries as one annotation file, I think it may getting too many false positive short reads mapped and quantified under the wrong condition. 

Cheers!

**Comment by kvittingseerup** [comment]
What you would classically do is to create one merged transcriptome and quantify both samples using that. Then transcripts only found in one of them would be highly expressed in that sampled and lowly expressed in the other sample. You can read more about it [her](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use).
