### ISSUE TITLE
Error in importRdata

### ISSUE THREAD

**Issue by sk1350** [kvittingseerup/IsoformSwitchAnalyzeR#53]
I am running this code:
> aSwitchList <- importRdata(
+     isoformCountMatrix   = salmonQuant$counts,
+     isoformRepExpression = salmonQuant$abundance,
+     designMatrix         = myDesign,
+     isoformExonAnnoation = "gencode.v32.annotation.gtf.gz",
+     isoformNtFasta       = "gencode.v32.transcripts.fa.gz",
+     showProgress = FALSE
+ )
Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
**Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘seqnames’ for signature ‘"Seqinfo"’**
Could this potentially be an issue with GRanges?

**Comment by kvittingseerup** [comment]
Thanks for reaching out. It does look like an issue with rtracklayer (the package which imports the GTF fille) could you try:

```
test <- rtracklayer::import('path/to/gtf_file.gtf')
```

Which version of:

- R
- rtracklayer
- GenomicRanges

are you using?

Cheers
Krisotffer

**Comment by kvittingseerup** [comment]
Closing issue due to no response
