### ISSUE TITLE
switchPlot() figure details

### ISSUE THREAD

**Issue by iaradsouza1** [kvittingseerup/IsoformSwitchAnalyzeR#54]
Hi, I find your switchPlot() function very useful to describe isoform usage. But I have some very specific questions. I did not understand it by reading the function's documentation. I would like to know:

1 - What are the rectangles with different thickness in each transcript structure? Are all of them exons? In the case of the last transcript represented in the following figure, why are all rectangles thiner than the other ones? What are the black parts?

![actg1](https://user-images.githubusercontent.com/17734397/70561501-4fa5bf80-1b69-11ea-963c-1292021d790d.png)

**Comment by kvittingseerup** [comment]
The breakdown is as follows:

- each square repressent an exon and is collored black
- each line indicate an intron
- the square thickness repressent non-coding regions (thin) and coding regions (thick) and is based on the annoation (if you used a GTF) or our predictions (if you used analyzeORF() ).
- parts of the coding region annotated as containing a annotaion (in this case a protein domain) are collored according to that.
- The grouping in the right side of the plot (here all 'Coding') indicate the predicting by CPAT or CPC2 (whichevery you used).

Hope this helps.
Chhers
