### ISSUE TITLE
Comparison to RATs

### ISSUE THREAD

**Issue by dktanwar** [kvittingseerup/IsoformSwitchAnalyzeR#55]
Hi,

This is a great tool, and I really like the plotting features and integration of external analysis.

I would be very happy to know your opinion about **RATs**: https://f1000research.com/articles/8-213

**IsoformSwitchAnalyzeR** uses DEXSeq. RATs use `G-test` of independence. Have you compared the two? 

Do you think it would be good to have **RATs** implemented with **IsoformSwitchAnalyzeR**?

**Comment by kvittingseerup** [comment]
Thanks for the nice words :-).

I do know about RATs and it has been benchmarked amongst other [here](https://f1000research.com/articles/7-952) where it performs comparable to DEXSeq with small number of samples - but much more conservative with many samples. This - combined with the runtime - is why RATs is not currently directly supported in IsoformSwitchAnalyzeR.

Hope this answers your question.
