### ISSUE TITLE
error that I get in IsoformSwitchAnalyzeR

### ISSUE THREAD

**Issue by kapilaGIT** [kvittingseerup/IsoformSwitchAnalyzeR#56]
Hi, I have a problem in importRdata(). When I do this I get the following error

Specifically:
 57540 isoforms were quantified.
 54590 isoforms are annotated.
 Only 50362 overlap.
 7178 isoforms quantifed isoforms had no corresponding annoation
 
This combination cannot be analyzed since it will cause discrepencies between quantification and annotation thereby skewing all analysis.
 
If there is no overlap (as in zero or close) there are two options:
 1) The files do not fit together (e.g. different databases, versions, etc) (no fix except using propperly paired files).
 2) It is somthing to do with how the isoform ids are stored in the different files. This problem might be solvable using some of the 'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
     Examples from expression matrix are : NM_001193612, NM_024522, NM_001128917 
     Examples of annoation are : NM_201444, NM_001280791, NM_198515 
     Examples of isoforms which were only found im the quantification are  : NM_030959, NM_001170418, NM_001242356_8

Now if I take any ID of the last line I could find it in all gtf files including the merged gtf I use in importRdata() function. 

Do you have clue what I am doing wrong here. 

When I do this Ensembl the error is even worse. Here it is.

200310 isoforms were quantified.
 199216 isoforms are annotated.
 Only 0 overlap.
 200310 isoforms quantifed isoforms had no corresponding annoation
 
This combination cannot be analyzed since it will cause discrepencies between quantification and annotation thereby skewing all analysis.
 
If there is no overlap (as in zero or close) there are two options:
 1) The files do not fit together (e.g. different databases, versions, etc) (no fix except using propperly paired files).
 2) It is somthing to do with how the isoform ids are stored in the different files. This problem might be solvable using some of the 'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
     Examples from expression matrix are : ENST00000356297, ENST00000446853, ENST00000534710 
     Examples of annoation are : ENST00000514309.5, ENST00000589001.1, ENST00000513108.1 
     Examples of isoforms which were only found im the quantification are  : ENST00000468772, ENST00000448532, ENST00000434510

But again if I take any ID from the last line it is there in the Ensembl GTF file.

**Comment by kvittingseerup** [comment]
Hi 

Thanks for reaching out. Please note that this is not a problem with IsoformSwitchAnalyzeR or you but a problem with the files you provide. Unfortunatly providing matched files are not [always easy](https://twitter.com/KVittingSeerup/status/1029018660374044672).

For case 1: it simply looks like the files do not fit together. Where does the files originate from?

For case 2: the (main problem) seems to be that the annotation file have the transcript version numbers (e.g. ENST00000514309**.5**) but the expression matrix does not (e.g. ENST00000356297). This might be solved using the _ignoreAfterPeriod_ argument - did you try that?

Please take a look at [this section](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-transcript-database-should-i-use) of the vignette for more information on this problem and suggestions for how to solve it.

**Comment by kapilaGIT** [comment]
Hi,

Thank you very much for your reply and suggestions. I one attempt it was the hg38 gtf as I used hg38 genome for maping. There I get 50362 overlap. 

In the other attempt it was grc38 gtf file (Homo_sapiens.GRCh38.91.gtf) as I used grc38 genome for mapping. The problem there is I got 0 overlap.
