### ISSUE TITLE
warnings when runing external sequence analysis tool "signalP"

### ISSUE THREAD

**Issue by JamalEH** [kvittingseerup/IsoformSwitchAnalyzeR#57]
Daer Team,
May this e-mail finds you in a good shape.

For the sequence analysis part that is done with external tools, I run from my  computer the signalP tool with the following command line:
nohup ./signalp -fasta ../../isoformSwitchAnalyzeR_isoform_AA.fasta -format short -gff3 -plot none -prefix isoformSwitchAnalyzeR_isoform_AA &

the AA.fasta file was extracted while runing isoformSwitchAnalyzer.
While adding the signalP annotation to my switchlist I got the following warnings, even if the signalP analysis was run with -org "euk" option:
dded signal peptide information to 2224 (3.9%) transcripts
There were 35 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In analyzeSignalP(switchAnalyzeRlist = aSwitchListAnalyzed,  ... :
  It seems SignalP was run as Non-Eukaryote - was that on purpouse?
2: In FUN(X[[i]], ...) : NAs introduced by coercion
3: In FUN(X[[i]], ...) : NAs introduced by coercion
4: In FUN(X[[i]], ...) : NAs introduced by coercion
5: In FUN(X[[i]], ...) : NAs introduced by coercion
6: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
7: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
8: In max(which(transcriptCoordinats$start > exonCumsum)) :
  no non-missing arguments to max; returning -Inf
9: In max(which(transcriptCoordinats$end > exonCumsum)) :
  no non-missing arguments to max; returning -Inf
10: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
11: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
12: In max(which(transcriptCoordinats$start > exonCumsum)) :
  no non-missing arguments to max; returning -Inf
13: In max(which(transcriptCoordinats$end > exonCumsum)) :
  no non-missing arguments to max; returning -Inf
14: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
15: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
16: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
17: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
18: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
19: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
20: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
21: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
22: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
23: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
24: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
25: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
26: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
27: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
28: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
29: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
30: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
31: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
32: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
33: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
34: In max(which(transcriptCoordinats$start > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf
35: In max(which(transcriptCoordinats$end > exonRevCumsum)) :
  no non-missing arguments to max; returning -Inf

Should this be fine or something went wrong during the analysis step?

Thank you in advance!
Kind regards,
Jamal.

**Comment by kvittingseerup** [comment]
Hi Jamal

That does not look good. Looks like something went wrong when converting from transcript to genomic coordinates for some of the genes.

Which version of SignalP are you using on your server?

**Comment by JamalEH** [comment]
Hi,
Thank you for your response!

I have used the following latest signalP version signalp-5.0b.

Best regards,
Jamal

**Comment by kvittingseerup** [comment]
Hi Jamal

Ahh - I have actually not installed signalP5 on our server but just assumed it was similar to the result of the web-server (as it is for v4).

Would you be willing to share the unmodified/original signalP-5 result file (by email) - then I should be able to solve this problem. It would naturally be kept confidential and I would delete it when I was done with the debugging.

Cheers
Kristoffer

**Comment by JamalEH** [comment]
Dear Kristoffer,

I have sent you the requested file by e-mail.

Best regards,
Jamal.

**Comment by kvittingseerup** [comment]
Turns out there was a problem with SignalP5 when very short amino acid sequences were analyzed. The authors of SignalP are working on the problem and IsoformSwitchAnalyzeR 1.9.2 or higher are also equipped to deal with this problems.

Thanks for all the help figuring this one out Jamal

Cheers
Kristoffer
