### ISSUE TITLE
Importing Data from other Full-length Transcript Assemblers

### ISSUE THREAD

**Issue by ljw90607** [kvittingseerup/IsoformSwitchAnalyzeR#61]
Dear @kvittingseerup,

Hello, I am trying this wonderful tool you have developed, but having a difficult time creating the input.

From a manual you provided, you have listed the input files as below.
- The isoform abundance estimates in multiple samples from multiple conditions
- A design matrix that indicates which samples belong to which conditions
- The genomic coordinates of the isoform exon structure (most often stored as a GTF file).
- Annotation of which isoform belongs to which gene.
- The isoform nucleotide sequence (unless transcripts we de-novo/guide deconvoluted from the RNASeq data itself) (mostly stored as a fasta file).

Could you tell me the details of each file format? or possibly provide some example file so I could understand each file format?
Also, if you could provide the detailed script to import the files above for further usage, then it would really be helpful!
(Since I could not apply the example script provided from the manual.
aSwitchList <- importGTF(pathToGTF = system.file("extdata/example.gtf.gz", package="IsoformSwitchAnalyzeR")))

Thank you very much for your wonderful help.

Jungwoo.

**Comment by kvittingseerup** [comment]
Hi Jungwoo

Thanks for reaching out :-)

I suggest you take a closer look at the vignette - specifically you might find these sections (in this reading order) usefull:

- [The quick start](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#quick-start)

- [Importing data into R](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#importing-data-into-r)

Please note that both these sections contain example data included in the package.

Additionally you can find more information in the documentation for the _importRdata()_ function either [online](https://rdrr.io/bioc/IsoformSwitchAnalyzeR/man/importRdata.html) or by typing `?importRdata` in your R terminal (after loading the IsoformSwitchAnalyzeR package).

Let me know if you have any additional questions :-)

Cheers
Kristoffer

**Comment by ljw90607** [comment]
Thank you very much for your wonderful help. Your reference help a lot.

Jungwoo

**Comment by ljw90607** [comment]
Dear @kvittingseerup,

I just wanted to ask a quick question on the analyzeAlternativeSplicing().
It seems that the number of isoforms in the output of analyzeAlternativeSplicing is lower than the input file. (The number of isoforms is 37391 before running through the isoformSwitchTestDEXseq() and after the analyzeAlternativeSplicing(), I can only get 16908 reads from the exampleSwitchListAnalyzed_other$AlternativeSplicingAnalysis.

Do the filtered (or un-annotated) reads not get printed out? or would there be any reason for the filtered reads are not printed? 

Thank you very much for your help!

Jungwoo

**Comment by kvittingseerup** [comment]
I guess you mean 16908 isoforms? And if that is the case then yes that is on purpose. 

Check the `reduceToSwitchingGenes` and `reduceFurtherToGenesWithConsequencePotential` arguments in the [isoformSwitchTestDEXseq documentation](https://rdrr.io/bioc/IsoformSwitchAnalyzeR/man/IsoformSwitchTestDEXSeq.html).

Cheers
Kristoffer
