### ISSUE TITLE
IsoformswitchAnalyzeR for long read (TALON)

### ISSUE THREAD

**Issue by ashokpatowary** [kvittingseerup/IsoformSwitchAnalyzeR#62]
Hi @kvittingseerup 

I am trying to adapt IsoformSwitchAnalyzeR for long read isoform sequencing. Transcripts and abundance files were generated by TALON. While however I am coming across the following error. I am using version 1.8 

<img width="776" alt="Screen Shot 2020-04-19 at 5 05 17 PM" src="https://user-images.githubusercontent.com/42618005/79703478-ef363580-8260-11ea-894d-f3aff0f10be3.png">

Hoever I checked for the matching between isoform id (abundance file) and transcript id (TALON gtf) I can see 100% matching. Bellow is a screen shot for one of the id for which the tool failed to identify corresponding id in gtf file.

<img width="1071" alt="Screen Shot 2020-04-19 at 5 05 46 PM" src="https://user-images.githubusercontent.com/42618005/79703542-505e0900-8261-11ea-9240-46c146885f05.png">

Thanks

**Comment by kvittingseerup** [comment]
Hi 

Thanks for reaching out. This looks strange and like it is not supposed to happen.

For good measure could you try with IsoformSwitchAnalyzeR v1.9.1 from the [devel branch](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html)?

Could you try and look for the isoforms that IsoformSwitchAnalyzeR claims are not in the GTF file after importing the GTF file into R via`rtracklayer::import()`

If the isoform can be imported into R via `rtracklayer::import()` it is my code which does something unintended and I would need (a subset of) the GTF file to debug it - if you email such a (subset) to me I will fix this ASAP and naturally keep the file confidential :-)

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
Hi @kvittingseerup 

I can find the ids after importing via `rtracklayer::import()`. I can send a part of my file.

<img width="484" alt="Screen Shot 2020-04-20 at 9 25 05 AM" src="https://user-images.githubusercontent.com/42618005/79775720-821ab280-82e9-11ea-8f7e-5084cc9c7b77.png">

**Comment by kvittingseerup** [comment]
That is good news - then it is something in my code I can fix :-).

Could you also test if the isoforms are are there if you use IsoformSwitchAnalyzeR's `importGTF` function? Also if it gives any warnings please post them.

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
Hi @kvittingseerup 

Yess, the isoforms are available  with `importGTF` function.
<img width="669" alt="Screen Shot 2020-04-20 at 11 52 18 AM" src="https://user-images.githubusercontent.com/42618005/79788440-82bd4400-82fd-11ea-98dd-f024cf39fd6a.png">
However there was a wanring
<img width="748" alt="Screen Shot 2020-04-20 at 11 50 49 AM" src="https://user-images.githubusercontent.com/42618005/79788459-89e45200-82fd-11ea-9b71-0bc3b6442bfc.png">
How important is the ORF feature?

**Comment by kvittingseerup** [comment]
Hi Again.

I think the problem might be that you have some cross chromosome fusion transcripts (which IsoformSwitchAnalyzeR cannot handle). I've pushed an update which makes sure IsoformSwitchAnalyzeR better handles this.

Could you try and update to IsoformSwitchAnalyzeR 1.9.3 and try agin? You should be able to update via github (aka without upgrading R) via this R command:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

And please ignore the CDS warning - it is just because the default of the `addAnnotatedORFs` is TRUE but naturally there are not CDS in your dataset.

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
Hi @kvittingseerup 

I updated the package. But unfortunately same error is popping. 

<img width="501" alt="Screen Shot 2020-04-20 at 12 26 43 PM" src="https://user-images.githubusercontent.com/42618005/79791472-37f1fb00-8302-11ea-8a2b-0f99f9c993a2.png">
<img width="775" alt="Screen Shot 2020-04-20 at 12 23 45 PM" src="https://user-images.githubusercontent.com/42618005/79791478-3a545500-8302-11ea-9ead-306a6813bf9a.png">

**Comment by kvittingseerup** [comment]
Hi 

Did you restart R before trying with the updated version (I've tried that was nessesary)?

Could you try running `importRdata()` with `removeNonConvensionalChr=FALSE`?

Could you try running `importGTF()` and send me any warnings it prints?

If neither of these helps then we are back to that I would need you to send me the GTF file so I can debut it.

Cheers
Kristoffer

**Comment by kvittingseerup** [comment]
Could you also try with IsoformSwitchAnalyzeR 1.9.4 - which you can get from the github:

`
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
`

**Comment by ashokpatowary** [comment]
@kvittingseerup 
Thanks for your efforts. But still I am coming across the same error. I did restart the R after updating. With `importGTF()` I can see the CDS feature warning only. I can share part of my gtf file with you.

Thanks

**Comment by kvittingseerup** [comment]
Thanks for checking. You can get my email from the [Bioconductor website](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html)

**Comment by ashokpatowary** [comment]
@kvittingseerup 

I had just send you a small part of the data. 

Thanks

**Comment by ashokpatowary** [comment]
with version 1.9.5 there is no error.

**Comment by kvittingseerup** [comment]
Thanks for checking 😊

Cheers
Kristoffer

lør. 25. apr. 2020 kl. 09.38 skrev AshokP <notifications@github.com>:
