### ISSUE TITLE
ORF annotation for cufflinks import

### ISSUE THREAD

**Issue by CDieterich** [kvittingseerup/IsoformSwitchAnalyzeR#64]
Hi,

I try

testSwitchList <- importCufflinksFiles(
    pathToGTF                      = "/Volumes/cdieterich/index/cuffcmp.GRCh38_96.combined.gtf",
    pathToGeneDEanalysis           = "gene_exp.diff",
    pathToIsoformDEanalysis        = "isoform_exp.diff",
    pathToGeneFPKMtracking         = "genes.fpkm_tracking",
    pathToIsoformFPKMtracking      = "isoforms.fpkm_tracking",
    pathToIsoformReadGroupTracking = "isoforms.read_group_tracking",
    pathToSplicingAnalysis         = "splicing.diff",
    pathToReadGroups               = "read_groups.info",
    pathToRunInfo                  = "run.info",
    fixCufflinksAnnotationProblem=TRUE,
    quiet=TRUE
)

it all works fine.. except for the absence of ORF annotation.

How could I add the ORF information without predicting ORFs de novo.

Thx

**Comment by kvittingseerup** [comment]
There is no ORF annoation from in Cufflinks data so you have to predict it. Use can see the build in options - including using known start sites in dokumentation for the `analyzeORF()` function.
