### ISSUE TITLE
Long Read Abundance input

### ISSUE THREAD

**Issue by ashokpatowary** [kvittingseerup/IsoformSwitchAnalyzeR#66]
Hi @kvittingseerup 

I am having a query regarding input abundance file generated by TALON. Should I used the count matrix file generated by TALON or I should normalized it before using it IsoformSwitchAnalyzeR? 

thanks

**Comment by kvittingseerup** [comment]
Nope - you need raw un-modified counts.

Does TALON not produce normalized abundance values (if so you should also use those, and you can supply both to the `importRdata()` function).
