### ISSUE TITLE
Warnings when running isoformSwitchTestDRIMSeq

### ISSUE THREAD

**Issue by jalalsiddiqui** [kvittingseerup/IsoformSwitchAnalyzeR#68]
I get the following warnings when running isoformSwitchTestDRIMSeq

2: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
3: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
4: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
5: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
6: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
7: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
8: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
9: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
10: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
11: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
12: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'
13: In rowSums(lgamma(y + prec * prop) - lgamma(prop * prec)) :
  value out of range in 'lgamma'

**Comment by kvittingseerup** [comment]
Those are unfortunately known errors produced by [DRIMSeq](https://github.com/gosianow/DRIMSeq) (not IsoformSwitchAnalyzeR). I highly recommend using `isoformSwitchTestDEXSeq()` instead.

**Comment by jalalsiddiqui** [comment]
Thanks.  Will switch.
