### ISSUE TITLE
DEXSeq error

### ISSUE THREAD

**Issue by jalalsiddiqui** [kvittingseerup/IsoformSwitchAnalyzeR#69]
I tried to run it with the DEXSeq parameter and got the following error.

Step 1 of 3 : Detecting isoform switches...

error: matrix multiplication: incompatible matrix dimensions: 56x30 and 0x1
Error in fitBeta(ySEXP = ySEXP, xSEXP = xSEXP, nfSEXP = nfSEXP, alpha_hatSEXP = alpha_hatSEXP,  :
  matrix multiplication: incompatible matrix dimensions: 56x30 and 0x1
Calls: isoformSwitchAnalysisCombined ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

**Comment by kvittingseerup** [comment]
That does not look right. Could you run `traceback()` right after you get this error and post the resutl. Could you also post your design matrix?

**Comment by jalalsiddiqui** [comment]
The info is as follows:

PART 1: EXTRACTING ISOFORM SWTICH SEQUENCES
Step 1 of 3 : Detecting isoform switches...

error: matrix multiplication: incompatible matrix dimensions: 56x30 and 0x1
Error in fitBeta(ySEXP = ySEXP, xSEXP = xSEXP, nfSEXP = nfSEXP, alpha_hatSEXP = alpha_hatSEXP,  :
  matrix multiplication: incompatible matrix dimensions: 56x30 and 0x1
Calls: isoformSwitchAnalysisCombined ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: Warning message:
In isoformSwitchTestDEXSeq(switchAnalyzeRlist, reduceToSwitchingGenes = TRUE,  :
  Most journals and scientists consider an alpha larger than 0.05 untrustworthy. We therefore recommend using alpha values smaller than or queal to 0.05
Execution halted

The design matrix is 

[1] "list_allsamples" "Group2"   "Group1"
sampleID     condition
SRR*****01 SRR*****01 Group2
SRR*****02 SRR*****02     Group1
SRR*****03 SRR*****03     Group1
SRR*****04 SRR*****04     Group1
SRR*****05 SRR*****05     Group1
SRR*****06 SRR*****06     Group2
SRR*****07 SRR*****07     Group1
SRR*****08 SRR*****08     Group1
SRR*****09 SRR*****09     Group2
SRR*****10 SRR*****10     Group2
SRR*****11 SRR*****11     Group1
SRR*****12 SRR*****12     Group2
SRR*****13 SRR*****13     Group1
SRR*****14 SRR*****14     Group2
SRR*****15 SRR*****15     Group1
SRR*****16 SRR*****16     Group2
SRR*****17 SRR*****17     Group2
SRR*****18 SRR*****18     Group2
SRR*****19 SRR*****19     Group2
SRR*****20 SRR*****20     Group1
SRR*****21 SRR*****21     Group1
SRR*****22 SRR*****22     Group1
SRR*****23 SRR*****23     Group2
SRR*****24 SRR*****24     Group2
SRR*****25 SRR*****25     Group2
SRR*****26 SRR*****26     Group1
SRR*****27 SRR*****27     Group1
SRR*****28 SRR*****28     Group1

**Comment by jalalsiddiqui** [comment]
[1] "list_allsamples" "Group2"   "Group1"
sampleID     condition
SRR*****01 SRR*****01 Group2
SRR*****02 SRR*****02     Group1
SRR*****03 SRR*****03     Group1
SRR*****04 SRR*****04     Group1
SRR*****05 SRR*****05     Group1
SRR*****06 SRR*****06     Group2
SRR*****07 SRR*****07     Group1
SRR*****08 SRR*****08     Group1
SRR*****09 SRR*****09     Group2
SRR*****10 SRR*****10     Group2
SRR*****11 SRR*****11     Group1
SRR*****12 SRR*****12     Group2
SRR*****13 SRR*****13     Group1
SRR*****14 SRR*****14     Group2
SRR*****15 SRR*****15     Group1
SRR*****16 SRR*****16     Group2
SRR*****17 SRR*****17     Group2
SRR*****18 SRR*****18     Group2
SRR*****19 SRR*****19     Group2
SRR*****20 SRR*****20     Group1
SRR*****21 SRR*****21     Group1
SRR*****22 SRR*****22     Group1
SRR*****23 SRR*****23     Group2
SRR*****24 SRR*****24     Group2
SRR*****25 SRR*****25     Group2
SRR*****26 SRR*****26     Group1
SRR*****27 SRR*****27     Group1
SRR*****28 SRR*****28     Group1

**Comment by kvittingseerup** [comment]
Does your design matrix have 2 or 3 colums? Where does the `[1] "list_allsamples" "Group2" "Group1"` output come from?

Also could you send me the output of running:
```
summary(<your_switchAnalyzeRlist>)
```

And which version of IsoformSwitchAnalyzeR you are running? You can test that with this comand: `packageVersion('IsoformSwitchAnalyzeR')`

**Comment by jalalsiddiqui** [comment]
The design matrix has 2 columns.  list_all_samples is basically the list of the samples. Group1 and Group2 are the 2 groups compared. The two columns are sampleID and condition.

The info needed is as follows.

This switchAnalyzeRlist list contains:
 87852 isoforms from 14471 genes
 1 comparison from 2 conditions (in total 28 samples)

Feature analyzed:
[1] "ORFs, ntSequence"
[1] ‘1.11.3’

Let me know if this is what you need.

**Comment by kvittingseerup** [comment]
That all looks right. Could you try restarting R and trying again?

Which version of DEXSeq and DESeq2 are you using?

**Comment by jalalsiddiqui** [comment]
DEXSeq_1.28.3, DESeq2_1.22.2

**Comment by kvittingseerup** [comment]
Hi Jalal

Could you try updating DEXSeq and DESeq2 to the newest version from:
https://bioconductor.org/packages/release/bioc/html/DESeq2.html
https://bioconductor.org/packages/release/bioc/html/DEXSeq.html

Remember to restart R before re-running the IsoformSwitchAnalyzeR analysis
(necessary before the update take effects).

Cheers
Kristoffer




Den tir. 16. jun. 2020 kl. 22.24 skrev Jalal K. Siddiqui <
notifications@github.com>:

**Comment by jalalsiddiqui** [comment]
Sorry about late reply.  I can do that.  Do you think it is best that use the latest version of R as well?

**Comment by kvittingseerup** [comment]
R 3.6.1 or larger should do it :-)

**Comment by jalalsiddiqui** [comment]
I am still working on trying to get this to install.

The downloaded source packages are in
        ‘/tmp/RtmpzmfxWi/downloaded_packages’
> BiocManager::install("IsoformSwitchAnalyzeR")
Error in get(method, envir = home) : 
  lazy-load database '/users/PAS1143/osu8165/R/x86_64-pc-linux-gnu-library/3.6/BiocManager/R/BiocManager.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
> library(IsoformSwitchAnalyzeR)
Error in library(IsoformSwitchAnalyzeR) : 
  there is no package called ‘IsoformSwitchAnalyzeR’

I am trying to install on R version 3.6.3.

This may be an issue on the end of the cluster.

**Comment by jalalsiddiqui** [comment]
I reinstalled the package on R 4.0 on my laptop and got the following results.

PART 1: EXTRACTING ISOFORM SWTICH SEQUENCES
Step 1 of 3 : Detecting isoform switches...
Step 3 of 3 : Extracting (and outputting) sequences
The 'removeLongAAseq' and 'removeShortAAseq' arguments:
 Removed : 0 isoforms.
 Trimmed : 0 isoforms (to only contain the first 1000 AA)

The number of isoform switches found were:
                  Comparison nrIsoforms nrSwitches nrGenes
1 Non_responder vs Responder          5          6       5
The nucleotide and amino acid sequences of these isoforms have been outputted to the supplied directory. 
These sequences enabling external analysis of protein domians (Pfam), coding potential (CPAT/CPC2) or signal peptides (SignalIP). 
See ?analyzeCPAT, ?analyzeCPC2, ?analyzePFAM or?analyzeSignalIP (under details) for suggested ways of running these three tools.

PART 2: PLOTTING ISOFORM SEQUENCES
Step 1 of 5 : Importing external sequence analysis...
Step 2 of 5 : Analyzing alternative splicing...
Step 3 of 5 : Prediciting functional consequences...
Step 4 of 5 : Making indidual isoform switch plots...
  |=================================================================================================| 100%
Step 5 of 5 : Analyzing combined consequences plot...
Error in extractConsequenceEnrichment(switchAnalyzeRlist = switchAnalyzeRlist,  : 
  No features left for ploting after filtering with via "minEventsForPlotting" argument.
In addition: There were 11 warnings (use warnings() to see them)
> traceback()
4: stop("No features left for ploting after filtering with via \"minEventsForPlotting\" argument.")
3: extractConsequenceEnrichment(switchAnalyzeRlist = switchAnalyzeRlist, 
       alpha = alpha, dIFcutoff = dIFcutoff, plot = TRUE, returnResult = FALSE)
2: isoformSwitchAnalysisPart2(switchAnalyzeRlist = switchAnalyzeRlist, 
       alpha = alpha, dIFcutoff = dIFcutoff, n = n, consequencesToAnalyze = consequencesToAnalyze, 
       pathToOutput = pathToOutput, fileType = fileType, asFractionTotal = asFractionTotal, 
       outputPlots = outputPlots, quiet = quiet)
1: isoformSwitchAnalysisCombined(switchAnalyzeRlist = aSwitchListFiltered, 
       alpha = 0.2, dIFcutoff = 0.1, switchTestMethod = "DEXSeq", 
       n = NA, pathToOutput = "combinedDEXSeq_isar_results", overwriteORF = FALSE, 
       outputSequences = TRUE, genomeObject, orfMethod = "longest", 
       cds = NULL, consequencesToAnalyze = c("intron_retention", 
           "ORF_seq_similarity", "NMD_status"), fileType = "pdf", 
       asFractionTotal = FALSE, outputPlots = TRUE, quiet = FALSE)PART 1: EXTRACTING ISOFORM SWTICH SEQUENCES
Step 1 of 3 : Detecting isoform switches...
Step 3 of 3 : Extracting (and outputting) sequences
The 'removeLongAAseq' and 'removeShortAAseq' arguments:
 Removed : 0 isoforms.
 Trimmed : 0 isoforms (to only contain the first 1000 AA)

The number of isoform switches found were:
                  Comparison nrIsoforms nrSwitches nrGenes
1 Non_responder vs Responder          5          6       5
The nucleotide and amino acid sequences of these isoforms have been outputted to the supplied directory. 
These sequences enabling external analysis of protein domians (Pfam), coding potential (CPAT/CPC2) or signal peptides (SignalIP). 
See ?analyzeCPAT, ?analyzeCPC2, ?analyzePFAM or?analyzeSignalIP (under details) for suggested ways of running these three tools.

PART 2: PLOTTING ISOFORM SEQUENCES
Step 1 of 5 : Importing external sequence analysis...
Step 2 of 5 : Analyzing alternative splicing...
Step 3 of 5 : Prediciting functional consequences...
Step 4 of 5 : Making indidual isoform switch plots...
  |=================================================================================================| 100%
Step 5 of 5 : Analyzing combined consequences plot...
Error in extractConsequenceEnrichment(switchAnalyzeRlist = switchAnalyzeRlist,  : 
  No features left for ploting after filtering with via "minEventsForPlotting" argument.
In addition: There were 11 warnings (use warnings() to see them)
> traceback()
4: stop("No features left for ploting after filtering with via \"minEventsForPlotting\" argument.")
3: extractConsequenceEnrichment(switchAnalyzeRlist = switchAnalyzeRlist, 
       alpha = alpha, dIFcutoff = dIFcutoff, plot = TRUE, returnResult = FALSE)
2: isoformSwitchAnalysisPart2(switchAnalyzeRlist = switchAnalyzeRlist, 
       alpha = alpha, dIFcutoff = dIFcutoff, n = n, consequencesToAnalyze = consequencesToAnalyze, 
       pathToOutput = pathToOutput, fileType = fileType, asFractionTotal = asFractionTotal, 
       outputPlots = outputPlots, quiet = quiet)
1: isoformSwitchAnalysisCombined(switchAnalyzeRlist = aSwitchListFiltered, 
       alpha = 0.2, dIFcutoff = 0.1, switchTestMethod = "DEXSeq", 
       n = NA, pathToOutput = "combinedDEXSeq_isar_results", overwriteORF = FALSE, 
       outputSequences = TRUE, genomeObject, orfMethod = "longest", 
       cds = NULL, consequencesToAnalyze = c("intron_retention", 
           "ORF_seq_similarity", "NMD_status"), fileType = "pdf", 
       asFractionTotal = FALSE, outputPlots = TRUE, quiet = FALSE)

**Comment by kvittingseerup** [comment]
Good that you solved the installation/dependencies problem.

The latest problem is that you "only" find 5 genes with isoform switches and the extractConsequenceEnrichment() function requires 10 genes per default.

Thanks for pointing this out - I will fix it in a future update. In the meantime you can follow the [detailed workflow](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#detailed-workflow) - specifically you can use the switchAnalyzeRlist resulting from running `isoformSwitchAnalysisPart1()` and start from [this step of the detailed workflow](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#importing-external-sequence-analysis).

Cheers
Kristoffer

**Comment by jalalsiddiqui** [comment]
Thanks for all your help.  Greatly appreciate it.  Sorry for the delayed reply
