### ISSUE TITLE
Single cell

### ISSUE THREAD

**Issue by ashokpatowary** [kvittingseerup/IsoformSwitchAnalyzeR#70]
Hi @kvittingseerup 

I have successfully used the tool in bulk tissue samples. Now  I am planning to try it on single cell sequencing. have you tried it in house? Considering there are thousands of cells and their expression at isoform level is low; any suggestion regarding the designMatrix file?

Thanks

**Comment by kvittingseerup** [comment]
Hi Ashok

IsoformSwitchAnalyzeR is not designed for use with single cell data so I cannot recommend this. Also I have yet to see it being demonstrated that isoform switches can be identified in single cell data - have you?

Cheers
Kristoffer

**Comment by ashokpatowary** [comment]
@kvittingseerup 

I tried to check, just as preliminary, by merging cells belonging to same cluster randomly to create pseudo replicate. In such scenario I can see switching in between celltype. But its not scientifically correct.
