### ISSUE TITLE
Error when running part 2

### ISSUE THREAD

**Issue by lukais-i0han** [kvittingseerup/IsoformSwitchAnalyzeR#71]
Hi,

When I run the second part of pipeline I get the following error:

'pathToNetSurfP2resultFile' points to does not exist

I would to know what this error means, and how I can solve it.

**Comment by kvittingseerup** [comment]
Hi Lukais

Thanks for reaching out. I think you just need to update to 1.11.3 as described [here](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html).

Let me know if it works

Cheers
Kristoffer

**Comment by lukais-i0han** [comment]
Hi, Kristoffer

Unfortuneely your suggestion did not work, I still get the same error:

Error in analyzeNetSurfP2(switchAnalyzeRlist = switchAnalyzeRlist, pathToNetSurfP2resultFile = pathToNetSurfP2resultFile,  : 
  (At least on of) the file(s) 'pathToNetSurfP2resultFile' points to does not exist

Cheers,

Lukas

**Comment by kvittingseerup** [comment]
You need to provide a string (by using quotation marks) which points to the
netsurf2 result file on your computer to the pathToNetSurfP2resultFile
argument.

fre. 26. jun. 2020 kl. 03.30 skrev lukais-i0han <notifications@github.com>:

**Comment by lukais-i0han** [comment]
I figured out that I was giving the wrong path to NetSurf results. Thank you for support.

Cheers,

Lukas
