### ISSUE TITLE
Error in sample.int(length(x), size, replace, prob) :    invalid first argument

### ISSUE THREAD

**Issue by Gnojoomi** [kvittingseerup/IsoformSwitchAnalyzeR#73]
Hello, 

This is a valuable package, but I've been a little stuck. 

After loading in the data: 
```
High_SwitchList<-importRdata(isoformCountMatrix=Kallisto_quant$counts,isoformRepExpression=Kallisto_quant$abundance,designMatrix=High,isoformExonAnnoation="/group/runciegrp/SharedResources/Genomes/Zea_mays/B73/AGPv5.0/Zm-B73-REFERENCE-NAM-5.0_Zm00001e.1.gtf",isoformNtFasta="/group/runciegrp/SharedResources/Genomes/Zea_mays/B73/AGPv5.0/Zm-B73-REFERENCE-NAM-5.0.fa.gz",showProgress=TRUE)
```

I get the following error:

```
Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Step 3 of 6: Calculating gene expression and isoform fraction...
     632 ( 0.85%) isoforms were removed since they were not expressed in any samples.
Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument
```

I have no idea from the output what the issue is even might be. I previously had an issue with the GTF file but I manually fixed it by matching the names. 

Any help is welcome!!
Thank you!

**Comment by kvittingseerup** [comment]
Hi 

Thanks for reaching out.

Which version of IsoformSwitchAnalyzeR are you using? Do you get this problen with 1.11.3 which you can obtain as described [here](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html).

Cheers
Kristoffer

**Comment by Gnojoomi** [comment]
Hello again,

I'm sorry for the late reply. I had the older version of
IsoformSwitchAnalyze 1.6.0 on a cluster and I'm not sure when they will
update it.

However, using a different data set and version 1.11.3, I've run into
another issue.
I get this error:

Error in importRdata(isoformCountMatrix = Kallisto_quant$counts,
isoformRepExpression = Kallisto_quant$abundance,  :
  No sequences in the fasta files had IDs matching the expression data.

From this command:
Low_SwitchList<importRdata(isoformCountMatrix=Kallisto_quant$counts,isoformRepExpression=Kallisto_quant$abundance,designMatrix=Low,isoformExonAnnoation="../Zm-B73-REFERENCE-NAM-5.0_Zm00001e.1.gtf",isoformNtFasta="../Zm-B73-REFERENCE-NAM-5.0.fa.gz",showProgress=FALSE,ignoreAfterBar
= TRUE,ignoreAfterSpace = TRUE,ignoreAfterPeriod = TRUE)

**Comment by kvittingseerup** [comment]
Could you post the first couple of lines of the fasta file as well as the result of running this command:

```
head( Kallisto_quant$counts$isoform_id )
```

**Comment by Gnojoomi** [comment]
Hello again,

Thank you very much for your help! You are very kind.

This is the result I get when I do "head
(Kallisto_quant$counts$isoform_id)"

[1] "Zm00001e009486_T001" "Zm00001e035004_T001" "Zm00001e035198_T001"
"Zm00001e034271_T001"
[5] "Zm00001e007861_T001" "Zm00001e002647_T003"

I looked into the fasta file and I get:
 >chr1

TCATGGCTATTTTCATAAAAAATGGGGGTTGTGTGGCCATTTATCATCGACTAGAGGCTCATAAACCTCACCCCACATAT

GTTTCCTTGCCATAGATTACATTCTTGGATTTCT


I believe I should use the cdna.fasta file instead. It has names that match
the Kallisto$counts$isoform_id and looks like this:


>Zm00001e009486_T001
chromosome:Zm-B73-REFERENCE-NAM-5.0:2:1:243675191:1|mikado_gene|protein_coding|CDNA

GTAGAGATGGAGGAGTGTTTGATCACTCCACGGCGAGTCGGCGACGATGTTTTGCTTTGC


When I use the cdna file it seems to work.


Thank you very much,

Saghi Nojoomi

**Comment by kvittingseerup** [comment]
You are right - it should be the cDNA file - sorry for not spotting that when you posted the original question.

Cheers
Kristoffer
