### ISSUE TITLE
Problem with Cufflinks input using preFilter function

### ISSUE THREAD

**Issue by CDieterich** [kvittingseerup/IsoformSwitchAnalyzeR#74]
Dear @kvittingseerup 

I am trying to perform a complete workflow using cufflinks as input

require(IsoformSwitchAnalyzeR)

testSwitchList <- importCufflinksFiles(
pathToGTF = "/Volumes/cdieterich/index/cuffcmp.GRCh38_96.combined.gtf",
pathToGeneDEanalysis = "gene_exp.diff",
pathToIsoformDEanalysis = "isoform_exp.diff",
pathToGeneFPKMtracking = "genes.fpkm_tracking",
pathToIsoformFPKMtracking = "isoforms.fpkm_tracking",
pathToIsoformReadGroupTracking = "isoforms.read_group_tracking",
pathToSplicingAnalysis = "splicing.diff",
pathToReadGroups = "read_groups.info",
pathToRunInfo = "run.info",
isoformNtFasta = "/Volumes/cdieterich/index/cuffcmp.GRCh38_96.combined.fa",
fixCufflinksAnnotationProblem=TRUE,
addIFmatrix = TRUE,
quiet=TRUE
)

 table(testSwitchList$isoformSwitchAnalysis$significant)

    no    yes 
644808    447 

     testSwitchListFilt <- preFilter(testSwitchList, IFcutoff=0, dIFcutoff = 0)

then I get an empty testSwitchListFilt$isoformSwitchAnalysis$significant

Could you please advise how to filter for cufflinks input.

**Comment by kvittingseerup** [comment]
I'm sorry but I'm not sure what you want to do - could you elaborate?

**Comment by CDieterich** [comment]
I want to keep the 447 significant events and proceed with the workflow.

**Comment by CDieterich** [comment]
In your manual you write:
No matter which method is used, all the downstream functionality in IsoformSwitchAnalyzeR (e.g. not only the test) uses two parameters to define a significant isoform switch:

-The alpha argument indicating the FDR corrected P-value (Q-value) cutoff.
-The dIFcutoff argument indicating the minimum (absolute) change in isoform usage (dIF).

The cufflinks yields

range(testSwitchList$isoformFeatures$IF_overall,na.rm=T) =>  0 1
but there are a lot of NaN

range(testSwitchList$isoformFeatures[,"dIF"],na.rm=T)
[1] -1  1

**Comment by kvittingseerup** [comment]
All the NAs are genes/isoforms not tested as well as single isoform genes.

If you want to proceed with the Cufflinks splicing analysis you should just use the following command:

```
testSwitchListFilt <- preFilter(
    switchAnalyzeRlist  = testSwitchList,
    reduceToSwitchingGenes=TRUE,
    reduceFurtherToGenesWithConsequencePotential = TRUE
)
```
This will also take care of all the NAs.

Btw you can summarize what is in the switchAnalyzeRlist using the `summary()`function.

Also unless you have a specific reason for using Cufflinks splicing analysis I will recommend to use the `isoformSwitchTestDEXSeq()` function in IsoformSwitchAnalyzeR,

Cheers
Kristoffer

**Comment by CDieterich** [comment]
Ok, I tried..

but only this worked for me 
testSwitchListFilt <- preFilter(
    switchAnalyzeRlist  = testSwitchList,
    reduceToSwitchingGenes=TRUE, geneExpressionCutoff = NULL,
    reduceFurtherToGenesWithConsequencePotential = TRUE
)

**Comment by kvittingseerup** [comment]
Sounds good - just remember that if you dont use the `geneExpressionCutoff` argument you might have some very lowly expressed features.

Cheers
Kristoffer
