### ISSUE TITLE
vignette needs unique headers 

### ISSUE THREAD

**Issue by mikelove** [kvittingseerup/IsoformSwitchAnalyzeR#8]
I tweeted this but just noticed you have a GH page for issues

If you click on "Workflow Overview" in Quick Start it takes you way down the page to another place where that header occurs

![screen shot 2018-05-18 at 12 37 26 pm](https://user-images.githubusercontent.com/69203/40247106-46462c28-5a99-11e8-84fa-78c55e9a2f1a.png)

**Comment by kvittingseerup** [comment]
Thanks for pointing it out! - Will be fixed in the next update :)
