### ISSUE TITLE
Comparing total number of alternatively spliced genes

### ISSUE THREAD

**Issue by rmurray2** [kvittingseerup/IsoformSwitchAnalyzeR#80]
We are analyzing time course RNASeq data, four developmental stages in total, so three consecutive stage transition comparisons (1 -> 2), (2 -> 3), (3 -> 4). 

When I use IsoformSwitchAnalyzerR, two of the stage transitions give >200 genes as being significantly alternatively spliced, and one gives only ~30. I used isoformSwitchAnalysisPart1 and isoformSwitchAnalysisPart2 with default settings, and each condition had seven replicates. The sequences were aligned with salmon without using the --keep-duplicates option (in fact I got a warning for all analysis that " 402 isoforms were only found in the annotation" and that this could be due to salmon being used  in this particular way) 

This is a potentially interesting result, but I just want to confirm that we can confidently make the statement that there seems to be a rather large difference in global alternative splicing usage between the developmental conditions. I'm also curious as to what other parameters I should look at more carefully to verify whether or not this is the case. Could you give any guidance on this point? 

Much appreciated

**Comment by kvittingseerup** [comment]
Sounds like it - although the definition of "rather large" is rather vague - and what number would constitue a large change in your model system I cannot say. You will have to determine that for yourself :-)

Sounds like something were you, as you probably already have done, would use the [global AS analysis](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#splicing-enrichment-analysis) build into IsoformSwitchAnalyzeR.

Cheers
Kristoffer
