### ISSUE TITLE
Error in importRdata

### ISSUE THREAD

**Issue by yaccos** [kvittingseerup/IsoformSwitchAnalyzeR#81]
When trying to import data from StringTie, I was stopped by a bug on line 4162 in `import_data.R` (https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/blob/83fbe048ab283a33f8f920cfe35519f13de64794/R/import_data.R#L4162), were the `paste` function does not get the value of the last argument as this line is commented out. Alternatively, if you did not intend to print the final newline, the last comma on line 4161 must be removed.

**Comment by kvittingseerup** [comment]
Thanks for reaching out. I've fixed this in IsoformSwitchAnalyzeR 1.13.01 which you can get from the github via:

```
if (!requireNamespace("devtools", quietly = TRUE)){
    install.packages("devtools")
}
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```

Let me know if it works.
