### ISSUE TITLE
Strings for filepaths should support inheritance

### ISSUE THREAD

**Issue by yaccos** [kvittingseerup/IsoformSwitchAnalyzeR#82]
For the argument `pathToCPC2resultFile` and the other arguments referring to external results file paths, the function checks whether the argument is of the type `character` (https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/blob/8f6a04530793342ef18782d99530bef41cd1ed74/R/analyze_external_sequence_analysis.R#L221). However, this checking fails when the argument is of a class inherited from `character`, which for instance is a problem when generating the argument using the `glue` package (https://github.com/tidyverse/glue). The proper way to do such checks is `inherits(pathToCPC2resultFile,"character")`

**Comment by kvittingseerup** [comment]
Thanks for the suggestion. I'll look into it but since all of IsoformSwitchAnalyzeR works on strings it is a larger undertaking.

In the mean time I guess `as.character()` would do the trick for you?

Cheers
Kristoffer

**Comment by yaccos** [comment]
I worked around the problem by using `unclass()`, but `as.character()` would also be a decent solution.
