### ISSUE TITLE
Error in evaluating the argument 'con' in selecting a method for function 'import'

### ISSUE THREAD

**Issue by helenysl** [kvittingseerup/IsoformSwitchAnalyzeR#83]
I was able to create the switchAnalyzeRlist a few months ago, 

    ### Create switchAnalyzeRlist
    aSwitchList <- importRdata(
      isoformCountMatrix   = salmonQuant$counts,
      isoformRepExpression = salmonQuant$abundance,
      designMatrix         = myDesign,
      isoformExonAnnoation = "./Mus_musculus.GRCm38.100.chr_patch_hapl_scaff.gtf.gz",
      isoformNtFasta       = "./Mus_musculus.GRCm38.cdna.all.fa.gz",
      showProgress = TRUE
      )

but recently I kept encountering this error:
 
    Step 1 of 7: Checking data...
    Please note that some condition names were changed due to names not suited for modeling in R.
    Step 2 of 7: Obtaining annotation...
        importing GTF (this may take a while)
    Error in h(simpleError(msg, call)) : 
      error in evaluating the argument 'con' in selecting a method for function 'import': invalid class "GFF2File" object: undefined 
    class for slot "resource" ("characterORconnection")`

Actually, I also first ran into the same error as posted by https://github.com/kvittingseerup/IsoformSwitchAnalyzeR/issues/65, then I updated my R to 4.0.3 and the error message became the above one.
Any suggestion to fix this? 
Thank you.

**Comment by kvittingseerup** [comment]
Try updating to IsoformSwitchAnalyzeR 1.13.01 via github by copy pasting this into your R session:

```
if (!requireNamespace("devtools", quietly = TRUE)){ install.packages("devtools") }
devtools::install_github("kvittingseerup/IsoformSwitchAnalyzeR", build_vignettes = TRUE)
```
Remember to restart R before trying the import again.

**Comment by helenysl** [comment]
It finally works! Thank you so much!

**Comment by kvittingseerup** [comment]
Good to hear - then you should close the issue ;-)
