### ISSUE TITLE
stringtie→importRdata:  Error in eval(quote(list(...)), env) 

### ISSUE THREAD

**Issue by wsai0219** [kvittingseerup/IsoformSwitchAnalyzeR#87]
sorry to bother you. When import stringtie data, I met a error. Do you know why?
Especially,what does the "Error in eval(quote(list(...)), env) " mean?
I worked on this whole night, then have to ask for help~~

Best wishes to you!
#----------#---------
> aSwitchList <- importRdata(
+   isoformCountMatrix = StringtieQuant_ws$counts,
+   isoformRepExpression = StringtieQuant_ws$abundance,
+   designMatrix = myDesign,
+   isoformNtFasta = NULL,
+   isoformExonAnnoation = isoformExonAnnoation_ws,
+   fixStringTieAnnotationProblem = TRUE,
+   showProgress = TRUE,
+   comparisonsToMake = comparisionsToMake_ws,
+   addAnnotatedORFs = FALSE
+   )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
    4567 ( 3.23%) isoforms were removed since they were not expressed in any samples.
Step 3 of 7: Fixing StringTie gene annoation problems...
    27104 isoforms were assigned the gene_name of their associated gene_id. 
        This was only done when the parent gene_id were associated with a single gene_name.
    15102 isoforms were assigned the gene_name of the most similar 
        annotated isoform (defined via overlap in genomic exon coordinates). 
        This was only done if the overlap met the requriements 
        indicated by the three fixStringTieViaOverlap* arguments.
Error in eval(quote(list(...)), env) : 
  argument is missing, with no default
In addition: Warning message:
In importRdata(isoformCountMatrix = StringtieQuant_ws$counts, isoformRepExpression = StringtieQuant_ws$abundance,  :
  The number of comparisons (n=9) is unusually high.
 - If this intended please note that with a large number of comparisons IsoformSwitchAnalyzeR might use quite a lot of memmory (aka running on a small computer might be problematic).
 - If this was not intended please check the supplied design matrixt to make sure no mistakes were made.

**Comment by wsai0219** [comment]
2020.12.4Fri
the comparison was then made between 2 groups, but the error is the same.
#----------#---------
> condition_1 <- c("BC")
> condition_2 <- c("GC")
> comparisionsToMake_ws <- data.frame(condition_1,condition_2)
> aSwitchList <- importRdata(
+   isoformCountMatrix = StringtieQuant_ws$counts,
+   isoformRepExpression = StringtieQuant_ws$abundance,
+   designMatrix = myDesign,
+   isoformNtFasta = NULL,
+   isoformExonAnnoation = isoformExonAnnoation_ws,
+   fixStringTieAnnotationProblem = TRUE,
+   showProgress = TRUE,
+   comparisonsToMake = comparisionsToMake_ws,
+   addAnnotatedORFs = FALSE
+   )
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
    14209 ( 10.04%) isoforms were removed since they were not expressed in any samples.
Step 3 of 7: Fixing StringTie gene annoation problems...
    24317 isoforms were assigned the gene_name of their associated gene_id. 
        This was only done when the parent gene_id were associated with a single gene_name.
    13171 isoforms were assigned the gene_name of the most similar 
        annotated isoform (defined via overlap in genomic exon coordinates). 
        This was only done if the overlap met the requriements 
        indicated by the three fixStringTieViaOverlap* arguments.
Error in eval(quote(list(...)), env) : 
  argument is missing, with no default
#----------#---------

**Comment by wsai0219** [comment]
Interestingly, when I FALSE the argument  "fixStringTieAnnotationProblem = FALSE".
The program can be done. It seems that there is something wrong with the step 3 of 7 "Fixing StringTie gene annoation problems".
Is this OK?
#----------#---------
> aSwitchList <- importRdata(
+   isoformCountMatrix = StringtieQuant_ws$counts,
+   isoformRepExpression = StringtieQuant_ws$abundance,
+   designMatrix = myDesign,
+   isoformNtFasta = NULL,
+   isoformExonAnnoation = isoformExonAnnoation_ws,
+   fixStringTieAnnotationProblem = FALSE,
+   showProgress = TRUE,
+   comparisonsToMake = comparisionsToMake_ws,
+   addAnnotatedORFs = FALSE)
Step 1 of 7: Checking data...
Step 2 of 7: Obtaining annotation...
    importing GTF (this may take a while)
Done.
    14209 ( 10.04%) isoforms were removed since they were not expressed in any samples.
Step 4 of 7: Calculating gene expression and isoform fractions...
Step 5 of 7: Merging gene and isoform expression...
  |======================================================================| 100%
Step 6 of 7: Making comparisons...
  |======================================================================| 100%
Step 7 of 7: Making switchAnalyzeRlist object...
The GUESSTIMATED number of genes with differential isoform usage are:
  comparison estimated_genes_with_dtu
1    GC - BC              1436 - 2393
Done
#----------#---------

**Comment by kvittingseerup** [comment]
Thanks for reaching out. 

You need to update to IsoformSwitchAnalyzeR 1.13.01 as described [here](https://bioconductor.org/packages/devel/bioc/html/IsoformSwitchAnalyzeR.html).

And you are right it was a problem (with a message) in the StringTie rescue.

Cheers
Kristoffer
