### ISSUE TITLE
extracted gene count  matrix was normalized or not ?

### ISSUE THREAD

**Issue by wsai0219** [kvittingseerup/IsoformSwitchAnalyzeR#92]
sorry to bother you again. 
as you said in the vignette,
#----------#---------
Extract gene count matrix
geneCountMatrix <- extractGeneExpression(
    switchAnalyzeRlist,
    extractCounts = TRUE
)
#----------#---------
This count matrix can be used as input to differential expression tools such as edgeR, DESeq2, limma.
#----------#---------
★as I know, these tools may perform normalization, so the input should be raw counts. 
Importantly, the counts should not be normalized twice.
The counts extracted by extractGeneExpression()  is raw or has been normalized?
I looked through the whole manual, but can not get the answer. 
Please help me, thank you very much.

Best wishes to you!!!  ^_^

**Comment by Pinolinoo** [comment]
Hi, I have the same issue and am wondering why if I do the above the exported Count Matrix has non-integer values?

**Comment by kvittingseerup** [comment]
That is not stagnge. It is because it is the estimated counts. The `extractGeneExpression()` result is the same as can be generated with `tximport` - there are no extra steps or treatments involved.

**Comment by Pinolinoo** [comment]
thank you for your quick reply! How are those estimated reads obtained? Is this documented somewhere?

**Comment by kvittingseerup** [comment]
That is done by tximport - take a look in their [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html) :)

**Comment by Pinolinoo** [comment]
ok thank you!

**Comment by Pinolinoo** [comment]
I have another question. Is it normal that after the stringtie rescue algorithm my countmatrix still has about roughly 50% entries with MSTRG Ids and not know gene_ids?

**Comment by kvittingseerup** [comment]
The number of MSTRG transcripts you end up with entirely depends on the dataset and the organism you work with. I have seen both larger and smaller numbers. What were the ratio before the rescue.

For DEXSeq you just use the round() function (that is also what DEXSeq does itself under when using DESeqDataSetFromTximport).

**Comment by Pinolinoo** [comment]
I am working with a human genome and before generating the aSwitchlist the stringtie_quant gave me 199888 MSTRG Ids and 188121 ENST Ids. 

Is this also valid for DESeq2 if I want to do differential gene expression analysis? 
Also when I find Genes or transcripts with MSTRG Id that are differentially expressed, how would I go about to find more about this gene?

**Comment by kvittingseerup** [comment]
Yes it is valid for DESeq2.

Also please not isoformSwitchAnalyzeR fixes gene_id's - not transcript_ids :-).

For the post analysis start by looking at which genes they are annotated to. You can also looking in a genome browser like [UCSC](http://genome.ucsc.edu/cgi-bin/hgGateway) for other annotation overlap.

**Comment by Pinolinoo** [comment]
Ok thank you. 
I've now done the DGE analysis with the estimated counts as a basis (STAR -> Stringtie -> Isoformswitchanalyzer -> DESeq2). However the results differ immensly from the DGE analysis I did without stringtie (STAR -> featurecounts -> DESeq2) and also from the analysis I did when using featurecounts to count the output of stringtie (STAR -> Stringtie -> featurecounts -> DESeq2).. can this be true or did I do a mistake? And if there is no mistake which results should I trust?

**Comment by kvittingseerup** [comment]
I would trust the `STAR -> Stringtie -> Isoformswitchanalyzer -> DESeq2` or `STAR -> Stringtie -> tximport -> DESeq2` reults more. I expect results based on featureCounts to be different since that is a sub-optimal (outdated) thing to do (you can read more about that [here](https://bioconductor.org/packages/devel/bioc/vignettes/IsoformSwitchAnalyzeR/inst/doc/IsoformSwitchAnalyzeR.html#what-quantification-tools-should-i-use)).

If I was you I would start looking into similarities of the different quantification approaches before you do any differential expression analysis. Also maybe throw in a StringTie quantification of only known reference genes.

Let me know what you find.
