### ISSUE TITLE
Stringtie importRdata Stringtie Error

### ISSUE THREAD

**Issue by raita1227** [kvittingseerup/IsoformSwitchAnalyzeR#98]
`
TGFBvsCTRLSwitchListAnalyzed <- importRdata(
  isoformCountMatrix   = imported_VehVillivsCrypts$counts,
  isoformRepExpression = imported_VehVillivsCrypts$abundance,
  designMatrix         = TableForISAR_VehVillivsCrypts,
  isoformExonAnnoation = "ForIsoformAnalysis/VehVillivsCrypts_ForIsoformAnalysis.merged.annotated.gtf",
  comparisonsToMake=ComparisonsToMake_VehVillivsCrypts,
  fixStringTieAnnotationProblem = TRUE
)
`
**I am using Stringtie output from HISAT2/Stringtie pipeline for RNA-seq and running into this problem. The gtf file was obtained from using gffcompare on the merged gtf file according to step 5 of [HISAT2/Stringtie Pipeline](https://www.nature.com/articles/nprot.2016.095.) I am stuck and would greatly appreciate any help. I am using IsoformSwitchAnalyzeR version 1.12.0**

Step 1 of 6: Checking data...
Step 2 of 6: Obtaining annotation...
    importing GTF (this may take a while)
Error in importRdata(isoformCountMatrix = imported_VehVillivsCrypts$counts,  : 
  The annotation and quantification (count/abundance matrix and isoform annotation) seems to be different (Jaccard similarity < 0.925). 
Either isforoms found in the annotation are not quantifed or vise versa. 
Specifically:
 53429 isoforms were quantified.
 52274 isoforms are annotated.
 Only 38651 overlap.
 14778 isoforms quantifed isoforms had no corresponding annoation
 
This combination cannot be analyzed since it will cause discrepencies between quantification and annotation thereby skewing all analysis.
 
If there is no overlap (as in zero or close) there are two options:
 1) The files do not fit together (e.g. different databases, versions, etc) (no fix except using propperly paired files).
 2) It is somthing to do with how the isoform ids are stored in the different files. This problem might be solvable using some of the 'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.
     Examples from expression matrix are : MSTRG.3348.1, MSTRG.5745.3, NM_001159320 
     Examples of annoation are : NR_040408, NM_008867, NM_026177 
     Examples of isoforms which were only found im the quantification are  : MSTRG.11137.4, MSTRG.14792.1, MSTRG.14236.2 
 
If there is a large overlap but still far from complete there are 3 possibilites:
 1) The files do not fit together (e.g different databases versions etc.) (no fix except using propperly paired files).
 2) If you are using Ensembl data you have supplied the GTF without phaplotyps. You need to supply the <Ensembl_version>.chr_patch_hapl_scaff.gtf file - NOT the <Ensembl_version>.chr.gtf
 3) One file could contain non-chanonical chromosomes while the other do not (might be solved using the 'removeNonConvensionalChr' argument.)
 4) It is somthing to do with how a subset of the isoform ids are stored in the different files. This problem might be solvable using some of the 'ignoreAfterBar', 'ignoreAfterSpace' or 'ignoreAfterPeriod' arguments.

 
For more info see the FAQ in the vignette.
In addition: Warning message:
In importRdata(isoformCountMatrix = imported_VehVillivsCrypts$counts,  :
     No CDS annotation was found in the GTF files meaning ORFs could not be annotated.
     (But ORFs can still be predicted with the analyzeORF() function)

**Comment by kvittingseerup** [comment]
I think the problem might be that you use gffcompare. If you look at this overview [figure at the StringTie webside](https://ccb.jhu.edu/software/stringtie/index.shtml?t=manual#de) you need to run `stringtie --merge` to get the merged file.

Did you also do that? Which GTF file did you use to re-quantify the samples as also seen in the StringTie overview figure?

**Comment by raita1227** [comment]
So I had made a merged gtf file to requantify the samples by following the
protocol instructions. Gffcompare was run on this merged gtf file to obtain
an annotated gtf file. I run into the same error with either gtf file.

**Comment by raita1227** [comment]
Actually I was able to fix the problem, it was due to using samples from
the wrong batches. Thanks for your help.
